Repository antrea-io/antrea, pull requests merged in 2020-10, with the labels that each got.

#1315 Add introductions of features to getting-started and architecture docs
  README.md
  docs/antrea-network-policy.md
  docs/architecture.md
  docs/eks-terraform.md
  docs/feature-gates.md
  docs/getting-started.md
  docs/ovs-pipeline.md
Labels: cla-not-required

#1324 Update ovs-pipeline.md for Antrea Policy changes as of v0.10
  docs/assets/ovs-pipeline.svg
  docs/ovs-pipeline.md
Labels: cla-not-required

#1239 Add check for table of contents
  .github/workflows/go.yml
  Makefile
  docs/antctl.md
  docs/antrea-network-policy.md
  docs/issue-management.md
  docs/network-flow-visibility.md
  docs/securing-control-plane.md
  docs/traceflow-guide.md
  docs/troubleshooting.md
  hack/.notableofcontents
  hack/mdtoc-version
  hack/update-toc.sh
  hack/verify-toc.sh
Labels: cla-not-required

#1329 Use logrotate to rotate OVS log files
  build/images/ovs/Dockerfile
  build/images/scripts/start_ovs
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
Labels: cla-not-required

#1340 Support get/set log verbosity level by antctl and controller/agent API
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/antctl.yml
  docs/antctl.md
  pkg/agent/apiserver/apiserver.go
  pkg/antctl/antctl.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_list.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/handlers/loglevel/handler.go
  pkg/log/log_level.go
Labels: cla-not-required

#1337 Use the OVS upstream commit for the strongSwan config format fix
  build/images/ovs/apply-patches.sh
Labels: cla-not-required

#1296 Start document with security recommendations
  docs/security.md
Labels: cla-not-required, kind/documentation

#1343 Fixes #1333: Broken link in octant-plugin-installation.md doc
  docs/octant-plugin-installation.md
Labels: cla-not-required

#1344 Add docs/security.md to .notableofcontents
  hack/.notableofcontents
Labels: cla-not-required

#1336 Check and ignore ANP and ACNP in agent when AntreaPolicy is not enabled
  cmd/antrea-agent/agent.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#1346 Hardcode Github action actions/stale version to v3.0.8
  .github/workflows/lifecycle_management.yml
Labels: cla-not-required

#726 Document Antrea component metrics
  .github/workflows/kind.yml
  build/yamls/antrea-prometheus-rbac.yml
  ci/kind/kind-setup.sh
  ci/kind/validate-metrics-doc.sh
  docs/code-generation.md
  docs/prometheus-integration.md
  hack/generate-manifest.sh
  hack/make-metrics-doc.sh
Labels: cla-not-required

#1345 Change Windows demo video link to the one in ProjectAntrea channel
  docs/windows.md
Labels: cla-not-required

#1356 Fix version unsupported issue in AKS Jenkins job
  ci/jenkins/README.md
  ci/test-conformance-aks.sh
Labels: cla-not-required

#1359 Ensure appliedTo and priority is required for ACNP
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  test/e2e/antreapolicy_test.go
Labels: cla-not-required

#1323 Add kubectl commands to network policy docs
  docs/antrea-network-policy.md
Labels: cla-not-required

#1353 Add line breaks in metrics list for readability
  docs/prometheus-integration.md
  hack/make-metrics-doc.sh
Labels: cla-not-required

#1320 Upgrade the Kind version used for CI
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  build/images/ethtool/Dockerfile
  build/images/ethtool/README.md
  ci/kind/config-2nodes.yml
  ci/kind/config-3nodes.yml
  ci/kind/kind-setup.sh
  docs/kind.md
Labels: cla-not-required

#1326 Add enhancement for OpenFlow control interface
  go.mod
  go.sum
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/ovs/ofctrl_test.go
Labels: cla-not-required

#1381 Reorder Service&Endpoint handling order
  pkg/agent/proxy/proxier.go
Labels: cla-not-required

#1373 [IPv6] Skip IPsec e2e test
  test/e2e/framework.go
  test/e2e/ipsec_test.go
Labels: cla-not-required

#1331 Register consecutive priorities in batch
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/priority.go
  pkg/agent/controller/networkpolicy/priority_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/types/networkpolicy.go
Labels: cla-not-required

#1378 Set Traceflow TCP flag from antrea-octant-plugin
  plugins/octant/cmd/antrea-octant-plugin/traceflow.go
Labels: cla-not-required

#1386 TCP flags should be 2 when svc as dest in Traceflow
  pkg/agent/controller/traceflow/traceflow_controller.go
Labels: cla-not-required

#1370 Fix inconsistent definition of IPFIX field in Kibana
  build/yamls/elk-flow-collector/kibana.ndjson
Labels: cla-not-required

#1334 Use consistent function names in networkpolicy controller unittest
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#1385 Add support to match port with a mask
  go.mod
  go.sum
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/testing/mock_openflow.go
  plugins/octant/go.sum
  test/integration/ovs/ofctrl_test.go
Labels: cla-not-required

#1348 Move contributor docs and design docs to separate directories
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/antctl.md
  docs/contributors/code-generation.md
  docs/contributors/eks-terraform.md
  docs/contributors/github-labels.md
  docs/contributors/issue-management.md
  docs/contributors/manual-installation.md
  docs/design/architecture.md
  docs/design/ovs-pipeline.md
  docs/design/policy-only.md
  docs/design/windows-design.md
  docs/getting-started.md
  docs/network-flow-visibility.md
  docs/octant-plugin-installation.md
  docs/windows.md
  hack/.notableofcontents
Labels: cla-not-required

#1387 Retrieve featuregate status in e2e tests
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/e2e/proxy_test.go
Labels: cla-not-required

#1364 Cleanup: remove send_redirects sysctl configuration
  build/yamls/base/agent.yml
  docs/security.md
  pkg/agent/route/route_linux.go
Labels: cla-not-required

#1399 [IPv6] Add 2 Network Policy tests
  test/e2e/fixtures.go
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#1398 Fix issue in UDP/SCTP Service flow in Antrea Proxy
  pkg/ovs/openflow/ofctrl_action.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1419 Add kind/task Github label
  docs/contributors/github-labels.md
  docs/contributors/issue-management.md
Labels: kind/documentation

#1420 Update from go 1.13 to go 1.15
  .github/workflows/clair.yml
  .github/workflows/go.yml
  .github/workflows/golicense.yml
  .github/workflows/integration.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  CONTRIBUTING.md
  Makefile
  build/images/Dockerfile.build.coverage
  build/images/Dockerfile.build.ubuntu
  build/images/Dockerfile.build.windows
  build/images/Dockerfile.octant.ubuntu
  build/images/codegen/Dockerfile
  build/images/codegen/README.md
  build/images/test/Dockerfile
  ci/clair-scan/go.mod
  ci/clair-scan/go.sum
  docs/contributors/manual-installation.md
  go.mod
  hack/netpol/Makefile
  hack/netpol/go.mod
  hack/netpol/go.sum
  hack/netpol/install.yml
  hack/tidy-check.sh
  hack/windows/Install-DevTools.ps1
  plugins/octant/go.mod
Labels: cla-not-required

#1352 Document Antrea versioning
  docs/versioning.md
Labels: cla-not-required

#1393 Add kubectl example to sort Tiers by priority
  docs/antrea-network-policy.md
Labels: cla-not-required

#1397 Enhance Traceflow e2e test
  test/e2e/fixtures.go
  test/e2e/traceflow_test.go
Labels: cla-not-required

#1394 Add a config option to disable SNAT in the noEncap mode
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#1321 Support flow exporter feature for Windows
  build/yamls/antrea-windows.yml
  build/yamls/windows/base/conf/antrea-agent.conf
  cmd/antrea-agent/agent.go
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/agent/flowexporter/connections/conntrack_linux.go
  pkg/agent/flowexporter/connections/conntrack_linux_test.go
  pkg/agent/flowexporter/connections/conntrack_ovs.go
  pkg/agent/flowexporter/connections/conntrack_windows.go
  pkg/agent/flowexporter/connections/testing/mock_connections.go
  test/integration/agent/flowexporter_test.go
Labels: cla-not-required

#1430 Sanity checks for IPsec
  build/images/scripts/start_ovs_ipsec
  pkg/agent/agent.go
Labels: cla-not-required

#1435 Small updates of table 70 and 80 in ovs-pipeline.md
  docs/design/ovs-pipeline.md
Labels: cla-not-required

#1414 Support Pod traffic shaping
  build/images/base/Dockerfile
  build/images/scripts/install_cni
  build/images/scripts/install_cni_kind
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-cni.conflist
  build/yamls/offload/mellanox/antrea-crd.yml
  build/yamls/patches/coverage/startAgentCov.yml
  docs/configuration.md
  docs/contributors/manual-installation.md
  docs/design/architecture.md
  docs/ovs-offload.md
  test/e2e/bandwidth_test.go
  test/e2e/fixtures.go
  test/e2e/flowexporter_test.go
  test/e2e/framework.go
  test/e2e/proxy_test.go
Labels: cla-not-required

#1437 Fix typo in antrea-agent configuration comments
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/config.go
Labels: cla-not-required

#1423 [Windows] Set OVS version after ovs-vswitchd started
  hack/windows/Install-OVS.ps1
Labels: cla-not-required

#1443 Improve documentation of gateway CT mark
  docs/design/ovs-pipeline.md
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#1446 Correct unit test file names of endpoint_querier.go
  pkg/controller/networkpolicy/endpoint_querier_perf_test.go
  pkg/controller/networkpolicy/endpoint_querier_test.go
Labels: cla-not-required

#1425 Do not track UDP encapsulation packets in host network
  cmd/antrea-agent/agent.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/route/testing/mock_route.go
  pkg/agent/util/ipset/ipset.go
  pkg/agent/util/iptables/iptables.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#1449 Provide IPv6 version of ipfix-collector Docker image
  build/images/ipfix-collector/Dockerfile
  build/images/ipfix-collector/README.md
  test/e2e/fixtures.go
Labels: cla-not-required

#1380 Remove ServiceCIDR dependency in Flow Exporter
  cmd/antrea-agent/agent.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/connections_test.go
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/agent/flowexporter/connections/conntrack_linux.go
  pkg/agent/flowexporter/connections/conntrack_linux_test.go
  pkg/agent/flowexporter/connections/conntrack_ovs.go
  pkg/agent/flowexporter/connections/conntrack_windows.go
  pkg/agent/flowexporter/types.go
  pkg/agent/openflow/pipeline.go
  test/integration/agent/flowexporter_test.go
Labels: cla-not-required

#1460 Skip 2 Network Policy testcases before Network Policy IPv6 is supported
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#1464 remove verbose logging so that the handler.OnServiceUpdate doesnt spam
  docs/windows.md
Labels: cla-not-required
