Repository antrea-io/antrea, pull requests merged in 2020-05, with the labels that each got.

#623 Update README.md
  README.md
Labels: cla-not-required, kind/documentation

#672 Register antrea_agent_local_pod_count metric
  pkg/agent/metrics/prometheus.go
Labels: cla-not-required

#673 Fix udp_dst and sctp_dst in flow matching string
  pkg/ovs/openflow/ofctrl_builder.go
Labels: cla-not-required

#540 Added design doc for policy-only mode.
  docs/assets/policy-only-cni.svg
  docs/policy-only.md
Labels: cla-not-required

#682 Add namespace parameter to `podWaitForIP`
  test/e2e/antctl_test.go
  test/e2e/bandwidth_test.go
  test/e2e/basic_test.go
  test/e2e/connectivity_test.go
  test/e2e/fixtures.go
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
  test/e2e/performance_test.go
  test/e2e/upgrade_test.go
Labels: cla-not-required

#677 Update troubleshooting instructions for antrea-agent API
  docs/troubleshooting.md
Labels: cla-not-required

#676 Do not add tailing spaces to rows in antctl single column output table
  pkg/antctl/command_definition.go
Labels: cla-not-required

#679 Add Hybrid, NoEncap, NetworkPolicyOnly modes to architecture.md
  docs/architecture.md
Labels: cla-not-required

#675 Document antctl troubleshooting commands
  docs/antctl.md
  docs/troubleshooting.md
Labels: cla-not-required

#687 Fix incorrect antctl example and output
  pkg/agent/apiserver/handlers/agentinfo/handler.go
  pkg/antctl/antctl.go
Labels: cla-not-required

#686 Fix flaky unit test TestAddNetworkPolicyWithMultipleRules
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#639 Fix network policy overlapping issue
  docs/ovs-pipeline.md
  hack/netpol/pkg/main/main.go
  hack/netpol/pkg/utils/networkpolicyspecbuilder.go
  hack/netpol/pkg/utils/utils_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/types/networkpolicy.go
  pkg/antctl/transform/rule/transform.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
  test/integration/agent/openflow_test.go
Labels: area/network-policy/match, cla-rejected, kind/bug

#688 Add lister and informer to codegen image
  build/images/codegen/Dockerfile
Labels: cla-not-required

#696 Update codegen image before generating
  hack/update-codegen.sh
Labels: cla-not-required, size/XS

#691 Fix return path for NodePort Service traffic in EKS
  Makefile
  build/yamls/antrea-eks.yml
  build/yamls/patches/eks/eksEnv.yml
  ci/test-conformance-eks.sh
  hack/generate-manifest.sh
  pkg/agent/route/route_linux.go
  pkg/util/env/env.go
Labels: cla-not-required

#698 Fix antrea-agent not working with iptables>=1.6.2
  pkg/agent/util/iptables/iptables.go
  pkg/agent/util/iptables/lock.go
Labels: cla-not-required

#705 Skip NodePort testcases for EKS
  ci/run-k8s-e2e-tests.sh
  ci/test-conformance-eks.sh
Labels: cla-not-required

#699 [Windows] Fix issue: NodePort service can't be accessed from local Pod
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#693 Scan the latest antrea-ubuntu Docker image for vulnerabilities
  .github/workflows/clair.yml
  ci/clair-scan/.gitignore
  ci/clair-scan/README.md
  ci/clair-scan/analyze.go
  ci/clair-scan/go.mod
  ci/clair-scan/go.sum
  ci/clair-scan/main.go
  ci/clair-scan/notify.go
  ci/clair-scan/report.go
  ci/clair-scan/run.sh
Labels: cla-not-required

#707 Checking cluster status with kubectl locally
  test/e2e/README.md
Labels: kind/documentation

#710 Send results of Docker vulnerability scans to Antrea mailing lists
  ci/clair-scan/go.mod
  ci/clair-scan/go.sum
  ci/clair-scan/main.go
  ci/clair-scan/notify.go
  ci/clair-scan/run.sh
Labels: cla-not-required

#683 Expose API port in AgentInfo and ControllerInfo
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  pkg/agent/querier/querier.go
  pkg/apis/clusterinformation/v1beta1/types.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/querier/querier.go
Labels: area/api, cla-not-required, kind/api-change

#715 Remove unused binaries from image
  Makefile
  build/images/Dockerfile.build.ubuntu
  build/images/Dockerfile.octant.ubuntu
  docs/octant-plugin-installation.md
Labels: cla-not-required

#717 Ensure order while asserting equal
  pkg/agent/config/traffic_encap_mode_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#704 Clean up stale NetworkPolicies after reconnection
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/apiserver/storage/interfaces.go
  pkg/apiserver/storage/ram/store.go
  pkg/apiserver/storage/ram/store_test.go
  pkg/apiserver/storage/ram/watch.go
  pkg/apiserver/storage/ram/watch_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/addressgroup_test.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
  pkg/controller/networkpolicy/store/appliedtogroup_test.go
  pkg/controller/networkpolicy/store/networkpolicy.go
  pkg/controller/networkpolicy/store/networkpolicy_test.go
  test/e2e/antctl_test.go
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#721 Support getting kubeconfig path from KUBECONFIG env variable
  pkg/antctl/client.go
  pkg/antctl/command_list.go
Labels: cla-not-required

#722 [Windows]Use windows named pipe for CNI connection
  go.mod
  pkg/agent/cniserver/server.go
  pkg/agent/util/net.go
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_windows.go
  pkg/cni/client.go
  pkg/cni/default_windows.go
Labels: cla-not-required

#725 Add GKE conformance test to CI
  ci/jenkins/jobs/job-templates.yaml
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
Labels: cla-not-required

#727 Bump up K8s libraries to v0.17.6
  build/images/Dockerfile.octant.ubuntu
  build/images/codegen/Dockerfile
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/controller-rbac.yml
  cmd/antrea-octant-plugin/main.go
  docs/octant-plugin-installation.md
  go.mod
  go.sum
  hack/tidy-check.sh
  hack/update-codegen.sh
  pkg/antctl/client.go
  pkg/apis/networking/v1beta1/generated.pb.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/client/clientset/versioned/clientset.go
Labels: cla-not-required

#695 [Windows]Add antrea-agent dockerfile and deployment yaml for windows
  Makefile
  build/images/Dockerfile.build.windows
  build/images/scripts/Install-WindowsCNI.ps1
  build/yamls/antrea-windows.yml
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Install-DevTools.ps1
  hack/windows/Install-OVS.ps1
  hack/windows/Prepare-Node.ps1
  hack/windows/Prepare-ServiceInterface.ps1
  hack/windows/Reset-Node.ps1
  hack/windows/Uninstall-OVS.ps1
Labels: cla-not-required

#706 [Windows] Add documentation for Antrea on Windows
  docs/architecture.md
  docs/getting-started.md
  docs/windows.md
Labels: cla-not-required

#714 Support server certificate verification
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/conf/antrea-controller.conf
  build/yamls/base/controller-rbac.yml
  build/yamls/base/controller.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/config.go
  cmd/antrea-controller/controller.go
  cmd/antrea-controller/options.go
  docs/configuration.md
  go.mod
  go.sum
  pkg/agent/client.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/certificate/cacert_controller.go
  pkg/apiserver/certificate/certificate.go
  pkg/apiserver/certificate/certificate_test.go
  pkg/k8s/client.go
  test/e2e/framework.go
  test/e2e/security_test.go
Labels: cla-not-required

#737 Update Jenkins CI README and job lister for Windows CI
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
Labels: cla-not-required

#733 Add Prometheus service account in monitoring NS
  build/yamls/antrea-prometheus.yml
Labels: cla-not-required

#744 Use correct URL for Windows OVS binaries
  hack/windows/Install-OVS.ps1
Labels: cla-not-required

#634 Add support for PacketIn/PacketOut and Geneve header
  go.mod
  go.sum
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/ovs/openflow/ofctrl_flow_test.go
  pkg/ovs/openflow/ofctrl_packetout.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/ovs/ofctrl_test.go
Labels: cla-not-required

#748 Fix integration test failure
  test/integration/ovs/ofctrl_test.go
Labels: cla-not-required

#750 Use K8S metric wrapper
  pkg/agent/metrics/prometheus.go
  pkg/controller/metrics/prometheus.go
Labels: cla-not-required

#745 Build Antrea Windows Docker image as part of CI
  .github/workflows/build.yml
  .github/workflows/build_master.yml
  .github/workflows/build_tag.yml
Labels: cla-not-required

#742 Document Antrea certificate usage and configuration
  docs/getting-started.md
  docs/securing-control-plane.md
Labels: cla-not-required

#753 Mention KUBECONFIG env variable in antctl documentation
  docs/antctl.md
Labels: cla-not-required, kind/documentation, size/XS

#757 Fix conditional step in workflow for pushing latest Antrea images
  .github/workflows/build.yml
Labels: cla-not-required

#754 Use Kustomize to generate release antrea-windows.yml
  .github/workflows/upload_release_assets.yml
  Makefile
  build/yamls/antrea-windows.yml
  build/yamls/windows/base/agent.yml
  build/yamls/windows/base/conf/Run-AntreaAgent.ps1
  build/yamls/windows/base/conf/antrea-agent.conf
  build/yamls/windows/base/conf/antrea-cni.conflist
  build/yamls/windows/base/kustomization.yml
  build/yamls/windows/patches/dev/imagePullPolicy.yml
  build/yamls/windows/patches/release/.gitignore
  ci/check-manifest.sh
  hack/generate-manifest-windows.sh
  hack/release/prepare-assets.sh
Labels: cla-not-required

#743 [Windows] Set Node IP after `kubeadm join` complete
  docs/windows.md
Labels: cla-not-required

#760 Use bash shell for Windows Github workflow jobs
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
Labels: cla-not-required

#755 Upgrade Antrea versions used for upgrade test
  .github/workflows/kind-upgrade.yml
Labels: area/test/infra, cla-not-required

#762 Fix 32-bit arm build of antctl
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#657 Test Prometheus integration in CI
  ci/jenkins/jobs/macros.yaml
  go.mod
  test/e2e/README.md
  test/e2e/infra/vagrant/push_antrea.sh
  test/e2e/prometheus_test.go
Labels: cla-not-required
