Repository antrea-io/antrea, pull requests merged in 2020-02, with the labels that each got.

#339 Update codegen image
  build/images/codegen/Dockerfile
Labels: cla-not-required

#320 Implement antctl table output formatter
  pkg/antctl/command_definition.go
  pkg/antctl/command_definition_test.go
Labels: cla-not-required

#351 Fix ownership of ~/.kube directory in Ansible playbook for worker
  test/e2e/infra/vagrant/playbook/roles/worker/tasks/main.yml
Labels: cla-not-required

#308 Include ovs-pipeline reference in CONTRIBUTING doc
  docs/architecture.md
Labels: cla-not-required

#360 Improve flag implementation in antctl
  pkg/antctl/command_definition.go
Labels: cla-not-required

#359 Still use flow based tunnel when IPSec encyption is enabled
  docs/ovs-pipeline.md
  pkg/agent/agent.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#327 Update API types for NamedPort NP support
  go.mod
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/podset.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/apis/networking/sets.go
  pkg/apis/networking/types.go
  pkg/apis/networking/v1beta1/generated.pb.go
  pkg/apis/networking/v1beta1/generated.proto
  pkg/apis/networking/v1beta1/sets.go
  pkg/apis/networking/v1beta1/types.go
  pkg/apis/networking/v1beta1/zz_generated.conversion.go
  pkg/apis/networking/v1beta1/zz_generated.deepcopy.go
  pkg/apis/networking/zz_generated.deepcopy.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/addressgroup_test.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
  pkg/controller/networkpolicy/store/appliedtogroup_test.go
  pkg/controller/networkpolicy/store/util.go
  pkg/controller/types/networkpolicy.go
Labels: cla-not-required

#352 Create release version of antrea-octant
  Makefile
  build/yamls/antrea-octant.yml
  build/yamls/octant/base/deployment.yml
  build/yamls/octant/base/kustomization.yml
  build/yamls/octant/base/service.yml
  build/yamls/octant/patches/dev/imagePullPolicy.yml
  build/yamls/octant/patches/release/.gitignore
  ci/check-manifest.sh
  docs/maintainers/release.md
  docs/octant-plugin-installation.md
  hack/generate-manifest-octant.sh
  hack/generate-manifest.sh
Labels: cla-not-required

#362 Add user documentation and update architecture doc for IPSec
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  docs/architecture.md
  docs/configuration.md
  docs/getting-started.md
  docs/ipsec-tunnel.md
Labels: cla-not-required

#340 support various pod traffic encapsulation mode
  .github/workflows/integration.yml
  .github/workflows/kind.yml
  Makefile
  build/images/scripts/start_ovs_netdev
  build/images/test/Dockerfile
  build/images/test/test-integration
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  docs/kind.md
  go.mod
  go.sum
  hack/generate-manifest.sh
  pkg/agent/agent.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/config/traffic_encap_mode.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/iptables/iptables.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/route/route.go
  pkg/agent/types/node_config.go
  pkg/agent/util/net_test.go
  pkg/agent/util/net_unix.go
  pkg/signals/signals.go
  test/e2e/basic_test.go
  test/e2e/connectivity_test.go
  test/e2e/framework.go
  test/integration/agent/cniserver_test.go
  test/integration/agent/iptables_test.go
  test/integration/agent/openflow_test.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#335 Use Bundle to implement Network Policy on Antrea Agent
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: cla-not-required, enhancement

#371 Add unit tests to NetworkPolicy util functions
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#384 Update names in the doc
  docs/design/cni-testing-initiative-upstream.md
Labels: cla-not-required

#385 Reorder log statement to make output friendly
  pkg/ovs/ovsconfig/ovs_client.go
Labels: cla-not-required

#376 Add AddressGroup to select everything
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#382 Fix agent caching duplicate pod member
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/apis/networking/v1beta1/sets.go
Labels: cla-not-required

#336 Split a policy rule into Openflow rules based on resolved ports
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/types/networkpolicy.go
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#390 Fix bug in NetworkPolicy implementation with OpenFlow
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: cla-not-required

#394 [Windows] Add windows branch in github UT and integration test workflow
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: cla-not-required

#388 Update cni-testing-initiative-upstream.md
  docs/design/cni-testing-initiative-upstream.md
Labels: cla-not-required

#397 Group network configuration parameters to struct NetworkConfig
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/config/node_config.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/iptables/iptables.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/route/route.go
  test/integration/agent/cniserver_test.go
  test/integration/agent/iptables_test.go
  test/integration/agent/openflow_test.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#377 Update feature list in README.md and ROADMAP.md
  README.md
  ROADMAP.md
Labels: cla-not-required

#387 Remove unnecessary periodical resync
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
Labels: cla-not-required

#392 Enable named port NetworkPolicy e2e tests in CI
  ci/jenkins/jobs/projects.yaml
Labels: cla-not-required

#395 Add openapi endpoint to antrea-controller apiserver
  cmd/antrea-controller/controller.go
  go.mod
  hack/update-codegen-dockerized.sh
  pkg/apis/networking/v1beta1/doc.go
  pkg/apiserver/openapi/zz_generated.openapi.go
Labels: cla-not-required

#398 Reduce network policy calculation log
  pkg/controller/networkpolicy/networkpolicy_controller.go
Labels: cla-not-required

#402 Update cni-testing-initiative-upstream.md
  docs/design/cni-testing-initiative-upstream.md
Labels: cla-not-required

#358 Preserve OVS datapath flows after an agent restart
  build/images/ovs/Dockerfile
  build/images/ovs/apply-patches.sh
  test/e2e/connectivity_test.go
  test/e2e/fixtures.go
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#318 Implement antctl agent-info
  pkg/antctl/antctl.go
  pkg/antctl/handlers/agentinfo.go
  pkg/antctl/handlers/agentinfo_test.go
  pkg/monitor/monitor.go
  pkg/monitor/querier.go
  pkg/monitor/testing/mock_monitor.go
Labels: cla-not-required

#396 Avoid duplicate netlink queries
  pkg/agent/agent.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/config/node_config.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/route/route.go
  pkg/agent/util/net_unix.go
  test/integration/agent/cniserver_test.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#403 Update cni-testing-initiative-upstream.md
  docs/design/cni-testing-initiative-upstream.md
Labels: cla-not-required

#389 [Windows]Connect to ovsdb-server using named pipe
  go.mod
  go.sum
  pkg/ovs/ovsconfig/default.go
  pkg/ovs/ovsconfig/default_windows.go
  pkg/ovs/ovsconfig/ovs_client.go
  test/integration/ovs/address.go
  test/integration/ovs/address_windows.go
  test/integration/ovs/ovs_client_test.go
Labels: cla-not-required

#413 Add sonobuoy wrapper script to run Antrea K8s community tests
  ci/jenkins/README.md
  ci/jenkins/jobs/projects.yaml
  ci/run-k8s-e2e-tests.sh
  ci/verify-sonobuoy.sh
Labels: area/test/infra, cla-not-required, kind/feature, priority/important-soon

#425 Remove Except IPBlock e2e test
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#412 Update cni-testing-initiative-upstream.md
  docs/design/cni-testing-initiative-upstream.md
Labels: cla-not-required

#414 Use labels.Selector in GroupSelector
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/types/networkpolicy.go
Labels: area/component/controller, cla-not-required, kind/cleanup

#415 Add template files for jenkins on cloud
  ci/cluster-api/vsphere/templates/cluster.yaml
  ci/cluster-api/vsphere/templates/controlplane.yaml
  ci/cluster-api/vsphere/templates/machinedeployment.yaml
  ci/cluster-api/vsphere/templates/namespace.yaml
  ci/jenkins/ssh-config
Labels: cla-not-required

#436 Update Go netlink from 1.0.0 to 1.1.0
  go.mod
  go.sum
Labels: cla-not-required

#441 Update CHANGELOG for v0.4.1 release
  CHANGELOG.md
Labels: cla-not-required
