Repository antrea-io/antrea, pull requests merged in 2020-11, with the labels that each got.

#1267 Implement antctl supportbundle Node name list support
  pkg/antctl/raw/supportbundle/command.go
Labels: cla-not-required

#1452 Add "antctl proxy" support
  docs/antctl.md
  docs/troubleshooting.md
  go.mod
  go.sum
  pkg/antctl/antctl.go
  pkg/antctl/command_list.go
  pkg/antctl/raw/proxy/command.go
  plugins/octant/go.sum
  test/e2e/antctl_test.go
Labels: cla-not-required

#1474 [CI] Fix TEST_FAILURE judgement
  ci/jenkins/test-vmc.sh
Labels: cla-not-required

#1428 Add conformance CI test with all alpha features enabled
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/test-vmc.sh
  hack/generate-manifest.sh
Labels: cla-not-required

#1476 Remove peer IP check in NOTRACK rules
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/route/testing/mock_route.go
  pkg/antctl/command_list.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#1461 Show stderr when failing to set "noflood" config on port
  pkg/ovs/ovsctl/ofctl.go
Labels: cla-not-required

#1478 Fix issues in E2E test for audit logging feature
  test/e2e/antreapolicy_test.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
  test/e2e/utils/networkpolicyspecbuilder.go
Labels: cla-not-required

#1469 Document Antrea API
  docs/api.md
  hack/.notableofcontents
Labels: cla-not-required

#1473 Update octant plugin installation guide
  docs/octant-plugin-installation.md
Labels: cla-not-required

#1477 Document enableLogging field to Antrea-native policy doc.
  docs/antrea-network-policy.md
Labels: cla-not-required

#1490 Fix image in README
  site/docs/master/README.md
  site/prepare-master-docs.sh
Labels: cla-not-required

#1484 Reduce storage requirements for Github actions artifacts
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
Labels: cla-not-required

#1491 Small documentation fixes
  docs/design/architecture.md
  docs/design/ovs-pipeline.md
  docs/design/policy-only.md
  docs/design/windows-design.md
  docs/kind.md
Labels: cla-not-required, kind/documentation

#1481 Respect label selector
  pkg/apiserver/registry/networkpolicy/addressgroup/rest.go
  pkg/apiserver/registry/networkpolicy/addressgroup/rest_test.go
  pkg/apiserver/registry/networkpolicy/appliedtogroup/rest.go
  pkg/apiserver/registry/networkpolicy/appliedtogroup/rest_test.go
  pkg/apiserver/registry/networkpolicy/networkpolicy/rest.go
  pkg/apiserver/registry/networkpolicy/networkpolicy/rest_test.go
  pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest.go
  pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest_test.go
  pkg/apiserver/registry/stats/antreanetworkpolicystats/rest.go
  pkg/apiserver/registry/stats/antreanetworkpolicystats/rest_test.go
  pkg/apiserver/registry/stats/networkpolicystats/rest.go
  pkg/apiserver/registry/stats/networkpolicystats/rest_test.go
  pkg/apiserver/registry/system/controllerinfo/rest.go
  pkg/apiserver/registry/system/controllerinfo/rest_test.go
Labels: cla-not-required

#1496 [IPv6] Fix issues
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/agent/flowexporter/connections/conntrack_linux_test.go
Labels: cla-not-required

#1498 [IPv6] Skip TestAntctlProxy for IPv6
  test/e2e/antctl_test.go
Labels: cla-not-required

#1495 [Windows] Set OVS services always restart on failure
  hack/windows/Install-OVS.ps1
Labels: cla-not-required

#1475 Fix golangci-lint CI and issues found by linters
  Makefile
  hack/netpol/Makefile
  pkg/agent/agent_windows.go
  pkg/agent/apiserver/handlers/ovsflows/handler_test.go
  pkg/agent/apiserver/handlers/ovstracing/handler_test.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/flowexporter/connections/conntrack_linux.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/cookie/allocator_test.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/util/iptables/iptables.go
  pkg/agent/util/iptables/lock.go
  pkg/agent/util/iptables/lock_test.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/net_windows_test.go
  pkg/agent/util/sysctl/sysctl_linux.go
  pkg/agent/util/winfirewall/winfirewall.go
  pkg/agent/util/winfirewall/winfirewall_test.go
  pkg/antctl/raw/proxy/command.go
  pkg/antctl/raw/supportbundle/command.go
  pkg/antctl/transform/addressgroup/transform.go
  pkg/antctl/transform/appliedtogroup/transform.go
  pkg/apis/controlplane/v1beta1/conversion.go
  pkg/apiserver/registry/networkpolicy/addressgroup/rest_test.go
  pkg/apiserver/registry/networkpolicy/appliedtogroup/rest_test.go
  pkg/apiserver/registry/networkpolicy/networkpolicy/rest_test.go
  pkg/graphviz/traceflow.go
  pkg/ovs/openflow/ofctrl_packetout.go
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/integration/agent/flowexporter_test.go
Labels: cla-not-required

#1466 Use DSCP instead of tun_metadata0 in Traceflow
  pkg/agent/agent.go
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/controller/traceflow/controller.go
  pkg/ovs/openflow/interfaces.go
  test/e2e/traceflow_test.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1504 Remove unused function in e2e tests
  test/e2e/fixtures.go
Labels: cla-not-required

#1501 Move community meeting to 5AM UTC
  README.md
Labels: cla-not-required

#1468 Check features not supported on Windows Nodes
  Makefile
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_linux.go
  cmd/antrea-agent/options_windows.go
  cmd/antrea-agent/options_windows_test.go
  pkg/features/antrea_features.go
Labels: cla-not-required

#1450 Add baseline Tier for Antrea-Native Policies
  pkg/agent/controller/networkpolicy/priority.go
  pkg/agent/controller/networkpolicy/priority_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/controller/networkpolicy/tier.go
  pkg/controller/networkpolicy/validate.go
  test/e2e/antreapolicy_test.go
Labels: cla-not-required

#1480 [Windows] Provide scripts/guide to prepare env needed by antrea-agent
  docs/windows.md
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Prepare-AntreaAgent.ps1
  hack/windows/Prepare-ServiceInterface.ps1
Labels: area/OS/windows, cla-not-required

#1511 Bump up ofnet to 6fd225d8c8d1
  go.mod
  go.sum
  plugins/octant/go.mod
  plugins/octant/go.sum
Labels: cla-not-required

#1497 Make iptables initialization error non fatal
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/route/testing/mock_route.go
  pkg/agent/util/iptables/iptables.go
  pkg/agent/util/iptables/lock.go
  pkg/agent/util/iptables/lock_test.go
  test/integration/agent/cniserver_test.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#1503 Delete deprecated Prometheus metrics
  docs/prometheus-integration.md
  pkg/agent/metrics/prometheus.go
  pkg/controller/metrics/prometheus.go
  test/e2e/prometheus_test.go
Labels: cla-not-required

#1505 Enable Windows unit tests on github
  .github/workflows/go.yml
  Makefile
  pkg/agent/cniserver/server_test.go
  pkg/agent/util/net_windows_test.go
Labels: cla-not-required

#1510 Fix flaky e2e test TestTraceflowIntraNode
  test/e2e/traceflow_test.go
Labels: cla-not-required

#1411 Add asyncRuleCache to idAllocator in Antrea Agent
  cmd/antrea-agent/agent.go
  go.mod
  go.sum
  pkg/agent/controller/networkpolicy/allocator.go
  pkg/agent/controller/networkpolicy/allocator_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/stats/collector.go
  pkg/agent/stats/collector_test.go
  pkg/querier/querier.go
  pkg/querier/testing/mock_querier.go
  plugins/octant/go.sum
Labels: cla-not-required

#1529 Add -race flag for Windows unit tests
  Makefile
Labels: cla-not-required

#1479 Upgrade to go-ipfix v0.2.4
  build/yamls/elk-flow-collector/logstash/ipfix.yml
  docs/network-flow-visibility.md
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  plugins/octant/go.sum
Labels: cla-not-required

#1526 Fix missing routes caused by Node events coming out of order
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
Labels: cla-not-required

#1361 Support Antrea NetworkPolicy in Traceflow
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/ovs/openflow/ofctrl_flow_test.go
  pkg/ovs/openflow/testing/mock_openflow.go
Labels: cla-not-required

#1534 Bump up portmap version to v0.8.7
  build/images/base/Dockerfile
  build/images/scripts/install_cni
  build/images/scripts/install_cni_kind
Labels: cla-not-required

#1537 Update changelog for v0.10.1 and v0.10.2 releases
  CHANGELOG.md
Labels: cla-not-required

#1483 Update documentation for Antrea-native Policies
  docs/antrea-network-policy.md
  docs/assets/ovs-pipeline.svg
  docs/design/ovs-pipeline.md
Labels: cla-not-required

#1102 [ipv6] AntreaProxy IPv6 support
  cmd/antrea-agent/agent.go
  hack/update-codegen-dockerized.sh
  pkg/agent/agent.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/connections_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/service.go
  pkg/agent/proxy/testing/mock_proxy.go
  pkg/agent/proxy/types/types.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/ofctrl_group.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/agent/openflow_test.go
  third_party/proxy/config/config.go
  third_party/proxy/meta_proxier.go
  third_party/proxy/testing/mock_proxy.go
  third_party/proxy/types.go
Labels: cla-not-required

#1268 Add network policy info to IPFIX flow records as part of Flow Exporter
  cmd/antrea-agent/agent.go
  pkg/agent/controller/networkpolicy/allocator.go
  pkg/agent/controller/networkpolicy/allocator_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/connections_test.go
  pkg/agent/flowexporter/connections/conntrack_linux.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/types.go
  pkg/agent/stats/collector.go
  test/e2e/flowexporter_test.go
  test/e2e/performance_test.go
  test/integration/agent/flowexporter_test.go
Labels: cla-not-required

#1535 Update the network flow visibility doc
  docs/network-flow-visibility.md
Labels: cla-not-required

#1513 Kibana and docs update for network policy fields in Flow Exporter
  build/yamls/elk-flow-collector/kibana.ndjson
  build/yamls/elk-flow-collector/logstash/logstash.conf
  docs/network-flow-visibility.md
Labels: cla-not-required

#1544 Skip TestPodTrafficShaping on v6 clusters
  test/e2e/bandwidth_test.go
Labels: cla-not-required

#1531 Graduate some features from Alpha to Beta
  .github/workflows/kind.yml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-windows.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/base/conf/antrea-controller.conf
  build/yamls/windows/base/conf/antrea-agent.conf
  ci/jenkins/test-vmc.sh
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  cmd/antrea-controller/config.go
  cmd/antrea-controller/options.go
  docs/feature-gates.md
  hack/generate-manifest.sh
  pkg/agent/openflow/pipeline.go
  pkg/features/antrea_features.go
  test/e2e/infra/vagrant/push_antrea.sh
  test/e2e/proxy_test.go
  test/e2e/traceflow_test.go
Labels: cla-not-required

#1548 Document lack of support for Pod traffic shaping on Photon OS 3
  docs/os-issues.md
  test/e2e/bandwidth_test.go
  test/e2e/fixtures.go
Labels: cla-not-required

#1538 [IPv6] Improve comment
  pkg/agent/controller/noderoute/node_route_controller_test.go
Labels: cla-not-required

#1533 Remove ip tools dependency for Nodes in e2e tests
  test/e2e/basic_test.go
Labels: cla-not-required

#1453 Revise SNAT flows
  docs/design/ovs-pipeline.md
  docs/design/windows-design.md
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_windows.go
  pkg/agent/config/node_config.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1547 Formatting fixes for documentation
  .github/workflows/go.yml
  CONTRIBUTING.md
  Makefile
  README.md
  ROADMAP.md
  docs/aks-installation.md
  docs/antctl.md
  docs/assets/logo/README.md
  docs/configuration.md
  docs/contributors/code-generation.md
  docs/contributors/github-labels.md
  docs/contributors/issue-management.md
  docs/contributors/manual-installation.md
  docs/cookbooks/multus/README.md
  docs/design/architecture.md
  docs/design/ovs-pipeline.md
  docs/eks-installation.md
  docs/feature-gates.md
  docs/getting-started.md
  docs/gke-installation.md
  docs/kind.md
  docs/maintainers/getting-started-gif.md
  docs/maintainers/release.md
  docs/os-issues.md
  docs/prometheus-integration.md
  docs/securing-control-plane.md
  docs/security.md
  docs/traceflow-guide.md
  docs/troubleshooting.md
  docs/versioning.md
  docs/windows.md
  hack/.md_links_config.json
  hack/make-metrics-doc.sh
  hack/verify-docs-for-website.sh
Labels: cla-not-required

#1564 Add e2e tests for validation of Antrea-native policies and Tiers
  test/e2e/antreapolicy_test.go
  test/e2e/k8s_util.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
Labels: cla-not-required

#1521 [CI] Use VMware-hosted public Harbor registry in VMC CI
  Makefile
  ci/docker-registry
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/test-vmc.sh
  ci/kind/test-e2e-kind.sh
  test/e2e/fixtures.go
  test/e2e/framework.go
  test/e2e/performance_test.go
  test/e2e/proxy_test.go
Labels: cla-not-required

#1307 Update documentation for e2e tests on kind cluster
  test/e2e/README.md
Labels: cla-not-required

#1569 Run markdownlint as part of CI
  .github/workflows/go.yml
  .markdownlint-config.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Makefile
  README.md
  ROADMAP.md
  SECURITY.md
  build/images/ipfix-collector/README.md
  build/yamls/patches/kind/README.md
  ci/README.md
  ci/golicense/README.md
  ci/jenkins/README.md
  docs/aks-installation.md
  docs/antctl.md
  docs/antrea-network-policy.md
  docs/assets/README.md
  docs/configuration.md
  docs/contributors/code-generation.md
  docs/contributors/eks-terraform.md
  docs/contributors/github-labels.md
  docs/contributors/issue-management.md
  docs/contributors/manual-installation.md
  docs/cookbooks/multus/README.md
  docs/design/architecture.md
  docs/design/ovs-pipeline.md
  docs/design/policy-only.md
  docs/design/windows-design.md
  docs/feature-gates.md
  docs/getting-started.md
  docs/ipsec-tunnel.md
  docs/kind.md
  docs/maintainers/getting-started-gif.md
  docs/maintainers/release.md
  docs/network-flow-visibility.md
  docs/octant-plugin-installation.md
  docs/ovs-offload.md
  docs/prometheus-integration.md
  docs/securing-control-plane.md
  docs/traceflow-guide.md
  docs/troubleshooting.md
  docs/versioning.md
  docs/windows.md
  hack/make-metrics-doc.sh
  hack/terraform/eks/README.md
  test/e2e/README.md
Labels: cla-not-required

#1567 Mutate empty Tier set in Antrea-native policies to default tier
  pkg/controller/networkpolicy/mutate.go
  pkg/controller/networkpolicy/tier.go
  pkg/controller/networkpolicy/validate.go
  test/e2e/antreapolicy_test.go
Labels: cla-not-required

#1575 Fix ARP flow not installed issue in networkpolicy-only mode
  pkg/agent/openflow/client.go
Labels: cla-not-required

#1522 Fix flaky unit test TestLargeScaleEndpointQueryManyPolicies
  pkg/controller/networkpolicy/endpoint_querier_test.go
Labels: cla-not-required

#1576 Fix SessionAffinity implementation in AntreaProxy
  ci/cluster-api/vsphere/templates/cluster.yaml
  ci/jenkins/test-vmc.sh
  ci/k8s-conformance-image-version
  ci/run-k8s-e2e-tests.sh
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_linux.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/proxier_windows.go
  pkg/agent/proxy/types/groupcounter.go
  pkg/agent/proxy/types/types.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1488 Refactor validate.go for Antrea-native policy and Tier validation
  pkg/controller/networkpolicy/validate.go
Labels: cla-not-required

#1584 Set OVS max revalidator delay to 200ms
  build/images/scripts/start_ovs
Labels: cla-not-required

#1436 Dec TTL on source Node only if the packet is from local Pod
  docs/assets/ovs-pipeline.svg
  docs/design/ovs-pipeline.md
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1585 Fix policyOnlyMode and cloud support for AKS & EKS
  build/yamls/antrea-eks-node-init.yml
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/config/node_config.go
  pkg/agent/openflow/client.go
  pkg/agent/querier/querier.go
  pkg/agent/querier/testing/mock_querier.go
  pkg/agent/route/route_linux.go
  pkg/support/dump_others.go
Labels: cla-not-required

#1586 Remove the pod reference in v1beta1 AddressGroup
  .github/workflows/kind_upgrade.yml
  ci/kind/test-upgrade-antrea.sh
  pkg/apis/controlplane/v1beta1/conversion.go
  pkg/apis/controlplane/v1beta1/conversion_test.go
  pkg/apis/controlplane/v1beta1/zz_generated.conversion.go
  test/e2e/networkpolicy_test.go
  test/e2e/upgrade_test.go
Labels: cla-not-required

#1563 Remove unnecessary arguments of Openflow client funcs
  pkg/agent/agent.go
  pkg/agent/agent_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  test/integration/agent/cniserver_test.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1523 Use go-ipfix collector as flow collector in e2e tests
  build/images/ipfix-collector/Dockerfile
  build/images/ipfix-collector/README.md
  test/e2e/flowexporter_test.go
  test/e2e/framework.go
Labels: cla-not-required

#1593 e2e tests to ensure mutation of empty rule name in ACNP/ANP
  test/e2e/antreapolicy_test.go
Labels: cla-not-required
