Repository antrea-io/antrea, pull requests merged in 2020-04, with the labels that each got.

#562 Let controller and agent log to host dir
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
  build/yamls/base/controller.yml
Labels: cla-not-required

#569 Add cross-compile support to `make bin`
  Makefile
Labels: cla-not-required

#556 Implement group-bucket control interface
  go.mod
  go.sum
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/ovs/openflow/ofctrl_group.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/ovs/ofctrl_test.go
  test/integration/ovs/openflow_test_utils.go
Labels: cla-not-required

#573 Fix deny-all egress NetworkPolicy case
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#566 Improve antrea-controller NetworkPolicy computation performance
  go.mod
  go.sum
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
Labels: cla-not-required

#575 Hide output when resetting changes introduced by YEAR
  hack/update-codegen-dockerized.sh
Labels: cla-not-required

#581 Update CHANGELOG for v0.5.1 release
  CHANGELOG.md
Labels: cla-not-required

#587 Updated navigation for documentation.
  site/_data/master-toc.yml
  site/_includes/nav.html
Labels: cla-not-required

#557 Enable portmap CNI with Antrea
  build/images/Dockerfile.build.ubuntu
  build/images/Dockerfile.ubuntu
  build/images/scripts/install_cni
  build/images/scripts/install_cni_kind
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
  build/yamls/base/conf/antrea-cni.conf
  build/yamls/base/conf/antrea-cni.conflist
  build/yamls/base/kustomization.yml
  docs/architecture.md
  docs/configuration.md
  test/e2e/connectivity_test.go
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#582 Improve logging for e2e tests
  test/e2e/README.md
  test/e2e/connectivity_test.go
Labels: cla-not-required

#589 Updated docs ToC, fixed kind.md issue ref
  docs/kind.md
  site/_data/master-toc.yml
  site/docs/master/kind.md
Labels: cla-not-required

#580 Handle DeletedFinalStateUnknown in NetworkPolicy Controller
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#583 Throttle on cleanup and GC jobs
  ci/jenkins/jobs/job-templates.yaml
Labels: cla-not-required

#596 Fix flakiness in TestPodConnectivityAfterAntreaRestart
  test/e2e/framework.go
Labels: cla-not-required

#595 Explicitly mention the build steps
  docs/manual-installation.md
Labels: cla-not-required

#558 Validate all controller and agent commands in antctl test
  pkg/antctl/antctl.go
  pkg/antctl/client.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_definition_test.go
  pkg/antctl/command_list.go
  pkg/antctl/command_list_test.go
  pkg/antctl/command_runtime.go
  test/e2e/antctl_test.go
Labels: cla-not-required

#594 Implement openflow learn action control interface
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/ovs/ofctrl_test.go
Labels: cla-not-required

#522 Decouple CLI code from pkg monitor
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  hack/update-codegen-dockerized.sh
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/addressgroup/handler.go
  pkg/agent/apiserver/handlers/agentinfo/handler.go
  pkg/agent/apiserver/handlers/appliedtogroup/handler.go
  pkg/agent/apiserver/handlers/networkpolicy/handler.go
  pkg/agent/apiserver/handlers/podinterface/handler.go
  pkg/agent/apiserver/handlers/podinterface/handler_test.go
  pkg/agent/querier/querier.go
  pkg/agent/querier/testing/mock_querier.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/registry/system/controllerinfo/rest.go
  pkg/controller/querier/querier.go
  pkg/controller/querier/testing/mock_querier.go
  pkg/monitor/agent.go
  pkg/monitor/controller.go
  pkg/monitor/monitor.go
  pkg/monitor/querier.go
  pkg/monitor/testing/mock_monitor.go
  pkg/querier/querier.go
Labels: cla-not-required

#572 Add enhancements in Antrea Windows
  go.mod
  go.sum
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/winfirewall/winfirewall.go
  pkg/agent/util/winfirewall/winfirewall_test.go
Labels: cla-not-required

#603 Bumped advertised release to v0.5.1
  docs/manual-installation.md
  site/docs/master/manual-installation.md
  site/index.html
Labels: cla-not-required

#599 CI: Add timeout for kubectl rollout (#584)
  ci/jenkins/jobs/macros.yaml
Labels: cla-not-required

#605 Option to disable documentation warning
  site/_includes/version-warning.html
Labels: cla-not-required

#604 Update community meeting schedule
  README.md
Labels: cla-not-required

#608 Fix prepare-assets.sh script for antrea-octant.yml
  hack/release/prepare-assets.sh
Labels: cla-not-required

#610 Corrected Kubernetes spelling on community page.
  site/community.html
Labels: cla-not-required

#606 Add windows binaries compiling job to Github action
  .github/workflows/go.yml
  Makefile
Labels: cla-not-required

#559 Bundle enhancement
  hack/update-codegen-dockerized.sh
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/ovs/openflow/ofctrl_group.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/ovs/ofctrl_test.go
  test/integration/ovs/openflow_test_utils.go
Labels: cla-not-required

#611 Fix antctl command names in troubleshooting.md
  docs/troubleshooting.md
Labels: cla-not-required

#393 [Windows] Enable Windows Pod to access external addresses
  cmd/antrea-agent/config.go
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_windows.go
  pkg/agent/config/node_config.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/cookie/allocator.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/route/route_windows.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#602 Add agent API and antctl command to dump OVS flows
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/ovsflows/handler.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/querier/querier.go
  pkg/agent/querier/testing/mock_querier.go
  pkg/antctl/antctl.go
  pkg/ovs/ofctl/ofctl.go
  pkg/ovs/openflow/ofctrl_flow.go
  test/integration/agent/openflow_test.go
  test/integration/ovs/ofctrl_test.go
  test/integration/ovs/openflow_test_utils.go
Labels: cla-not-required

#618 Fix wrong error message when positional arguments are provided
  cmd/antrea-agent/options.go
  cmd/antrea-controller/options.go
Labels: cla-not-required

#621 Use json output annotations for yaml in antctl
  pkg/agent/apiserver/handlers/ovsflows/handler.go
  pkg/agent/apiserver/handlers/podinterface/handler.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_definition_test.go
  pkg/antctl/transform/addressgroup/transform.go
  pkg/antctl/transform/appliedtogroup/transform.go
  pkg/antctl/transform/common/transform.go
  pkg/antctl/transform/rule/transform.go
  pkg/antctl/transform/version/transform.go
Labels: cla-not-required

#601 Prune unused antrea-ubuntu images
  ci/jenkins/jobs/macros.yaml
Labels: cla-not-required

#638 Free disk space in some workflows with "apt-get clean"
  .github/workflows/kind-upgrade.yml
  .github/workflows/kind.yml
Labels: area/test/infra, cla-not-required

#622 Apply authentication to agent apiserver endpoint
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/antctl.yml
  pkg/agent/apiserver/apiserver.go
Labels: cla-not-required

#643 Timeout for sonobuoy jobs
  ci/jenkins/jobs/macros.yaml
Labels: cla-not-required

#629 Compliance to k8s log format in antrea-agent pod
  go.mod
  pkg/ovs/openflow/logs.go
Labels: cla-not-required

#633 Acquire xtables.lock before executing iptables-restore
  pkg/agent/util/iptables/iptables.go
  pkg/agent/util/iptables/lock.go
  pkg/agent/util/iptables/lock_test.go
Labels: cla-not-required

#644 set -ex for bash script
  ci/jenkins/jobs/macros.yaml
Labels: cla-not-required

#640 Document known issues on Photon OS and CoreOS
  docs/getting-started.md
  docs/os-issues.md
Labels: cla-not-required, kind/documentation

#564 [Windows] Prepare ovs bridge
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/config/node_config.go
  pkg/agent/interfacestore/types.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/util/net.go
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_windows.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/integration/ovs/ovs_client_test.go
Labels: cla-not-required

#642 [Windows] Support set DNS from runtime config in CNI request
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux.go
  pkg/agent/cniserver/server_windows.go
Labels: cla-not-required

#620 Fix monitoring CRD issues
  pkg/agent/querier/querier.go
  pkg/monitor/agent.go
  pkg/monitor/controller.go
Labels: cla-not-required

#656 [Windows] Check error before clean OVS bridge and HNS network
  pkg/agent/agent_windows.go
Labels: cla-not-required

#653 Upgrade Antrea versions used for upgrade test
  .github/workflows/kind-upgrade.yml
Labels: area/test/e2e, cla-not-required

#654 Enable API Server local access with privilegedLoopbackToken
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/antctl.yml
  cmd/antrea-controller/controller.go
  pkg/agent/apiserver/apiserver.go
  pkg/antctl/client.go
  pkg/antctl/command_runtime.go
  pkg/apiserver/apiserver.go
Labels: cla-not-required

#321 Antrea Prometheus integration
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/base/conf/antrea-controller.conf
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/config.go
  cmd/antrea-controller/config.go
  cmd/antrea-controller/controller.go
  go.mod
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/metrics/prometheus.go
  pkg/controller/metrics/prometheus.go
  pkg/util/env/env.go
  pkg/util/env/env_test.go
Labels: cla-not-required

#325 Add prometheus metrics for antrea controller
  pkg/controller/metrics/prometheus.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
Labels: cla-not-required

#659 Add default CPU resource requests for Antrea Pods in manifests
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
  build/yamls/base/controller.yml
  build/yamls/patches/ipsec/ipsecContainer.yml
Labels: cla-not-required

#658 Start ovs-vswitchd with flow-restore-wait
  build/images/scripts/start_ovs
  build/images/scripts/start_ovs_netdev
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/integration/ovs/ovs_client_test.go
Labels: cla-not-required

#655 Document Prometheus configuration with Antrea
  build/yamls/antrea-prometheus.yml
  docs/prometheus-integration.md
Labels: cla-not-required

#649 Supporting dumping OVS flows of a specific table
  hack/update-codegen-dockerized.sh
  pkg/agent/apiserver/handlers/agentinfo/handler.go
  pkg/agent/apiserver/handlers/ovsflows/handler.go
  pkg/agent/apiserver/handlers/ovsflows/handler_test.go
  pkg/agent/apiserver/handlers/podinterface/handler.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/querier/querier.go
  pkg/agent/querier/testing/mock_querier.go
  pkg/antctl/antctl.go
  pkg/antctl/command_definition.go
  pkg/antctl/transform/addressgroup/transform.go
  pkg/antctl/transform/appliedtogroup/transform.go
  pkg/antctl/transform/common/transform.go
  pkg/antctl/transform/controllerinfo/transform.go
  pkg/antctl/transform/networkpolicy/transform.go
  pkg/ovs/ofctl/interface.go
  pkg/ovs/ofctl/ofctl.go
  pkg/ovs/ofctl/testing/mock_ofctl.go
  pkg/ovs/openflow/interfaces.go
  pkg/querier/testing/mock_querier.go
  test/integration/ovs/ofctrl_test.go
  test/integration/ovs/openflow_test_utils.go
Labels: cla-not-required

#669 Remove redundant ClusterRole in Prometheus deployment instructions
  build/yamls/antrea-prometheus.yml
  docs/prometheus-integration.md
Labels: cla-not-required
