Repository antrea-io/antrea, pull requests merged in 2020-12, with the labels that each got.

#1574 Improve network flow visibility doc
  docs/network-flow-visibility.md
Labels: cla-not-required

#1590 Remove leftover references to ipv6 branch in Github workflow files
  .github/workflows/go.yml
  .github/workflows/kind.yml
Labels: cla-not-required

#1603 [Website] Add ATO 2020 presentation
  site/_presentations/2020-10-20-all-things-open-2020.md
Labels: cla-not-required

#1601 [CI] Fix image in test-vmc.sh & ipfix version in Kind
  ci/jenkins/test-vmc.sh
  ci/kind/test-e2e-kind.sh
Labels: cla-not-required

#1582 Upgrade go-ipfix to v0.3.1
  go.mod
  go.sum
  hack/update-codegen-dockerized.sh
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/ipfix/ipfix_process.go
  pkg/agent/flowexporter/ipfix/ipfix_record.go
  pkg/agent/flowexporter/ipfix/ipfix_set.go
  pkg/agent/flowexporter/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
  test/e2e/flowexporter_test.go
  test/e2e/framework.go
Labels: cla-not-required

#1604 Support using arbitrary Antrea image to trigger Cloud CI
  ci/jenkins/jobs/job-templates.yaml
  ci/jenkins/jobs/projects.yaml
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
Labels: cla-not-required

#1530 Add sort-by effectivePriority for antctl get networkpolicy
  docs/antctl.md
  docs/antrea-network-policy.md
  pkg/agent/apiserver/handlers/networkpolicy/handler.go
  pkg/antctl/antctl.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_definition_test.go
  pkg/antctl/transform/addressgroup/transform.go
  pkg/antctl/transform/appliedtogroup/transform.go
  pkg/antctl/transform/controllerinfo/transform.go
  pkg/antctl/transform/networkpolicy/transform.go
  pkg/antctl/transform/utils.go
  pkg/antctl/transform/version/transform.go
  pkg/controller/networkpolicy/antreanetworkpolicy_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/tier.go
Labels: cla-not-required

#1462 [CI] Add Windows and Linux CI scripts for remote Jenkins in Antrea repo
  ci/conformance-image-config.yaml
  ci/jenkins/test.sh
  ci/run-k8s-e2e-tests.sh
Labels: cla-not-required

#1594 Change L2 forwarding flows for traffic to gateway and tunnel
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1612 Add listers and informers for antreaagentinfo and antreacontrollerinfo
  hack/update-codegen-dockerized.sh
  pkg/client/informers/externalversions/clusterinformation/interface.go
  pkg/client/informers/externalversions/clusterinformation/v1beta1/antreaagentinfo.go
  pkg/client/informers/externalversions/clusterinformation/v1beta1/antreacontrollerinfo.go
  pkg/client/informers/externalversions/clusterinformation/v1beta1/interface.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/clusterinformation/v1beta1/antreaagentinfo.go
  pkg/client/listers/clusterinformation/v1beta1/antreacontrollerinfo.go
  pkg/client/listers/clusterinformation/v1beta1/expansion_generated.go
Labels: cla-not-required

#1552 [Windows] Correct Windows pause image name shown in doc
  docs/windows.md
Labels: cla-not-required

#1507 Add hack script to generare reference docs for the Antrea API
  hack/api-reference/gen-config.json
  hack/api-reference/generate-api-reference.sh
  hack/api-reference/template/members.tpl
  hack/api-reference/template/pkg.tpl
  hack/api-reference/template/type.tpl
Labels: cla-not-required

#1366 Add script and make target to update incorrect spellings
  Makefile
  hack/update-spelling.sh
Labels: cla-not-required

#1624 Fix issues in cloud CI
  ci/jenkins/jobs/job-templates.yaml
  ci/jenkins/jobs/projects.yaml
  ci/run-k8s-e2e-tests.sh
  ci/test-conformance-eks.sh
Labels: cla-not-required

#1618 Display CII best practice badge in README
  README.md
Labels: cla-not-required

#1549 Fix the flaky test TestWorker in idAllocator
  pkg/agent/controller/networkpolicy/allocator_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  test/e2e/flowexporter_test.go
Labels: cla-not-required

#1541 [IPv6] Support flow exporter
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-windows.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/windows/base/conf/antrea-agent.conf
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_test.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/connections_test.go
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/agent/flowexporter/connections/conntrack_linux.go
  pkg/agent/flowexporter/connections/conntrack_linux_test.go
  pkg/agent/flowexporter/connections/conntrack_ovs.go
  pkg/agent/flowexporter/connections/conntrack_windows.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/flowrecords/flow_records.go
  pkg/agent/flowexporter/types.go
  test/e2e/fixtures.go
  test/e2e/flowexporter_test.go
  test/integration/agent/flowexporter_test.go
Labels: cla-not-required

#1623 Update CI doc & bug fix in CI scripts
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/test.sh
  ci/run-k8s-e2e-tests.sh
Labels: cla-not-required

#1626 Fix next table decision of l2ForwardingCalcTable
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#1640 Fix in Traceflow e2e test
  test/e2e/traceflow_test.go
Labels: cla-not-required

#1641 [Flow-aggregator]Support destination service port field in Flow Exporter
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
Labels: cla-not-required

#1619 Update OVS pipeline doc for the L2 forwarding flow changes
  docs/assets/ovs-pipeline.svg
  docs/design/ovs-pipeline.md
Labels: cla-not-required

#1615 Fix metrics flow parsing error caused by traceflow flows
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#1630 Minor code cleanup in controllers
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/status_controller.go
  pkg/controller/stats/aggregator.go
  pkg/controller/traceflow/controller.go
  pkg/monitor/controller.go
Labels: cla-not-required

#1634 Necessary change in codegen image after update to Go 1.15
  build/images/codegen/Dockerfile
  hack/update-codegen-dockerized.sh
Labels: cla-not-required

#1643 Fix flaky upgrade e2e test
  test/e2e/networkpolicy_test.go
Labels: cla-not-required

#1617 Switch to VMware Harbor registry for Antrea Docker images
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  Makefile
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-octant.yml
  build/yamls/antrea-windows.yml
  build/yamls/antrea.yml
  build/yamls/patches/coverage/startAgentCov.yml
  build/yamls/patches/coverage/startControllerCov.yml
  ci/jenkins/test-vmc.sh
  ci/jenkins/test.sh
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  ci/kind/test-upgrade-antrea.sh
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
  docs/kind.md
  hack/generate-manifest-octant.sh
  hack/generate-manifest-windows.sh
  hack/generate-manifest.sh
  hack/netpol/test-kind.sh
  hack/release/prepare-assets.sh
  test/e2e/README.md
  test/e2e/infra/vagrant/push_antrea.sh
Labels: cla-not-required

#1657 [CI] Fix Windows conformance test
  ci/jenkins/test.sh
Labels: cla-not-required

#1651 Fix CI cloud scripts
  Makefile
Labels: cla-not-required

#1650 Use VMware Harbor registry for flow-aggregator Docker image
  Makefile
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/flow-aggregator.yml
  hack/generate-manifest-flow-aggregator.sh
  hack/release/prepare-assets.sh
Labels: cla-not-required

#1602 Fix wrong TCP flags and CNP flows in Antrea Traceflow
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/openflow/client.go
  test/e2e/traceflow_test.go
Labels: cla-not-required

#1595 [Flow Exporter] Improve e2e tests
  test/e2e/fixtures.go
  test/e2e/flowexporter_test.go
Labels: cla-not-required

#1661 [CI] Fix issues
  ci/jenkins/test.sh
  test/e2e/basic_test.go
Labels: cla-not-required

#1662 Add default value of kubeconfig for antrea-octant-plugin
  docs/octant-plugin-installation.md
  plugins/octant/cmd/antrea-octant-plugin/main.go
Labels: cla-not-required

#1607 Update traceflow graph message for service destinations
  pkg/apis/ops/v1alpha1/types.go
  pkg/graphviz/traceflow.go
Labels: cla-not-required

#1655 Bump up CNI plugins version to v0.8.7
  go.mod
  go.sum
  pkg/agent/cniserver/interface_configuration_linux.go
  plugins/octant/go.sum
Labels: cla-not-required

#1660 [Windows] Fix br-int NetIPAddress not found issue
  pkg/agent/agent_windows.go
  pkg/agent/util/net_windows.go
Labels: area/OS/windows, cla-not-required

#1596 [Flow-Aggregator] The main logic implementation of the flow aggregator
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/conf/flow-aggregator.conf
  build/yamls/flow-aggregator/base/flow-aggregator.yml
  cmd/flow-aggregator/config.go
  cmd/flow-aggregator/flow-aggregator.go
  cmd/flow-aggregator/main.go
  cmd/flow-aggregator/options.go
  go.mod
  go.sum
  hack/update-codegen-dockerized.sh
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_collector.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/ipfix_process.go
  pkg/ipfix/ipfix_registry.go
  pkg/ipfix/ipfix_set.go
  pkg/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
Labels: cla-not-required

#1672 Push image of flow aggregator in feature branch
  .github/workflows/build.yml
Labels: cla-not-required

#1396 AppliedTo Per Rule for Antrea-native Policies
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta1/conversion.go
  pkg/apis/controlplane/v1beta1/generated.proto
  pkg/apis/controlplane/v1beta1/types.go
  pkg/apis/controlplane/v1beta1/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apis/security/v1alpha1/types.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/networkpolicy/antreanetworkpolicy.go
  pkg/controller/networkpolicy/antreanetworkpolicy_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/store/networkpolicy.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/types/networkpolicy.go
  test/e2e/antreapolicy_test.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
Labels: cla-not-required

#1666 [CI] Use K8s v1.19.1 in VMC Jenkins
  ci/jenkins/test-vmc.sh
Labels: cla-not-required

#1636 [Flow-Aggregator] Bump go-ipfix to v0.4.2
  ci/kind/test-e2e-kind.sh
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_collector.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/ipfix_process.go
  pkg/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
  test/e2e/framework.go
Labels: cla-not-required

#1646 [Flow-aggregator] Automation for flow aggregator deployment
  build/yamls/flow-aggregator/patches/kustomization.configMap.tpl.yml
  cmd/antrea-agent/options.go
  hack/generate-manifest-flow-aggregator.sh
  test/e2e/infra/vagrant/push_antrea.sh
Labels: cla-not-required

#1676 [Flow-Aggregator] Add template fields of stats
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
Labels: cla-not-required

#1502 [CI] Improve VMC Jenkins CI
  ci/jenkins/jobs/job-templates.yaml
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/test-vmc.sh
Labels: cla-not-required

#1667 Enhance error handling of policy reconciler
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
Labels: cla-not-required

#1682 [Flow-Aggregator] Add correlate fields and fix e2e tests with stats and network policy
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/flowaggregator/flowaggregator.go
  test/e2e/flowaggregator_test.go
Labels: cla-not-required

#1665 Update Emergency Tier's Priority to 50
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/controller-rbac.yml
  build/yamls/base/controller.yml
  docs/antrea-network-policy.md
  pkg/controller/networkpolicy/tier.go
  pkg/controller/networkpolicy/validate.go
  pkg/util/env/env.go
Labels: cla-not-required

#1683 [CI] Upgrade conformance and integration Jenkins jobs
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/test-vmc.sh
  ci/run-k8s-e2e-tests.sh
  ci/verify-sonobuoy.sh
Labels: cla-not-required

#1687 Update CHANGELOG for v0.11.1 release
  CHANGELOG.md
Labels: cla-not-required

#1686 Add note to docs regarding appliedTo per rule
  docs/antrea-network-policy.md
Labels: cla-not-required

#1671 PR to merge feature/flow-aggregator with master
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  .github/workflows/kind.yml
  .github/workflows/upload_release_assets.yml
  Makefile
  build/images/flow-aggregator/Dockerfile
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/conf/flow-aggregator.conf
  build/yamls/flow-aggregator/base/flow-aggregator.yml
  build/yamls/flow-aggregator/base/kustomization.yml
  build/yamls/flow-aggregator/patches/dev/imagePullPolicy.yml
  build/yamls/flow-aggregator/patches/kustomization.configMap.tpl.yml
  build/yamls/flow-aggregator/patches/release/.gitignore
  ci/jenkins/test-vmc.sh
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_test.go
  cmd/flow-aggregator/config.go
  cmd/flow-aggregator/flow-aggregator.go
  cmd/flow-aggregator/main.go
  cmd/flow-aggregator/options.go
  go.mod
  go.sum
  hack/generate-manifest-flow-aggregator.sh
  hack/release/prepare-assets.sh
  hack/update-codegen-dockerized.sh
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_collector.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/ipfix_process.go
  pkg/ipfix/ipfix_registry.go
  pkg/ipfix/ipfix_set.go
  pkg/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/flowexporter_test.go
  test/e2e/framework.go
  test/e2e/infra/vagrant/push_antrea.sh
  test/integration/agent/flowexporter_test.go
Labels: cla-not-required

#1677 Update network flow visibility document
  docs/assets/flow_exporter.svg
  docs/assets/flow_visibility.svg
  docs/network-flow-visibility.md
Labels: cla-not-required

#1698 Fix a couple of markdown links for the antrea.io website
  docs/kind.md
  docs/traceflow-guide.md
  docs/troubleshooting.md
Labels: kind/documentation

#1700 Remove known issue note from NetworkPolicy doc
  docs/antrea-network-policy.md
Labels: cla-not-required

#1701 Use default K8s version supported by AKS for cloud CI
  ci/jenkins/README.md
  ci/test-conformance-aks.sh
Labels: cla-not-required
