Repository antrea-io/antrea, pull requests merged in 2021-07, with the labels that each got.

#2240 Add Pod labels infomation in flow records
  build/yamls/elk-flow-collector/logstash/ipfix.yml
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/testing/mock_ipfix.go
  test/e2e/flowaggregator_test.go
Labels: area/flow-visibility, area/flow-visibility/aggregator

#2335 [Website] Add Linux Foundation footer to website
  site/_includes/footer.html
  site/_scss/site/objects/_footer.scss
  site/img/cncf-color-logo.svg
Labels: cncf/sandbox

#2129 Add performance unit test for Flow Exporter
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go
  pkg/agent/flowexporter/connections/deny_connections.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_perf_test.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/flowrecords/flow_records.go
Labels: area/flow-visibility, area/flow-visibility/exporter, cla-not-required

#2328 Automated cherry pick of #2306: [Windows]Check HostNamespace value when removing HcnEndpoint
  pkg/agent/cniserver/interface_configuration_windows.go
Labels: kind/cherry-pick

#2327 Automated cherry pick of #2306: [Windows]Check HostNamespace value when removing HcnEndpoint
  pkg/agent/cniserver/interface_configuration_windows.go
Labels: kind/cherry-pick

#2325 Automated cherry pick of #2318: Fix cross-Node service access when AntreaProxy is disabled
  docs/design/ovs-pipeline.md
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  test/e2e/service_test.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#2324 Automated cherry pick of #2318: Fix cross-Node service access when AntreaProxy is disabled
  docs/design/ovs-pipeline.md
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  test/e2e/service_test.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#2347 Automated cherry pick of #2332: Fix intra-Node service access when both Egress and
  docs/design/windows-design.md
  pkg/agent/openflow/pipeline.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#2348 Automated cherry pick of #2332: Fix intra-Node service access when both Egress and
  docs/design/windows-design.md
  pkg/agent/openflow/pipeline.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#2308 Fix flakiness in Kind e2e flow aggregator tests
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
  pkg/agent/flowexporter/exporter/exporter.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: area/flow-visibility, area/test/e2e

#2361 [Flow Aggregator] Remove originalExporterAddress and originalObservationDomainId
  ci/kind/test-e2e-kind.sh
  go.mod
  go.sum
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
  test/e2e/framework.go
Labels: area/flow-visibility, area/flow-visibility/aggregator

#2382 Change default port range for NodePortLocal
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/options.go
  docs/feature-gates.md
  pkg/agent/nodeportlocal/k8s/annotations_test.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  test/e2e/nodeportlocal_test.go
Labels: area/proxy/nodeportlocal

#2385 NodePortLocal: make sure port is available and bind to it to reserve it
  hack/update-codegen-dockerized.sh
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/npl_agent_init.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/doc.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/portcache/testing/mock_portcache.go
  pkg/agent/nodeportlocal/portcache/types.go
  pkg/agent/nodeportlocal/rules/iptable_rule.go
  test/e2e/nodeportlocal_test.go
Labels: area/proxy/nodeportlocal

#2401 Document update for removed elements in Flow Exporter
  docs/network-flow-visibility.md
Labels: area/flow-visibility

#2417 Automated cherry pick of #2408: Improve e2e tests on kind clusters
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  .github/workflows/netpol_cyclonus.yml
  test/e2e/fixtures.go
  test/e2e/framework.go
Labels: kind/cherry-pick

#2418 Automated cherry pick of #2408: Improve e2e tests on kind clusters
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  .github/workflows/netpol_cyclonus.yml
  test/e2e/fixtures.go
  test/e2e/framework.go
Labels: kind/cherry-pick

#2375 Automated cherry pick of #2363: RunCommand with os/exec * Use "os/exec" to run
  go.mod
  go.sum
  pkg/agent/agent_windows.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/powershell/powershell_windows.go
  pkg/agent/util/winfirewall/winfirewall.go
  plugins/octant/go.sum
  test/integration/agent/net_windows_test.go
Labels: kind/cherry-pick

#2373 Automated cherry pick of #2363: RunCommand with os/exec * Use "os/exec" to run
  go.mod
  go.sum
  pkg/agent/agent_windows.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/powershell/powershell_windows.go
  pkg/agent/util/winfirewall/winfirewall.go
  plugins/octant/go.sum
  test/integration/agent/net_test_windows.go
Labels: kind/cherry-pick

#2387 Support TCP transport for elk flow collector
  build/yamls/elk-flow-collector/elk-flow-collector.yml
  build/yamls/elk-flow-collector/logstash/logstash.conf
  docs/network-flow-visibility.md
Labels: area/flow-visibility, area/flow-visibility/elk

#2410 Fix typos in process-changelog release helper script
  hack/release/process-changelog.go
Labels: area/build-release

#2429 Fix the deadlock between the exporter and the conntrack polling go routines
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_perf_test.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/flowrecords/flow_records.go
  pkg/agent/flowexporter/types.go
Labels: area/flow-visibility/exporter

#2374 Automated cherry pick of #2363: RunCommand with os/exec * Use "os/exec" to run
  go.mod
  go.sum
  pkg/agent/agent_windows.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/powershell/powershell_windows.go
  pkg/agent/util/winfirewall/winfirewall.go
  plugins/octant/go.sum
  test/integration/agent/net_windows_test.go
Labels: kind/cherry-pick

#2432 [Flow Aggregator] Fix throughput calculation in Logstash
  build/yamls/elk-flow-collector/logstash/filter.rb
  pkg/agent/flowexporter/connections/conntrack_connections.go
Labels: area/flow-visibility/elk, area/flow-visibility/exporter

#2447 Automated cherry pick of #2432: Fix throughput calculation in Logstash
  build/yamls/elk-flow-collector/logstash/filter.rb
  pkg/agent/flowexporter/connections/conntrack_connections.go
Labels: kind/cherry-pick

#2446 Automated cherry pick of #2429: Fix the deadlock between exporter and conntrack polling goroutines
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_perf_test.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/flowrecords/flow_records.go
  pkg/agent/flowexporter/types.go
Labels: kind/cherry-pick

#2397 Automated cherry pick of #2383: Fix ACNP incorrectly process rules with no from/to in
  docs/antrea-network-policy.md
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  test/e2e/antreapolicy_test.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
Labels: kind/cherry-pick

#2404 Automated cherry pick of #2376: Fix deadlock in initializing GroupEntityIndex with many
  cmd/antrea-controller/controller.go
  pkg/controller/egress/controller_test.go
  pkg/controller/grouping/controller.go
  pkg/controller/grouping/controller_test.go
  pkg/controller/grouping/group_entity_index.go
  pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
Labels: kind/cherry-pick

#2405 Automated cherry pick of #2376: Fix deadlock in initializing GroupEntityIndex with many
  cmd/antrea-controller/controller.go
  pkg/controller/egress/controller_test.go
  pkg/controller/grouping/controller.go
  pkg/controller/grouping/controller_test.go
  pkg/controller/grouping/group_entity_index.go
  pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
Labels: kind/cherry-pick

#2425 Explicitly use testNamespace in creating Pods for e2e tests
  test/e2e/antreapolicy_test.go
  test/e2e/bandwidth_test.go
  test/e2e/basic_test.go
  test/e2e/batch_test.go
  test/e2e/connectivity_test.go
  test/e2e/egress_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/legacyantreapolicy_test.go
  test/e2e/networkpolicy_test.go
  test/e2e/nodeportlocal_test.go
  test/e2e/proxy_test.go
  test/e2e/service_test.go
  test/e2e/traceflow_test.go
  test/e2e/upgrade_test.go
Labels: area/test/e2e

#2462 Automated cherry pick of #2451: Update OVS version from 2.14.0 to 2.14.2
  .github/workflows/update_ovs_image.yml
  build/images/Dockerfile.build.coverage
  build/images/Dockerfile.build.ubuntu
  build/images/Dockerfile.ubuntu
  build/images/base/Dockerfile
  build/images/flow-aggregator/Dockerfile
  build/images/ovs/Dockerfile
  build/images/ovs/README.md
  build/images/ovs/apply-patches.sh
  build/images/test/Dockerfile
  ci/jenkins/test-vmc.sh
  ci/jenkins/test.sh
  docs/troubleshooting.md
Labels: kind/cherry-pick

#2475 Automated cherry pick of #2452: Update some Go module dependencies #2464: Fix invalid client-go version
  go.mod
  go.sum
  plugins/octant/go.sum
Labels: kind/cherry-pick

#2482 Update API versioning documentation
  docs/api.md
  docs/versioning.md
Labels: kind/documentation

#2480 Automated cherry pick of #2386: Return an empty list when NetworkPolicyStats is disabled
  pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest.go
  pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest_test.go
  pkg/apiserver/registry/stats/antreanetworkpolicystats/rest.go
  pkg/apiserver/registry/stats/antreanetworkpolicystats/rest_test.go
  pkg/apiserver/registry/stats/networkpolicystats/rest.go
  pkg/apiserver/registry/stats/networkpolicystats/rest_test.go
Labels: kind/cherry-pick

#2481 Update sample ClusterGroup specs to v1alpha3
  docs/antrea-network-policy.md
Labels: kind/documentation

#2459 Automated cherry pick of #2451: Update OVS version from 2.14.0 to 2.14.2
  build/images/deps/ovs-version
  build/images/ovs/apply-patches.sh
  docs/troubleshooting.md
Labels: kind/cherry-pick

#2460 Automated cherry pick of #2451: Update OVS version from 2.14.0 to 2.14.2
  build/images/deps/ovs-version
  build/images/ovs/apply-patches.sh
  docs/troubleshooting.md
Labels: kind/cherry-pick

#2461 Automated cherry pick of #2451: Update OVS version from 2.14.0 to 2.14.2
  build/images/deps/ovs-version
  build/images/ovs/apply-patches.sh
  docs/troubleshooting.md
Labels: kind/cherry-pick

#2487 Fix test-upgrade-antrea.sh script so it can be used in release branches
  ci/kind/test-upgrade-antrea.sh
Labels: area/test/infra

#2502 Automated cherry pick of #2467: Use GroupMemberSet.Merge to reduce CPU usage and memory
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/apis/controlplane/sets.go
  pkg/apis/controlplane/v1beta1/sets.go
  pkg/apis/controlplane/v1beta2/sets.go
  pkg/controller/egress/store/egressgroup.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
Labels: kind/cherry-pick

#2501 Automated cherry pick of #2458: Use ChainExists to reduce memory footprint
  go.mod
  go.sum
  pkg/agent/util/iptables/iptables.go
  plugins/octant/go.sum
Labels: kind/cherry-pick

#2503 Automated cherry pick of #2479: Improve NetworkPolicy batch installation
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/util/ip/ip.go
Labels: kind/cherry-pick

#2509 Automated cherry pick of #2487: Fix test-upgrade-antrea.sh script so it can be used in
  ci/kind/test-upgrade-antrea.sh
Labels: kind/cherry-pick

#2510 Automated cherry pick of #2487: Fix test-upgrade-antrea.sh script so it can be used in
  ci/kind/test-upgrade-antrea.sh
Labels: kind/cherry-pick

#2511 Automated cherry pick of #2487: Fix test-upgrade-antrea.sh script so it can be used in
  ci/kind/test-upgrade-antrea.sh
Labels: kind/cherry-pick

#2512 Automated cherry pick of #2487: Fix test-upgrade-antrea.sh script so it can be used in
  ci/kind/test-upgrade-antrea.sh
Labels: kind/cherry-pick
