Repository antrea-io/antrea, pull requests merged in 2021-01, with the labels that each got.

#1699 Add validation e2e tests for endPort
  test/e2e/antreapolicy_test.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
Labels: cla-not-required

#1711 Avoid concurrent Git processes when running 'make codegen'
  hack/update-codegen-dockerized.sh
Labels: cla-not-required

#1708 Support retrieving flows of multi-tables of ovsflows command
  docs/antctl.md
  pkg/agent/apiserver/handlers/ovsflows/handler.go
  pkg/antctl/antctl.go
Labels: cla-not-required

#1702 Use more inclusive terminology in project
  ci/clair-scan/run.sh
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/ssh-config
  ci/jenkins/test-vmc.sh
  ci/jenkins/test.sh
  ci/test-conformance-gke.sh
  docs/assets/antrea_overview.svg
  docs/assets/antrea_overview.svg.png
  docs/assets/ovs-pipeline.svg
  docs/cookbooks/multus/test/Vagrantfile
  docs/design/ovs-pipeline.md
  docs/windows.md
  go.mod
  go.sum
  hack/netpol/README.md
  hack/netpol/pkg/main/main.go
  hack/netpol/pkg/utils/reachability.go
  hack/windows/Prepare-ServiceInterface.ps1
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/proxy/proxier.go
  pkg/antctl/command_definition_test.go
  pkg/controller/traceflow/controller.go
  pkg/ovs/openflow/ofctrl_bridge.go
  plugins/octant/go.sum
  test/e2e/README.md
  test/e2e/antctl_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/bandwidth_test.go
  test/e2e/basic_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/infra/vagrant/Vagrantfile
  test/e2e/infra/vagrant/playbook/k8s.yml
  test/e2e/infra/vagrant/playbook/roles/control-plane/meta/main.yml
  test/e2e/infra/vagrant/playbook/roles/control-plane/tasks/main.yml
  test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2
  test/e2e/infra/vagrant/push_antrea.sh
  test/e2e/k8s_util.go
  test/e2e/main_test.go
  test/e2e/performance_test.go
  test/e2e/providers/kind.go
  test/e2e/reachability.go
  test/e2e/supportbundle_test.go
  test/e2e/upgrade_test.go
  third_party/proxy/service.go
Labels: cla-not-required

#1717 Document our commitment to using inclusive naming in Antrea
  CONTRIBUTING.md
Labels: cla-not-required

#1696 Skip AntreaProxy LB for established connections without ServiceMark
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#1705 Fix: CI should use Harbor registry in matrix job
  ci/jenkins/jobs/macros.yaml
Labels: cla-not-required

#1721 Fix enablement check of feature FlowExporter
  cmd/antrea-agent/options.go
Labels: cla-not-required

#1723 Fix flaky test TestControllerWithDuplicatePodCIDR
  pkg/agent/controller/noderoute/node_route_controller_test.go
Labels: cla-not-required

#1713 Bug fix in AntreaProxy IPv6 and modification of related e2e tests
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_flow.go
  test/e2e/bandwidth_test.go
  test/e2e/basic_test.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/ipsec_test.go
  test/e2e/k8s_util.go
  test/e2e/networkpolicy_test.go
  test/e2e/proxy_test.go
  test/e2e/traceflow_test.go
Labels: cla-not-required

#1724 Address lgtm.com alerts based on CodeQL analysis
  pkg/agent/apiserver/handlers/ovstracing/handler.go
  pkg/agent/apiserver/handlers/ovstracing/handler_test.go
  pkg/agent/flowexporter/connections/conntrack_ovs.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/ofctrl_action.go
Labels: cla-not-required

#1718 Consolidate config validation function of flow aggregator
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_test.go
  cmd/flow-aggregator/config.go
  cmd/flow-aggregator/flow-aggregator.go
  cmd/flow-aggregator/options.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/util/flowexport/flowexport.go
  pkg/util/flowexport/flowexport_test.go
Labels: cla-not-required

#1726 Cleanup Agent integration tests
  go.mod
  test/integration/agent/route_test.go
Labels: cla-not-required, kind/cleanup

#1704 Add metrics of Antrea Proxy
  docs/prometheus-integration.md
  pkg/agent/proxy/metrics/metrics.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
Labels: area/monitoring/metrics, cla-not-required

#1459 Introducing NodePortLocal in Antrea Agent
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  hack/update-codegen-dockerized.sh
  pkg/agent/nodeportlocal/k8s/annotations.go
  pkg/agent/nodeportlocal/k8s/controller.go
  pkg/agent/nodeportlocal/npl_agent_init.go
  pkg/agent/nodeportlocal/npl_agent_init_windows.go
  pkg/agent/nodeportlocal/nplagent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/rules/iptable_rule.go
  pkg/agent/nodeportlocal/rules/rules.go
  pkg/agent/nodeportlocal/rules/testing/mock_rules.go
  pkg/agent/nodeportlocal/util/parse_port.go
  pkg/agent/util/iptables/iptables.go
  pkg/features/antrea_features.go
Labels: cla-not-required

#1597 Revise OVS pipeline: use macRewriteMark as the only mark to reset dst MAC
  pkg/agent/openflow/pipeline.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1730 Check the flow-restore-wait config and retry deleting it
  pkg/agent/agent.go
Labels: cla-not-required

#1741 [Windows] Update the way to check the state of required Windows feature
  pkg/agent/util/net_windows.go
  pkg/agent/util/net_windows_test.go
Labels: cla-not-required

#1746 Fix cookie ID of decTTL flows
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#1639 Add ClusterGroup API types
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/controller-rbac.yml
  build/yamls/base/controller.yml
  build/yamls/base/crds-rbac.yml
  build/yamls/base/crds.yml
  cmd/antrea-controller/controller.go
  pkg/apis/controlplane/register.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/register.go
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha2/register.go
  pkg/apis/core/v1alpha2/types.go
  pkg/apis/core/v1alpha2/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/apiserver/registry/networkpolicy/group/rest.go
  pkg/apiserver/registry/networkpolicy/group/rest_test.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_group.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/generated_expansion.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/group.go
  pkg/client/clientset/versioned/typed/core/v1alpha2/clustergroup.go
  pkg/client/clientset/versioned/typed/core/v1alpha2/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha2/fake/fake_clustergroup.go
  pkg/client/clientset/versioned/typed/core/v1alpha2/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha2/generated_expansion.go
  pkg/client/informers/externalversions/core/v1alpha2/clustergroup.go
  pkg/client/informers/externalversions/core/v1alpha2/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1alpha2/clustergroup.go
  pkg/client/listers/core/v1alpha2/expansion_generated.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/group.go
  pkg/controller/networkpolicy/store/group_test.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/types/group.go
  pkg/controller/types/networkpolicy.go
Labels: cla-not-required

#1748 Conditionally pull base image for "make ubuntu" target
  Makefile
Labels: cla-not-required

#1579 [IPv6] Traceflow IPv6 support
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  go.mod
  go.sum
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/interfacestore/types.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/apis/ops/v1alpha1/types.go
  pkg/apis/ops/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/traceflow/controller.go
  pkg/controller/traceflow/controller_test.go
  pkg/ovs/openflow/ofctrl_packetout.go
  pkg/ovs/openflow/ofctrl_packetout_test.go
  plugins/octant/go.sum
Labels: cla-not-required

#1736 [Windows] Check interface operation results before return
  pkg/agent/agent_windows.go
  pkg/agent/util/net_windows.go
Labels: cla-not-required

#1744 [Windows] Provide workaround to install Hyper-V without CPU check
  docs/windows.md
Labels: cla-not-required

#1756 [Windows] Fix restart OVS service issue
  ci/jenkins/test.sh
Labels: cla-not-required

#1755 [Refactor] Common flow tables in pipeline
  pkg/agent/openflow/pipeline.go
Labels: cla-not-required

#1754 Use macRewriteMark to indicate MAC rewrite in L3Fwd flow for gw0
  docs/design/ovs-pipeline.md
  pkg/agent/openflow/pipeline.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1762 Update Github workflows ahead of default branch renaming
  .github/workflows/build.yml
  .github/workflows/go.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
Labels: cla-not-required

#1757 Update the getting started doc about the requirements of Linux Kernel
  docs/getting-started.md
Labels: cla-not-required

#1769 Use Ubuntu 20.04 more consistently instead of Ubuntu 18.04
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  .github/workflows/clair.yml
  .github/workflows/go.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  .github/workflows/update_ovs_image.yml
  .github/workflows/upload_release_assets.yml
  build/images/Dockerfile.octant.ubuntu
  build/images/codegen/Dockerfile
  build/images/ethtool/Dockerfile
  build/images/perftool/Dockerfile
  test/e2e/infra/vagrant/Vagrantfile
Labels: cla-not-required

#1749 Update metric definitions to meet the convention
  pkg/agent/metrics/prometheus.go
  pkg/agent/proxy/metrics/metrics.go
  pkg/controller/metrics/prometheus.go
Labels: cla-not-required

#1767 Normalize non standard CIDRs to fix OVS error
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
Labels: cla-not-required

#1777 Stop mounting the host's kmod to the Antrea initContainer
  build/images/scripts/install_cni
  build/images/scripts/install_cni_chaining
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
Labels: cla-not-required

#1763 Rename "master" to "main" branch for Jenkins jobs
  ci/jenkins/jobs/job-templates.yaml
  ci/jenkins/jobs/projects.yaml
Labels: cla-not-required

#1783 Remove all remaining references to the Antrea "master" branch
  .github/workflows/build.yml
  .github/workflows/go.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  ci/gh-actions/has-changes/README.md
  ci/jenkins/mellanox/README.md
  docs/aks-installation.md
  docs/cookbooks/multus/README.md
  docs/eks-installation.md
  docs/getting-started.md
  docs/gke-installation.md
  docs/ipsec-tunnel.md
  docs/network-flow-visibility.md
  docs/versioning.md
  docs/windows.md
  hack/netpol/Makefile
  hack/netpol/README.md
Labels: cla-not-required

#1792 Add link to calendar in community page
  site/community.html
  site/img/calendar_new.png
Labels: cla-not-required

#1793 Use NamespacedName KeyFunc for ClusterGroups
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/group.go
Labels: cla-not-required

#1796 Remove dependency on juju packages
  go.mod
  go.sum
  pkg/agent/util/net_windows.go
  plugins/octant/go.sum
Labels: cla-not-required

#1647 E2E improvements and fixes for Antrea-native Policy
  test/e2e/antreapolicy_test.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
  test/e2e/utils/networkpolicyspecbuilder.go
Labels: cla-not-required

#1778 Add Status subresource to ClusterGroup CRD
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/controller-rbac.yml
  build/yamls/base/crds.yml
  pkg/apis/core/v1alpha2/types.go
  pkg/apis/core/v1alpha2/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/core/v1alpha2/clustergroup.go
  pkg/client/clientset/versioned/typed/core/v1alpha2/fake/fake_clustergroup.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: cla-not-required

#1798 Add documentation for noEncap and hybrid modes, and kube-router
  docs/getting-started.md
  docs/noencap-hybrid-modes.md
  hack/.notableofcontents
Labels: cla-not-required
