Repository antrea-io/antrea, pull requests merged in 2021-10, with the labels that each got.

#2807 Upgrade go-ipfix to v0.5.8
  ci/kind/test-e2e-kind.sh
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_perf_test.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  plugins/octant/go.sum
  test/e2e/framework.go
Labels: area/flow-visibility

#2859 [Doc] Some docs/comments changes and refactoring
  docs/design/architecture.md
  docs/design/ovs-pipeline.md
  docs/design/windows-design.md
  pkg/agent/agent_windows.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/controller/egress/ipassigner/ip_assigner_linux.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_windows.go
  pkg/agent/proxy/proxier.go
  pkg/agent/route/route_windows.go
  pkg/agent/util/net.go
  pkg/agent/util/net_windows.go
  test/e2e/service_test.go
  test/integration/agent/cniserver_test.go
  test/integration/agent/net_windows_test.go
  test/integration/agent/openflow_test.go
  test/integration/agent/route_test.go
  test/integration/ovs/openflow_test_utils.go
Labels: kind/documentation

#2929 Document encap mode installation for EKS
  docs/design/policy-only.md
  docs/eks-installation.md
  docs/getting-started.md
Labels: area/provider/aws, kind/documentation

#2876 Improve Conntrack Connection unit test
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
Labels: area/flow-visibility/exporter, review-manager-test

#2939 [Windows][AntreaProxy] Fix route reconcile()
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/route/route_windows.go
Labels: kind/bug, area/proxy
