Repository antrea-io/antrea, pull requests merged in 2021-05, with the labels that each got.

#2102 Decode flowType in Kibana dashboard
  build/yamls/elk-flow-collector/kibana.ndjson
  build/yamls/elk-flow-collector/logstash/filter.rb
  docs/network-flow-visibility.md
Labels: cla-not-required

#2148 Update CHANGELOG
  CHANGELOG/CHANGELOG-0.x.md
  CHANGELOG/CHANGELOG-1.0.md
Labels: cla-not-required

#2153 [Website] Add antrea CNCF sandbox donation blog post
  CHANGELOG/CHANGELOG-0.x.md
  CHANGELOG/CHANGELOG-1.0.md
  site/_posts/2021-05-05-antrea-joins-cncf-sandbox.md
  site/img/cncf-sandbox-horizontal-color.svg
Labels: cla-not-required

#2125 Improve Antrea-native Policy CRD schema verification
  .gitignore
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  test/e2e/antreapolicy_test.go
Labels: cla-not-required

#2131 Readme: Make meeting time clearer, invite to check calendar
  README.md
Labels: cla-not-required

#2149 Improve conformance test scripts
  ci/run-k8s-e2e-tests.sh
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
Labels: area/test/infra, cla-not-required

#2156 Updating Adopters.md
  ADOPTERS.md
Labels: cla-not-required

#2136 Add script for semi-automatic bug fix backporting
  CONTRIBUTING.md
  docs/contributors/cherry-picks.md
  docs/contributors/github-labels.md
  hack/.notableofcontents
  hack/cherry-pick-pull.sh
  hack/update-toc.sh
  hack/verify-toc.sh
Labels: cla-not-required

#2158 [Website] Update main docs and add blog post
  .gitignore
  ADOPTERS.md
  CONTRIBUTING.md
  README.md
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  ci/run-k8s-e2e-tests.sh
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
  docs/contributors/cherry-picks.md
  docs/contributors/github-labels.md
  docs/getting-started.md
  docs/network-requirements.md
  hack/.notableofcontents
  hack/cherry-pick-pull.sh
  hack/update-toc.sh
  hack/verify-toc.sh
  site/_posts/2021-05-07-antrea-cluster-network-policy-howto.md
  site/docs/main/ADOPTERS.md
  site/docs/main/CONTRIBUTING.md
  site/docs/main/README.md
  site/docs/main/contributors/cherry-picks.md
  site/docs/main/contributors/github-labels.md
  site/docs/main/getting-started.md
  site/docs/main/network-requirements.md
  site/prepare-tot-docs.sh
  test/e2e/antreapolicy_test.go
Labels: cla-not-required

#2159 Correct Community meeting recording link
  README.md
Labels: cla-not-required

#2155 Fix cleanup for the TestClusterGroup e2e test
  test/e2e/clustergroup_test.go
  test/e2e/k8s_util.go
  test/e2e/legacyclustergroup_test.go
Labels: area/test/e2e, area/test/infra, cla-not-required

#2165 [Website] Set up vanity import path for Antrea
  site/_config.yml
  site/_redirects
  site/golang/antrea.html
Labels: cla-not-required

#2018 [CI][Windows] Support connectivity tests & enable e2e Jenkins jobs in Windows
  ci/jenkins/README.md
  ci/jenkins/test.sh
  test/e2e/antctl_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/bandwidth_test.go
  test/e2e/basic_test.go
  test/e2e/batch_test.go
  test/e2e/clustergroup_test.go
  test/e2e/connectivity_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/ipsec_test.go
  test/e2e/legacyantreapolicy_test.go
  test/e2e/legacyclustergroup_test.go
  test/e2e/networkpolicy_test.go
  test/e2e/nodeportlocal_test.go
  test/e2e/prometheus_test.go
  test/e2e/proxy_test.go
  test/e2e/security_test.go
  test/e2e/supportbundle_test.go
  test/e2e/tls_test.go
  test/e2e/traceflow_test.go
  test/e2e/upgrade_test.go
Labels: cla-not-required

#2170 Handle Antrea repository change in Github workflows
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  .github/workflows/clair.yml
  .github/workflows/lifecycle_management.yml
Labels: cla-not-required

#2124 add livetraffic support in octant plugin
  pkg/graphviz/traceflow.go
  plugins/octant/cmd/antrea-octant-plugin/main.go
  plugins/octant/cmd/antrea-octant-plugin/traceflow.go
Labels: cla-not-required

#2181 Add FOSSA license scan report and status
  README.md
  hack/.md_links_config.json
Labels: cncf/sandbox

#2184 [CI] Exit immediately if building images fails
  ci/jenkins/test-vmc.sh
Labels: area/test/infra

#2183 [CI] Support pulling images from Dockerhub
  ci/jenkins/test-vmc.sh
Labels: area/test/infra

#1949 Change flow export mechanism for Flow Aggregator
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/conf/flow-aggregator.conf
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  cmd/flow-aggregator/config.go
  cmd/flow-aggregator/flow-aggregator.go
  cmd/flow-aggregator/options.go
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: cla-not-required

#2147 Add ipfix-collector deployment instructions to flow-visibility doc
  docs/network-flow-visibility.md
Labels: cla-not-required, kind/documentation

#2189 Build antrea-cni binary and release binaries without cgo
  Makefile
  hack/release/prepare-assets.sh
Labels: area/build-release

#2161 Update Node's MAC address to the Node's annotation for direct routing
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/types/annotations.go
  pkg/agent/util/net_windows.go
  pkg/util/env/env.go
  pkg/util/env/env_test.go
Labels: cla-not-required

#2138 Windows support for Flow Exporter with Flow Aggregator
  build/yamls/antrea-windows.yml
  build/yamls/windows/base/conf/antrea-agent.conf
  docs/network-flow-visibility.md
  pkg/agent/flowexporter/connections/conntrack_windows.go
  pkg/flowaggregator/certificate.go
Labels: cla-not-required

#2191 Move GetNodeAddr function to k8s util package
  cmd/antrea-agent-simulator/simulator.go
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  pkg/agent/agent.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/interfacestore/interface_cache.go
  pkg/antctl/raw/proxy/command.go
  pkg/antctl/raw/supportbundle/command.go
  pkg/apiserver/registry/networkpolicy/groupassociation/rest_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/store/group.go
  pkg/controller/stats/aggregator.go
  pkg/util/k8s/client.go
  pkg/util/k8s/doc.go
  pkg/util/k8s/name.go
  pkg/util/k8s/node.go
  pkg/util/k8s/node_test.go
Labels: kind/cleanup

#1961 Add 'namespaces' in ACNP for enhanced peer namespace selection
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  cmd/antrea-controller/controller.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/networkpolicy.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/types/networkpolicy.go
  test/e2e/antreapolicy_test.go
  test/e2e/legacyantreapolicy_test.go
  test/e2e/reachability.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
  test/e2e/utils/networkpolicyspecbuilder.go
Labels: cla-not-required, kind/feature

#2167 Fix Traceflow issue on hairpin service
  pkg/agent/openflow/pipeline.go
  test/e2e/traceflow_test.go
Labels: cla-not-required

#2112 Add deny connection tracking for Flow Exporter
  build/yamls/elk-flow-collector/logstash/filter.rb
  build/yamls/elk-flow-collector/logstash/ipfix.yml
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/flow-aggregator.yml
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/agent.go
  cmd/flow-aggregator/flow-aggregator.go
  docs/network-flow-visibility.md
  docs/prometheus-integration.md
  hack/update-codegen-dockerized.sh
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/connections_test.go
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
  pkg/agent/flowexporter/connections/conntrack_linux.go
  pkg/agent/flowexporter/connections/conntrack_linux_test.go
  pkg/agent/flowexporter/connections/conntrack_ovs.go
  pkg/agent/flowexporter/connections/deny_connections.go
  pkg/agent/flowexporter/connections/deny_connections_test.go
  pkg/agent/flowexporter/connections/testing/mock_connections.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/flowrecords/flow_records.go
  pkg/agent/flowexporter/types.go
  pkg/agent/flowexporter/utils.go
  pkg/agent/metrics/prometheus.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/testing/mock_ipfix.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/integration/agent/flowexporter_test.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#2160 [Windows] NoEncap support
  build/yamls/antrea-windows.yml
  build/yamls/windows/base/conf/antrea-agent.conf
  cmd/antrea-agent/options_windows.go
  cmd/antrea-agent/options_windows_test.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_other.go
  pkg/agent/openflow/pipeline_windows.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1802 Fortify the bandwidth e2e test of flow aggregator
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: cla-not-required

#2039 Fix bug in FlowAggregator when sending template set
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  test/e2e/flowaggregator_test.go
Labels: cla-not-required

#2163 Add network policy related metadata to flow records
  build/yamls/elk-flow-collector/logstash/filter.rb
  build/yamls/elk-flow-collector/logstash/ipfix.yml
  docs/network-flow-visibility.md
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/types.go
  pkg/agent/flowexporter/utils.go
  pkg/flowaggregator/flowaggregator.go
  test/e2e/flowaggregator_test.go
Labels: cla-not-required

#2197 Update governance
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
  SECURITY.md
  ci/clair-scan/notify.go
  docs/contributors/github-labels.md
Labels: cncf/sandbox
