Repository antrea-io/antrea, pull requests merged in 2021-02, with the labels that each got.

#1790 [CI] Enable prometheus e2e test on dual-stack and IPv6 testbeds
  build/yamls/antrea-prometheus.yml
  ci/jenkins/test.sh
  pkg/agent/proxy/proxier.go
  test/e2e/prometheus_test.go
Labels: cla-not-required

#1688 Add ClusterGroup Membership and Association query API
  pkg/apis/controlplane/register.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/register.go
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go
  pkg/apiserver/registry/networkpolicy/group/rest.go
  pkg/apiserver/registry/networkpolicy/group/rest_test.go
  pkg/apiserver/registry/networkpolicy/groupassociation/rest.go
  pkg/apiserver/registry/networkpolicy/groupassociation/rest_test.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/group.go
Labels: cla-not-required

#1775 Refactor agent interfaces to support GroupMember in appliedToGroups
  cmd/antrea-agent/agent.go
  pkg/agent/cniserver/server.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/status_controller_test.go
  pkg/agent/interfacestore/interface_cache.go
  pkg/agent/interfacestore/testing/mock_interfacestore.go
  pkg/agent/interfacestore/types.go
  pkg/agent/types/networkpolicy.go
  test/integration/agent/cniserver_test.go
Labels: cla-not-required

#1800 Replace golicense with lichen
  .github/workflows/golicense.yml
  build/images/golicense/Dockerfile
  build/images/lichen/Dockerfile
  build/images/lichen/README.md
  ci/golicense/README.md
  ci/golicense/conf.json
  ci/golicense/conf.yml
  ci/golicense/run.sh
Labels: area/licensing, cla-not-required, kind/task

#1781 [Windows] ContainerD support
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_linux.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/cniserver/server_windows.go
  pkg/agent/util/net_windows.go
  plugins/octant/go.sum
Labels: cla-not-required

#1712 Add Antrea upgrade matrix test job
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/test-vmc.sh
Labels: cla-not-required

#1808 Fix AddressGroup memberKey not updated on pod IP update
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/apis/controlplane/sets.go
  pkg/apis/controlplane/v1beta2/sets.go
  pkg/controller/networkpolicy/antreanetworkpolicy_test.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/external_entity_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup_test.go
Labels: cla-not-required

#1806 [CI] Improve e2e tests and scripts
  ci/jenkins/test.sh
  test/e2e/antctl_test.go
  test/e2e/connectivity_test.go
  test/e2e/networkpolicy_test.go
  test/e2e/proxy_test.go
  test/e2e/security_test.go
Labels: cla-not-required

#1801 Add Prometheus metrics to count ANP and ACNP Status updates
  docs/prometheus-integration.md
  pkg/controller/metrics/prometheus.go
  pkg/controller/networkpolicy/status_controller.go
Labels: cla-not-required

#1811 Update file list used to determine if a PR is a documentation PR
  .github/workflows/build.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
Labels: area/test/infra, cla-not-required, kind/task

#1733 [Windows] Enhance OVS installation script
  hack/windows/Install-OVS.ps1
Labels: cla-not-required

#1784 Provide CipherSuites option between Clients and Servers
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/base/conf/antrea-controller.conf
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/config.go
  cmd/antrea-controller/config.go
  cmd/antrea-controller/controller.go
  pkg/agent/apiserver/apiserver.go
  pkg/util/cipher/cipher.go
  pkg/util/cipher/cipher_test.go
  test/e2e/framework.go
  test/e2e/tls_test.go
Labels: cla-not-required

#1814 Fix flaky test TestSvcUpdateAnnotation
  pkg/agent/nodeportlocal/nplagent_test.go
Labels: cla-not-required

#1803 Add ClusterGroup CRD resource to antrea-network-policy doc
  docs/antrea-network-policy.md
Labels: cla-not-required

#1818 Multiple fixes and small improvements for e2e tests
  .github/workflows/kind.yml
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/infra/vagrant/push_antrea.sh
  test/e2e/performance_test.go
Labels: area/test/e2e, cla-not-required

#1827 Add netlify.toml file
  netlify.toml
  site/config.yaml
Labels: cla-not-required

#1734 Add ClusterGroup reference in ClusterNetworkPolicy rules
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/controller.yml
  build/yamls/base/crds.yml
  pkg/apis/security/v1alpha1/types.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/types/networkpolicy.go
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/e2e/k8s_util.go
  test/e2e/networkpolicy_test.go
  test/e2e/reachability.go
  test/e2e/utils/cgspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
Labels: cla-not-required

#1832 [Windows] Fix network policy not working
  cmd/antrea-agent/agent.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  test/integration/agent/cniserver_test.go
Labels: cla-not-required

#1834 [Windows] Fix uplinkTable uninitialized when disable AntreaProxy
  pkg/agent/openflow/pipeline.go
  pkg/util/runtime/runtime.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1836 [Windows] Lock container by ID to prevent concurrent modification
  pkg/agent/cniserver/pod_configuration_windows.go
Labels: cla-not-required

#1825 A few documentation fixes
  docs/antctl.md
  docs/design/ovs-pipeline.md
  docs/feature-gates.md
  docs/octant-plugin-installation.md
  docs/prometheus-integration.md
  docs/troubleshooting.md
  docs/windows.md
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/metrics/prometheus.go
  test/integration/agent/cniserver_test.go
Labels: cla-not-required

#1841 Fix not dedup Priorities in batch register
  pkg/agent/controller/networkpolicy/priority.go
  pkg/agent/controller/networkpolicy/priority_test.go
Labels: cla-not-required

#1824 [Windows] Fix Pod cannot access endpoints with external IP through ClusterIP Service
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/agent/openflow_test.go
Labels: cla-not-required

#1823 [CI] Enable IPv6 TestAntctlProxy test and bug fix
  pkg/antctl/raw/proxy/command.go
  test/e2e/antctl_test.go
Labels: cla-not-required

#1844 Fix unintended priority release when ovs rule install fails
  pkg/agent/controller/networkpolicy/reconciler.go
Labels: cla-not-required

#1821 Fix incorrect use of 'uniq' in golicense run.sh script
  .github/workflows/golicense.yml
  ci/golicense/run.sh
Labels: cla-not-required

#1826 Fix issues with NPL unit tests
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/nplagent_test.go
Labels: cla-not-required

#1840 Avoid warning about 'flow-restore-wait' config with netdev datapath
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_windows.go
  cmd/antrea-agent/options_windows_test.go
  pkg/agent/agent.go
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/flowexporter/connections/conntrack.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/integration/agent/cniserver_test.go
Labels: cla-not-required

#1839 Add liveness probe to Antrea Controller
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
  build/yamls/base/controller.yml
  cmd/antrea-controller/controller.go
  pkg/agent/apiserver/apiserver.go
  pkg/controller/querier/querier.go
  pkg/monitor/controller.go
  test/e2e/security_test.go
Labels: cla-not-required

#1843 Cleanup netpol in testANPBasic after testcase execution
  test/e2e/antreapolicy_test.go
Labels: cla-not-required

#1813 Remove type Group and GroupList from controlplane message
  pkg/apis/controlplane/register.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta1/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/register.go
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_group.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/generated_expansion.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/group.go
  pkg/controller/networkpolicy/store/group.go
  pkg/controller/networkpolicy/store/group_test.go
Labels: cla-not-required

#1849 Rename Netpol Cyclonus Github workflow
  .github/workflows/netpol_cyclonus.yml
Labels: cla-not-required

#1829 Improvements / bug fixes in NPL Controller code
  pkg/agent/nodeportlocal/k8s/npl_controller.go
Labels: cla-not-required

#1847 [Windows] Always update agent configs on startup
  hack/windows/Helper.psm1
Labels: cla-not-required

#1815 Fix: add Endpoints references counter
  pkg/agent/proxy/endpoints.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_others.go
  pkg/agent/proxy/proxier_test.go
  test/e2e/flowaggregator_test.go
  test/e2e/proxy_test.go
Labels: cla-not-required

#1817 Move go-ipfix to v0.4.3
  ci/kind/test-e2e-kind.sh
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/flowaggregator/flowaggregator.go
  plugins/octant/go.sum
  test/e2e/framework.go
Labels: cla-not-required

#1851 Increase kind e2e test timeout to 40m
  ci/kind/test-e2e-kind.sh
Labels: cla-not-required

#1816 Fix NodePort traffic bypassing ingress NetworkPolicy on Linux
  cmd/antrea-agent/agent.go
  docs/design/ovs-pipeline.md
  go.mod
  go.sum
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/route/route_linux.go
  pkg/agent/types/marks.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
  test/integration/agent/openflow_test.go
  test/integration/agent/route_test.go
Labels: cla-not-required

#1750 Add ClusterGroup reference in ClusterNetworkPolicy AppliedTo
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/types/networkpolicy.go
  test/e2e/antreapolicy_test.go
  test/e2e/utils/cnpspecbuilder.go
Labels: cla-not-required

#1703 Support EndpointSlice in Antrea proxy
  Makefile
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/conf/antrea-agent.conf
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/agent.go
  docs/feature-gates.md
  hack/generate-manifest.sh
  pkg/agent/proxy/endpoints.go
  pkg/agent/proxy/endpointslicecache.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/features/antrea_features.go
  third_party/proxy/config/config.go
  third_party/proxy/endpoints.go
Labels: cla-not-required

#1850 Fix CG validation
  pkg/controller/networkpolicy/validate.go
  test/e2e/clustergroup_test.go
  test/e2e/k8s_util.go
Labels: cla-not-required

#1809 Antrea Feature Gates document update for NodePortLocal
  docs/feature-gates.md
Labels: cla-not-required

#1797 Add serviceReference in ClusterGroup
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/controller-rbac.yml
  build/yamls/base/crds.yml
  cmd/antrea-controller/controller.go
  docs/antrea-network-policy.md
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha2/types.go
  pkg/apis/core/v1alpha2/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/group.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/types/group.go
Labels: cla-not-required

#1649 [Flow-Aggregator] Add security support for flow aggregator
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/conf/flow-aggregator.conf
  build/yamls/flow-aggregator/base/flow-aggregator.yml
  ci/test-elk-flow-collector.sh
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  cmd/flow-aggregator/config.go
  cmd/flow-aggregator/flow-aggregator.go
  cmd/flow-aggregator/options.go
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/certificate.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/certificate.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/util/flowexport/flowexport.go
  plugins/octant/go.sum
  test/e2e/framework.go
Labels: cla-not-required

#1862 Update CHANGELOG
  CHANGELOG.md
Labels: cla-not-required

#1859 Fix NPLController unit test failure
  pkg/agent/nodeportlocal/k8s/annotations.go
  pkg/agent/nodeportlocal/k8s/annotations_test.go
  pkg/agent/nodeportlocal/k8s/npl_controller.go
Labels: cla-not-required, kind/bug

#1863 Remove coreos.com links in documentation
  docs/contributors/eks-terraform.md
  docs/os-issues.md
Labels: cla-not-required, kind/documentation

#1795 Document Antrea ARM support
  docs/arm-support.md
  docs/getting-started.md
  hack/.notableofcontents
Labels: cla-not-required, kind/documentation

#1861 Update docs for flow aggregator TLS support
  docs/network-flow-visibility.md
  pkg/flowaggregator/flowaggregator.go
Labels: cla-not-required

#1864 Add missing patch permissions for Pods
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
Labels: cla-not-required

#1865 Remove trailing spaces in doc
  docs/network-flow-visibility.md
Labels: cla-not-required

#1828 Add ExternalEntities to ClusterGroup
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  pkg/apis/core/v1alpha2/types.go
  pkg/apis/core/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/external_entity.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/validate.go
Labels: cla-not-required

#1858 Fail golicense Github workflow if license check fails
  .github/workflows/golicense.yml
  ci/golicense/run.sh
Labels: cla-not-required

#1881 Disable deadlink checker for Github handles
  CHANGELOG.md
  hack/.md_links_config.json
Labels: cla-not-required

#1854 Update Port used in e2e test to int32
  test/e2e/antreapolicy_test.go
  test/e2e/connectivity_test.go
  test/e2e/framework.go
  test/e2e/k8s_util.go
  test/e2e/networkpolicy_test.go
  test/e2e/utils/anpspecbuilder.go
  test/e2e/utils/cnpspecbuilder.go
  test/e2e/utils/networkpolicyspecbuilder.go
Labels: cla-not-required

#1880 Add link to community information at the end of troubleshooting doc
  README.md
  docs/troubleshooting.md
Labels: cla-not-required

#1883 Fix libOpenflow crash for some Traceflow requests
  go.mod
  go.sum
Labels: cla-not-required

#1853 Improve Antrea-policy e2e testcase execution logic
  test/e2e/antreapolicy_test.go
  test/e2e/k8s_util.go
Labels: cla-not-required

#1887 Delete IPTABLES rules for NodePortLocal when nplPortRange is updated
  pkg/agent/nodeportlocal/k8s/npl_controller.go
Labels: cla-not-required

#1879 Change antctl traceflow command to output results at timeout/failure
  pkg/antctl/raw/traceflow/command.go
Labels: cla-not-required

#1890 Move go-ipfix to v0.4.5
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_set.go
  pkg/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
Labels: cla-not-required

#1876 Ensure that "antctl version" always outputs the client version
  docs/contributors/code-generation.md
  hack/update-codegen-dockerized.sh
  pkg/antctl/antctl.go
  pkg/antctl/antctl_test.go
  pkg/antctl/client.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_list.go
  pkg/antctl/fallback/version/fallback.go
  pkg/antctl/mock_antctl_test.go
Labels: cla-not-required

#1846 Unify the writting of containerd
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/server_windows.go
Labels: cla-not-required

#1897 Fix the formatting of antctl trace-packet output
  pkg/antctl/antctl.go
  pkg/antctl/command_definition.go
  pkg/antctl/transform/ovstracing/transform.go
Labels: cla-not-required

#1900 Clean up stale IP addresses on Antrea host gateway
  pkg/agent/agent.go
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_windows.go
  test/integration/agent/net_test.go
  test/integration/agent/net_test_linux.go
  test/integration/agent/net_test_windows.go
Labels: cla-not-required

#1905 [CI] Fix wrong trigger phrase in integration-manual job
  ci/jenkins/jobs/projects.yaml
Labels: cla-not-required

#1884 Fix Traceflow implementation for external IPs and gateway IP
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/apis/ops/v1alpha1/types.go
  pkg/controller/traceflow/controller.go
  test/e2e/fixtures.go
  test/e2e/framework.go
  test/e2e/traceflow_test.go
Labels: cla-not-required

#1906 Fix misleading comments about defaultMTU config parameter
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/config.go
Labels: cla-not-required, kind/documentation

#1913 Fix dead link to PhotonOS documentation
  docs/os-issues.md
Labels: kind/documentation

#1918 Add new area labels for ops and Traceflow
  docs/contributors/github-labels.md
Labels: cla-not-required

#1877 Support dumping OVS flows for a Service with antctl
  cmd/antrea-agent/agent.go
  docs/antctl.md
  hack/update-codegen-dockerized.sh
  pkg/agent/apiserver/handlers/ovsflows/handler.go
  pkg/agent/apiserver/handlers/ovsflows/handler_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/testing/mock_proxy.go
  pkg/agent/querier/querier.go
  pkg/agent/querier/testing/mock_querier.go
  pkg/antctl/antctl.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/ovsctl/interface.go
  pkg/ovs/ovsctl/ofctl.go
  pkg/ovs/ovsctl/testing/mock_ovsctl.go
  test/integration/agent/openflow_test.go
  test/integration/ovs/ofctrl_test.go
Labels: cla-not-required
