Repository antrea-io/antrea, pull requests merged in 2021-06, with the labels that each got.

#2082 print featuregates via antctl
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/antctl.yml
  build/yamls/base/controller-rbac.yml
  build/yamls/base/controller.yml
  build/yamls/base/kustomization.yml
  cmd/antrea-controller/controller.go
  docs/antctl.md
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/featuregates/handler.go
  pkg/antctl/antctl.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_list.go
  pkg/antctl/raw/featuregates/command.go
  pkg/antctl/raw/helper.go
  pkg/antctl/raw/proxy/command.go
  pkg/antctl/raw/supportbundle/command.go
  pkg/antctl/raw/traceflow/command.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/handlers/featuregates/handler.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/apiserver/registry/system/controllerinfo/rest_test.go
  pkg/controller/querier/querier.go
  pkg/features/antrea_features.go
  pkg/util/env/env.go
  pkg/util/env/env_test.go
  test/e2e/antctl_test.go
Labels: cla-not-required

#2117 [CI] Prune stale images in testbeds
  ci/jenkins/test.sh
Labels: cla-not-required

#2257 Automated cherry pick of #2253: Fix the race condition in ifConfigurator
  pkg/agent/cniserver/interface_configuration_windows.go
Labels: kind/cherry-pick

#2256 Automated cherry pick of #2253: Fix the race condition in ifConfigurator
  pkg/agent/cniserver/interface_configuration_windows.go
Labels: kind/cherry-pick

#2255 Automated cherry pick of #2253: Fix the race condition in ifConfigurator
  pkg/agent/cniserver/interface_configuration_windows.go
Labels: kind/cherry-pick

#2265 Remove deprecated api
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/antctl.yml
  build/yamls/base/controller-rbac.yml
  build/yamls/base/controller.yml
  docs/api.md
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/certificate/cacert_controller.go
  pkg/legacyapis/networking/doc.go
  pkg/legacyapis/networking/install/install.go
  pkg/legacyapis/networking/register.go
  pkg/legacyapis/networking/v1beta1/doc.go
  pkg/legacyapis/networking/v1beta1/register.go
Labels: kind/api-change, kind/cleanup

#2143 Drop eth0 packets in PREROUTING on Kind Nodes
  build/images/scripts/start_ovs_netdev
  ci/kind/kind-setup.sh
  hack/kind-fix-networking.sh
  test/e2e/antreapolicy_test.go
  test/e2e/fixtures.go
Labels: cla-not-required

#2271 Add documentation regarding Namespaces field
  docs/antrea-network-policy.md
Labels: kind/documentation

#2284 Fix template and fields missing issue in dual stack e2e tests
  ci/kind/test-e2e-kind.sh
  go.mod
  go.sum
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/ipfix/ipfix_intermediate.go
  pkg/ipfix/testing/mock_ipfix.go
  plugins/octant/go.sum
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: area/flow-visibility, area/test/e2e

#2231 Add flow-aggregator e2e test for pod-to-external flow type
  test/e2e/connectivity_test.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
Labels: area/flow-visibility, area/test/e2e

#2310 Automated cherry pick of #2302: Fix MarshalJSON error caused by incorrect conversion function
  pkg/apis/controlplane/v1beta1/conversion.go
  pkg/apis/controlplane/v1beta1/conversion_test.go
Labels: kind/cherry-pick

#2311 Automated cherry pick of #2302: Fix MarshalJSON error caused by incorrect conversion function
  pkg/apis/controlplane/v1beta1/conversion.go
  pkg/apis/controlplane/v1beta1/conversion_test.go
Labels: kind/cherry-pick

#2314 Automated cherry pick of #2305: Fix wrong types and missing field selectors in legacy APIs
  pkg/legacyapis/controlplane/v1beta1/conversion.go
  pkg/legacyapis/controlplane/v1beta1/register.go
  pkg/legacyapis/networking/v1beta1/conversion.go
Labels: kind/cherry-pick

#2313 Automated cherry pick of #2305: Fix wrong types and missing field selectors in legacy APIs
  pkg/legacyapis/controlplane/v1beta1/conversion.go
  pkg/legacyapis/controlplane/v1beta1/register.go
  pkg/legacyapis/networking/v1beta1/conversion.go
Labels: kind/cherry-pick

#2312 Automated cherry pick of #2302: Fix MarshalJSON error caused by incorrect conversion function
  pkg/apis/controlplane/v1beta1/conversion.go
  pkg/apis/controlplane/v1beta1/conversion_test.go
Labels: kind/cherry-pick

#2320 Automated cherry pick of #2317: Fix ovs group id conflict when dual stack is enabled
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/types/groupcounter.go
Labels: kind/cherry-pick

#2322 Automated cherry pick of #2317: Fix ovs group id conflict when dual stack is enabled
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/types/groupcounter.go
Labels: kind/cherry-pick

#2323 Automated cherry pick of #2317: Fix ovs group id conflict when dual stack is enabled
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/types/groupcounter.go
Labels: kind/cherry-pick

#2326 Automated cherry pick of #2306: [Windows]Check HostNamespace value when removing HcnEndpoint
  pkg/agent/cniserver/interface_configuration_windows.go
Labels: kind/cherry-pick

#2321 Automated cherry pick of #2318: Fix cross-Node service access when AntreaProxy is disabled
  docs/design/ovs-pipeline.md
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  test/e2e/service_test.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick
