Repository antrea-io/antrea, pull requests merged in 2021-09, with the labels that each got.

#2628 Improve NodePortLocal documentation
  docs/feature-gates.md
  docs/node-port-local.md
Labels: kind/documentation, area/proxy/nodeportlocal

#2690 Automated cherry pick of #2672: Convert NodeName obtained from env var to lowercase on
  pkg/util/env/env.go
Labels: kind/cherry-pick

#2691 Automated cherry pick of #2662: Add in-cluster svc fqdn e2e test
  test/e2e/antreapolicy_test.go
  test/e2e/k8s_util.go
Labels: kind/cherry-pick

#2703 Automated cherry pick of #2697: Fix service traffic requiring SNAT
  pkg/agent/agent.go
  pkg/agent/wireguard/client_linux.go
  pkg/agent/wireguard/client_windows.go
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#2710 Automated cherry pick of #2675: Generate ssh-config for all Nodes
  ci/jenkins/test.sh
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#2711 Automated cherry pick of #2695: Wait for ovs-vswitchd PID before calling ovs-appctl
  build/images/scripts/start_ovs
  pkg/ovs/ovsctl/interface.go
  pkg/ovs/ovsctl/ovsctl_others.go
Labels: kind/cherry-pick

#2713 Automated cherry pick of #2655: Fix agent panic because of nil NodeIP in pure IPv6 cluster
  cmd/antrea-agent/agent.go
  pkg/agent/memberlist/cluster.go
  pkg/agent/util/ndp/doc.go
  test/e2e/egress_test.go
  test/e2e/fixtures.go
  test/e2e/framework.go
  test/e2e/service_test.go
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#2714 Automated cherry pick of #2712: Fix WireGuard testServiceConnectivity in IPv6 cluster
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#2715 Automated cherry pick of #2705: Update test.sh * Retry after reverting Windows VM
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#2733 Automated cherry pick of #2702: Bugfix: SNAT is not performed on the +est packets.
  pkg/agent/openflow/pipeline_windows.go
Labels: kind/cherry-pick

#1561 Use NodeIPAMController code from K8S
  README.md
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-controller.conf
  build/yamls/base/controller-rbac.yml
  cmd/antrea-controller/config.go
  cmd/antrea-controller/controller.go
  cmd/antrea-controller/options.go
  docs/feature-gates.md
  pkg/apiserver/handlers/featuregates/handler.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
  third_party/ipam/LICENSE
  third_party/ipam/README
  third_party/ipam/controller_util_node/controller_utils.go
  third_party/ipam/nodeipam/ipam/cidr_allocator.go
  third_party/ipam/nodeipam/ipam/cidrset/cidr_set.go
  third_party/ipam/nodeipam/ipam/cidrset/metrics.go
  third_party/ipam/nodeipam/ipam/range_allocator.go
  third_party/ipam/nodeipam/node_ipam_controller.go
  third_party/ipam/util_node/node.go
Labels: cla-not-required

#2746 Automated cherry pick of #2723: Fix TestEgress flaky failure in jenkins-ipv6-only-e2e
  test/e2e/egress_test.go
Labels: kind/cherry-pick

#2756 Automated cherry pick of #2751: Bugfix: Agent crashed when removing the existing
  pkg/agent/util/net_windows.go
Labels: kind/cherry-pick

#2757 Automated cherry pick of #2730: Fix panic bug in Antrea Policy
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: kind/cherry-pick

#2759 Automated cherry pick of #2730: Fix panic bug in Antrea Policy
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: kind/cherry-pick

#2758 Automated cherry pick of #2730: Fix panic bug in Antrea Policy
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: kind/cherry-pick

#2760 Automated cherry pick of #2730: Fix panic bug in Antrea Policy
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: kind/cherry-pick

#2761 Automated cherry pick of #2730: Fix panic bug in Antrea Policy
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: kind/cherry-pick

#2765 Automated cherry pick of #2582: remove config mismatched port during creation
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
Labels: kind/cherry-pick

#2764 Automated cherry pick of #2489: remove tunnel limitation for IPSec
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/config.go
  cmd/antrea-agent/options.go
  docs/design/architecture.md
  docs/ipsec-tunnel.md
Labels: kind/cherry-pick

#2789 Automated cherry pick of #2598: supportbundle: fix nil pointer error
  pkg/apiserver/registry/system/supportbundle/rest.go
Labels: kind/cherry-pick

#2795 Automated cherry pick of #2768: Fix triggerCNPUpdates panic
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: kind/cherry-pick

#2798 Automated cherry pick of #2778: Bugfix for MTU configuration on nonexistent
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/sriov.go
Labels: kind/cherry-pick

#2818 Use @antrea-io/review-manager to manage PR reviews
  .github/AREA-OWNERS
  .github/workflows/reviews.yml
Labels: community

#2808 add client generate codes
  multicluster/Makefile
  multicluster/apis/multicluster/v1alpha1/clusterclaim_types.go
  multicluster/apis/multicluster/v1alpha1/clusterset_types.go
  multicluster/apis/multicluster/v1alpha1/doc.go
  multicluster/apis/multicluster/v1alpha1/memberclusterannounce_types.go
  multicluster/apis/multicluster/v1alpha1/register.go
  multicluster/apis/multicluster/v1alpha1/resourceexport_types.go
  multicluster/apis/multicluster/v1alpha1/resourceexportfilter_types.go
  multicluster/apis/multicluster/v1alpha1/resourceimport_types.go
  multicluster/apis/multicluster/v1alpha1/resourceimportfilter_types.go
  multicluster/hack/update-codegen-dockerized.sh
  multicluster/hack/update-codegen.sh
  multicluster/pkg/client/clientset/versioned/clientset.go
  multicluster/pkg/client/clientset/versioned/doc.go
  multicluster/pkg/client/clientset/versioned/fake/clientset_generated.go
  multicluster/pkg/client/clientset/versioned/fake/doc.go
  multicluster/pkg/client/clientset/versioned/fake/register.go
  multicluster/pkg/client/clientset/versioned/scheme/doc.go
  multicluster/pkg/client/clientset/versioned/scheme/register.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/clusterclaim.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/clusterset.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/doc.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/doc.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_clusterclaim.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_clusterset.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_memberclusterannounce.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_multicluster_client.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_resourceexport.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_resourceexportfilter.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_resourceimport.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_resourceimportfilter.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/generated_expansion.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/memberclusterannounce.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/multicluster_client.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/resourceexport.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/resourceexportfilter.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/resourceimport.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/resourceimportfilter.go
  multicluster/pkg/client/informers/externalversions/factory.go
  multicluster/pkg/client/informers/externalversions/generic.go
  multicluster/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  multicluster/pkg/client/informers/externalversions/multicluster/interface.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/clusterclaim.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/clusterset.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/interface.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/memberclusterannounce.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/resourceexport.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/resourceexportfilter.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/resourceimport.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/resourceimportfilter.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/clusterclaim.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/clusterset.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/expansion_generated.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/memberclusterannounce.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/resourceexport.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/resourceexportfilter.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/resourceimport.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/resourceimportfilter.go
Labels: area/multi-cluster

#2821 Automated cherry pick of #2813: Reduce memory consumption of supportbundle command
  pkg/antctl/raw/supportbundle/command.go
Labels: kind/cherry-pick

#2834 Automated cherry pick of #2815: Fix Windows NetPol test failures * Retry resync VM time
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#2797 Automated cherry pick of #2778: Bugfix for MTU configuration on nonexistent
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/sriov.go
Labels: kind/cherry-pick

#2836 Automated cherry pick of #2815: Fix Windows NetPol test failures * Retry resync VM time
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#2845 Use Node TransportIP interface to send EgressIP gratuitous arp
  cmd/antrea-agent/agent.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/ipassigner/ip_assigner_linux.go
  pkg/agent/controller/egress/ipassigner/ip_assigner_windows.go
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: review-manager-test, area/transit/egress

#2741 Update release documentation
  .github/AREA-OWNERS
  docs/contributors/github-labels.md
  docs/maintainers/antrea-docker-image.md
  docs/maintainers/release.md
  hack/.notableofcontents
Labels: kind/documentation

#2858 Wait for AntreaProxy to be ready before accessing Service
  cmd/antrea-agent/agent.go
  pkg/agent/proxy/proxier.go
  third_party/proxy/meta_proxier.go
  third_party/proxy/types.go
Labels: area/proxy, review-manager-test
