Repository antrea-io/antrea, pull requests merged in 2021-12, with the labels that each got.

#2951 Update Antrea Octant plugin to support latest Octant version
  build/images/Dockerfile.octant.ubuntu
  ci/golicense/conf.yml
  docs/octant-plugin-installation.md
  plugins/octant/cmd/antrea-octant-plugin/antrea_info.go
  plugins/octant/cmd/antrea-octant-plugin/main.go
  plugins/octant/cmd/antrea-octant-plugin/traceflow.go
  plugins/octant/go.mod
  plugins/octant/go.sum
Labels: area/component/octant-plugin

#3079 Fix typo in antrea-network-policy doc
  docs/antrea-network-policy.md
Labels: kind/documentation, size/XS, area/network-policy

#3069 Automated cherry pick of #3043: Fix SetInterfaceMTU not working on Windows bug For Windows,
  pkg/agent/agent.go
Labels: kind/cherry-pick

#3071 Automated cherry pick of #3043: Fix SetInterfaceMTU not working on Windows bug For Windows,
  pkg/agent/agent.go
Labels: kind/cherry-pick

#3070 Automated cherry pick of #3043: Fix SetInterfaceMTU not working on Windows bug For Windows,
  pkg/agent/agent.go
Labels: kind/cherry-pick

#3087 Automated cherry pick of #3074: Fix status report of Antrea-native policies
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  test/e2e/antreapolicy_test.go
Labels: kind/cherry-pick

#3102 Automated cherry pick of #3083: Fix NetworkPolicy resources dump for Agent's supportbundle
  pkg/apis/controlplane/v1beta2/marshal.go
  pkg/support/dump.go
Labels: kind/cherry-pick

#3103 Automated cherry pick of #3083: Fix NetworkPolicy resources dump for Agent's supportbundle
  pkg/apis/controlplane/v1beta2/marshal.go
  pkg/support/dump.go
Labels: kind/cherry-pick

#3113 Improve NodePortLocal documentation
  docs/node-port-local.md
Labels: kind/documentation, area/proxy/nodeportlocal

#3015 Add multicluster image in registry
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  Makefile
  build/images/Dockerfile.build.ubuntu
  build/images/Dockerfile.simulator.build.ubuntu
  build/images/Dockerfile.ubuntu
  multicluster/Makefile
  multicluster/build/Dockerfile.build
Labels: area/multi-cluster

#3105 Add multi-cluster manual integration job
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
Labels: area/multi-cluster

#3139 Half the number of days before issues & PRs become stale / closed
  .github/workflows/lifecycle_management.yml
Labels: kind/task

#3111 MemberClusterAnnounce webhook and Clusterset status implementations
  multicluster/apis/multicluster/v1alpha1/clusterset_types.go
  multicluster/apis/multicluster/v1alpha1/memberclusterannounce_webhook.go
  multicluster/apis/multicluster/v1alpha1/webhook_suite_test.go
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member-only.yml
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/cmd/multicluster-controller/memberclusterannounce_webhook.go
  multicluster/cmd/multicluster-controller/memberclusterannounce_webhook_test.go
  multicluster/config/webhook/manifests.yaml
  multicluster/controllers/multicluster/core/mock_remote_common_area.go
  multicluster/controllers/multicluster/core/mock_remote_common_area_manager.go
  multicluster/controllers/multicluster/core/remote_common_area.go
  multicluster/controllers/multicluster/core/remote_common_area_manager.go
  multicluster/controllers/multicluster/leader_clusterset_controller.go
  multicluster/controllers/multicluster/leader_clusterset_controller_test.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/memberclusterannounce_controller.go
  multicluster/controllers/multicluster/memberclusterannounce_controller_test.go
  multicluster/controllers/multicluster/mock_membercluster_status_manager.go
Labels: area/multi-cluster

#3089 [windows] Fix bug in configureContainerLink
  pkg/agent/cniserver/interface_configuration_windows.go
Labels: review-manager-test
