Repository antrea-io/antrea, pull requests merged in 2021-08, with the labels that each got.

#2504 Automated cherry pick of #2495: Fix panic in stats.calculateRuleDiff
  pkg/agent/stats/collector.go
  pkg/agent/stats/collector_test.go
Labels: kind/cherry-pick

#2520 Automated cherry pick of #2476: Install all Endpoint flows belong to a Service via single
  pkg/agent/openflow/client.go
Labels: kind/cherry-pick

#2505 Automated cherry pick of #2495: Fix panic in stats.calculateRuleDiff
  pkg/agent/stats/collector.go
  pkg/agent/stats/collector_test.go
Labels: kind/cherry-pick

#2443 Remove child group existence validation for ClusterGroup
  pkg/controller/networkpolicy/validate.go
  test/e2e/antreapolicy_test.go
  test/e2e/clustergroup_test.go
  test/e2e/legacyclustergroup_test.go
Labels: area/network-policy/lifecycle

#2513 Document update of OVS windows binaries distributed by Antrea
  docs/maintainers/updating-ovs-windows.md
  hack/.notableofcontents
Labels: kind/documentation

#2506 Automated cherry pick of #2495: Fix panic in stats.calculateRuleDiff
  pkg/agent/stats/collector.go
  pkg/agent/stats/collector_test.go
Labels: kind/cherry-pick

#2507 Automated cherry pick of #2479: Improve NetworkPolicy batch installation
  go.mod
  go.sum
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/util/ip/ip.go
  plugins/octant/go.sum
Labels: kind/cherry-pick

#2508 Automated cherry pick of #2479: Improve NetworkPolicy batch installation
  go.mod
  go.sum
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/util/ip/ip.go
  plugins/octant/go.sum
Labels: kind/cherry-pick

#2524 Automated cherry pick of #2522: Log maintenance bug fix in the Flow Aggregator
  cmd/flow-aggregator/flow-aggregator.go
Labels: kind/cherry-pick

#2525 Fix link in kubernetes-installers.md
  docs/kubernetes-installers.md
Labels: kind/documentation

#2528 Remove controlplane.antrea.tanzu.vmware.com/v1beta1
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/controller-rbac.yml
  build/yamls/base/controller.yml
  docs/api.md
  hack/update-codegen-dockerized.sh
  pkg/apiserver/apiserver.go
  pkg/apiserver/certificate/cacert_controller.go
  pkg/legacyapis/controlplane/install/install.go
  pkg/legacyapis/controlplane/v1beta1/conversion.go
  pkg/legacyapis/controlplane/v1beta1/doc.go
  pkg/legacyapis/controlplane/v1beta1/register.go
  pkg/legacyclient/clientset/versioned/clientset.go
  pkg/legacyclient/clientset/versioned/fake/clientset_generated.go
  pkg/legacyclient/clientset/versioned/fake/register.go
  pkg/legacyclient/clientset/versioned/scheme/register.go
  pkg/legacyclient/clientset/versioned/typed/controlplane/v1beta1/controlplane_client.go
  pkg/legacyclient/clientset/versioned/typed/controlplane/v1beta1/doc.go
  pkg/legacyclient/clientset/versioned/typed/controlplane/v1beta1/fake/doc.go
  pkg/legacyclient/clientset/versioned/typed/controlplane/v1beta1/fake/fake_controlplane_client.go
  pkg/legacyclient/clientset/versioned/typed/controlplane/v1beta1/generated_expansion.go
Labels: kind/api-change

#2516 [Bug fix]Connections are not deleted properly in Flow Exporter when they are not exported
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/connections_test.go
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
  pkg/agent/flowexporter/connections/deny_connections.go
  pkg/agent/flowexporter/connections/deny_connections_test.go
  pkg/agent/flowexporter/exporter/exporter_perf_test.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/flowrecords/flow_records.go
  test/integration/agent/flowexporter_test.go
Labels: area/flow-visibility/exporter, kind/bug

#2536 Automated cherry pick of #2516: Bug fix in Flow Exporter related deletion of connections
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/connections_test.go
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
  pkg/agent/flowexporter/connections/deny_connections.go
  pkg/agent/flowexporter/connections/deny_connections_test.go
  pkg/agent/flowexporter/exporter/exporter_perf_test.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/agent/flowexporter/flowrecords/flow_records.go
  test/integration/agent/flowexporter_test.go
Labels: kind/cherry-pick

#2541 Automated cherry pick of #2535: antrea-agent readiness probe tolerates longer disconnection
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
Labels: kind/cherry-pick

#2543 Fix Ansible playbooks (Vagrant test infra) for K8s 1.22
  test/e2e/infra/vagrant/playbook/roles/common/tasks/docker.yml
  test/e2e/infra/vagrant/playbook/roles/common/templates/docker.json.j2
Labels: area/test/infra

#2540 Automated cherry pick of #2469: Bug fix in adding iptable rules * bug fix in
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/rules/iptable_rule.go
  pkg/agent/nodeportlocal/rules/rules.go
  pkg/agent/nodeportlocal/rules/testing/mock_rules.go
  pkg/agent/route/route_linux.go
  pkg/agent/util/iptables/iptables.go
Labels: kind/cherry-pick

#2546 [Flow Exporter] Fix missing template when sending first record
  pkg/flowaggregator/flowaggregator.go
Labels: area/flow-visibility, area/flow-visibility/exporter

#2551 Automated cherry pick of #2546: Fix missing template when sending first record
  pkg/flowaggregator/flowaggregator.go
Labels: kind/cherry-pick

#2560 Automated cherry pick of #2486: fix tunnel interface name issue
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
  pkg/agent/util/net.go
Labels: kind/cherry-pick

#2553 Automated cherry pick of #2469: Bug fix in adding iptable rules * bug fix in
  go.mod
  go.sum
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/rules/iptable_rule.go
  pkg/agent/nodeportlocal/rules/rules.go
  pkg/agent/nodeportlocal/rules/testing/mock_rules.go
  pkg/agent/route/route_linux.go
  pkg/agent/util/iptables/iptables.go
  plugins/octant/go.sum
Labels: kind/cherry-pick

#2575 Automated cherry pick of #2555: Handle iptables-restore failures correctly in NPL
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
Labels: kind/cherry-pick

#2597 Automated cherry pick of #2574: Move the go-ipfix tag after adding performance fixes:
  go.mod
  go.sum
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  plugins/octant/go.sum
Labels: kind/cherry-pick

#2596 Update Antrea-native policy doc for Namespace labels
  docs/antrea-network-policy.md
Labels: kind/documentation

#2602 Automated cherry pick of #2579: Fix Reject loop issue
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
Labels: kind/cherry-pick

#2605 Update AllowToCoreDNS rule to permit udp on port 53
  docs/antrea-network-policy.md
Labels: kind/documentation

#2431 Resolve flow aggregator close issue
  ci/kind/test-e2e-kind.sh
  cmd/flow-aggregator/flow-aggregator.go
  pkg/flowaggregator/flowaggregator.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: area/flow-visibility, area/flow-visibility/aggregator, area/flow-visibility/exporter

#2559 [Flow Aggregator] Add support for sending JSON record
  build/yamls/elk-flow-collector/elk-flow-collector.yml
  build/yamls/elk-flow-collector/kibana.ndjson
  build/yamls/elk-flow-collector/logstash/filter.rb
  build/yamls/elk-flow-collector/logstash/ipfix.yml
  build/yamls/elk-flow-collector/logstash/logstash.conf
  build/yamls/elk-flow-collector/logstash/logstash.yml
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/conf/flow-aggregator.conf
  cmd/flow-aggregator/config.go
  cmd/flow-aggregator/flow-aggregator.go
  cmd/flow-aggregator/options.go
  docs/network-flow-visibility.md
  pkg/flowaggregator/flowaggregator.go
Labels: area/flow-visibility, area/flow-visibility/aggregator, area/flow-visibility/elk

#2636 [CI] Fix typo in Jenkins test.sh script
  ci/jenkins/test.sh
Labels: area/test/infra, area/test/jenkins

#2678 Automated cherry pick of #2633: Fix Mellanox CI build command
  ci/jenkins/mellanox/common/common_functions.sh
  ci/jenkins/mellanox/scripts/start_ci.sh
Labels: kind/cherry-pick

#2667 Fix documentation for FQDN based policies which use Service DNS names
  docs/antrea-network-policy.md
Labels: kind/documentation

#2679 Automated cherry pick of #2667: Fix documentation for FQDN based policies which use
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#2677 Automated cherry pick of #2670: Fix init node transport interface bug (#2670)
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/util/net.go
Labels: kind/cherry-pick

#2682 Automated cherry pick of #2681: Upgrade Windows OVS version to 2.14.2
  hack/windows/Install-OVS.ps1
Labels: kind/cherry-pick
