Repository antrea-io/antrea, pull requests merged in 2022-12, with the labels that each got.

#4424 Update multi-cluster manifests and add CI check
  ci/check-manifest.sh
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_labelidentities.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
Labels: area/multi-cluster

#4434 Use iptables wrapper in antrea/ethtool Docker image
  build/images/ethtool/Dockerfile
Labels: kind/bug, area/test/infra

#4412 Fix ClusterInfo type ResourceExport recreation bug
  multicluster/controllers/multicluster/gateway_controller.go
  multicluster/controllers/multicluster/gateway_controller_test.go
Labels: area/multi-cluster, action/backport

#4339 Add multicast documents
  docs/antctl.md
  docs/feature-gates.md
  docs/multicast-guide.md
Labels: kind/documentation

#4443 Automated cherry pick of #4389: Fix UBI image build error
  build/images/ovs/Dockerfile.ubi
Labels: kind/cherry-pick

#4377 Improve unit test coverage for multi-cluster controllers
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go
  multicluster/controllers/multicluster/commonarea/clusterinfo_importer_test.go
  multicluster/controllers/multicluster/commonarea/labelidentityimport_controller_test.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area_wrapper.go
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_test.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
  multicluster/controllers/multicluster/gateway_controller_test.go
  multicluster/controllers/multicluster/label_identity_controller_test.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/member_clusterset_controller_test.go
  multicluster/controllers/multicluster/mock_member_clusterset_controller.go
  multicluster/controllers/multicluster/serviceexport_controller_test.go
  multicluster/controllers/multicluster/stale_controller_test.go
  test/e2e/nodeportlocal_test.go
Labels: area/multi-cluster

#4442 Automated cherry pick of #4412: Fix ClusterInfo type ResourceExport recreation bug
  multicluster/controllers/multicluster/gateway_controller.go
  multicluster/controllers/multicluster/gateway_controller_test.go
Labels: kind/cherry-pick

#4453 Automated cherry pick of #4389: Fix UBI image build error
  build/images/ovs/Dockerfile.ubi
Labels: kind/cherry-pick

#4454 Automated cherry pick of #4389: Fix UBI image build error
  build/images/ovs/Dockerfile.ubi
Labels: kind/cherry-pick

#4429 Add StretchedNetworkPolicy toggle
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-controller.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-controller/controller.go
  cmd/antrea-controller/options.go
  multicluster/apis/multicluster/v1alpha1/multiclusterconfig_types.go
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/leader_test.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/cmd/multicluster-controller/member_test.go
  multicluster/cmd/multicluster-controller/options.go
  multicluster/config/default/configmap/controller_manager_config.yaml
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_test.go
  multicluster/controllers/multicluster/gateway_controller_test.go
  multicluster/controllers/multicluster/label_identity_controller_test.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/serviceexport_controller_test.go
  multicluster/controllers/multicluster/stale_controller_test.go
  multicluster/test/integration/suite_test.go
  pkg/config/controller/config.go
Labels: area/multi-cluster

#4469 Bugfix: Resolve a deadlock in cluster memberlist maintanance
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: kind/bug, action/backport, action/release-note

#4471 Automated cherry pick of #4469: Bugfix: Resolve a deadlock in cluster memberlist maintanance
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: kind/cherry-pick

#4450 Automated cherry pick of #4103: Fix Windows AddNodePort parameter error
  pkg/agent/config/node_config.go
  pkg/agent/route/route_windows.go
Labels: kind/cherry-pick

#4449 Automated cherry pick of #4428: Bugfix: Pod or gateway interface use a different MAC from the
  pkg/agent/agent.go
  pkg/agent/agent_linux_test.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/agent_windows_test.go
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/interfacestore/types.go
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/ovs_client_test.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  third_party/containernetworking/ip/link_linux.go
Labels: kind/cherry-pick

#4451 Automated cherry pick of #4428: Bugfix: Pod or gateway interface use a different MAC from the
  pkg/agent/agent.go
  pkg/agent/agent_linux_test.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/agent_windows_test.go
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/interfacestore/types.go
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/ovs_client_test.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  third_party/containernetworking/ip/link_linux.go
Labels: kind/cherry-pick

#4472 Automated cherry pick of #4469: Bugfix: Resolve a deadlock in cluster memberlist maintanance
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: kind/cherry-pick

#4483 Automated cherry pick of #4016: Fix unit test flaky for IPsec controller #4060: Fix race condition in unit test for IPsec #4241: Fix flaky TestController_RotateCertificates unit test
  pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go
Labels: kind/cherry-pick

#4448 Automated cherry pick of #4428: Bugfix: Pod or gateway interface use a different MAC from the
  pkg/agent/agent.go
  pkg/agent/agent_linux_test.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/agent_windows_test.go
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/interfacestore/interface_cache_test.go
  pkg/agent/interfacestore/types.go
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/ovs_client_test.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  third_party/containernetworking/ip/link_linux.go
Labels: kind/cherry-pick

#4447 Automated cherry pick of #4126: Add OFSwitch connection check to Agent's liveness probes
  build/charts/antrea/templates/agent/daemonset.yaml
  build/images/scripts/container_liveness_probe
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_test.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/apiserver_test.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_bridge_test.go
  pkg/ovs/openflow/ofctrl_packetout_test.go
Labels: kind/cherry-pick

#4491 Make memberlist cluster rejoin dead nodes periodically
  hack/update-codegen-dockerized.sh
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
  pkg/agent/memberlist/testing/mock_memberlist.go
Labels: area/transit/egress, action/backport, action/release-note

#4432 Add addressgroup peer for in-cluster stretched NetworkPolicy enforcement
  pkg/apis/controlplane/types.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
Labels: area/multi-cluster

#4492 Automated cherry pick of #4491: Make memberlist cluster rejoin dead nodes periodically
  cmd/antrea-agent/agent.go
  hack/update-codegen-dockerized.sh
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
  pkg/agent/memberlist/testing/mock_memberlist.go
Labels: kind/cherry-pick

#4051 Automated cherry pick of #3882: Add a new option --service-cidr
  ci/kind/kind-setup.sh
  docs/kind.md
Labels: kind/cherry-pick

#4049 Automated cherry pick of #3995: Set up Kind clusters to run multi-cluster e2e
  ci/jenkins/test-mc.sh
  multicluster/test/e2e/README.md
  multicluster/test/e2e/antreapolicy_test.go
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
Labels: kind/cherry-pick

#3926 Improve support for Egress in Traceflow
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/pipeline.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/graphviz/traceflow.go
  pkg/graphviz/traceflow_test.go
  pkg/querier/querier.go
  test/e2e/traceflow_test.go
  test/integration/agent/openflow_test.go
Labels: action/release-note

#3914 StretchedNetworkPolicy Agent Implementation
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/conf/antrea-controller.conf
  build/charts/antrea/templates/agent/clusterrole.yaml
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  ci/jenkins/test-mc.sh
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  multicluster/controllers/multicluster/label_identity_controller.go
  multicluster/controllers/multicluster/label_identity_controller_test.go
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/agent/controller/networkpolicy/reject.go
  pkg/agent/multicluster/mc_route_controller.go
  pkg/agent/multicluster/mc_route_controller_test.go
  pkg/agent/multicluster/stretched_networkpolicy_controller.go
  pkg/agent/multicluster/stretched_networkpolicy_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/multicluster.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/types/networkpolicy.go
  pkg/config/agent/config.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/e2e/framework.go
  test/e2e/utils/cnp_spec_builder.go
  test/integration/agent/cniserver_test.go
  test/integration/agent/openflow_test.go
Labels: area/multi-cluster

#4397 Add `scope` field for `toServices` in Antrea-native policies
  build/charts/antrea/crds/clusternetworkpolicy.yaml
  build/charts/antrea/crds/networkpolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/test/e2e/service_test.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/networkpolicy/antreanetworkpolicy_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/utils/anp_spec_builder.go
  test/e2e/utils/cnp_spec_builder.go
Labels: area/multi-cluster

#4279 Add containerd runtime support for antrea agent on windows
  build/yamls/antrea-windows-containerd.yml
  build/yamls/windows/base/agent-containerd.yml
  build/yamls/windows/base/conf/Install-WindowsCNI-Containerd.ps1
  build/yamls/windows/base/conf/Run-AntreaAgent-Containerd.ps1
  ci/jenkins/test-mc.sh
  ci/jenkins/test.sh
  docs/windows.md
  hack/generate-manifest-windows.sh
  hack/release/prepare-assets.sh
  test/e2e/traceflow_test.go
Labels: action/release-note

#4350 Add documentation for Stretched NetworkPolicy feature
  docs/multicluster/user-guide.md
Labels: area/multi-cluster

#4516 Update comment to remove the tunnel type limit
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: area/multi-cluster

#4509 Update feature gate doc for the Multicluster feature
  docs/feature-gates.md
Labels: area/multi-cluster
