Repository antrea-io/antrea, pull requests merged in 2022-10, with the labels that each got.

#3664 Label Identity replication for MCS
  go.mod
  multicluster/apis/multicluster/v1alpha1/labelidentity_types.go
  multicluster/apis/multicluster/v1alpha1/resourceexport_types.go
  multicluster/apis/multicluster/v1alpha1/resourceimport_types.go
  multicluster/apis/multicluster/v1alpha1/zz_generated.deepcopy.go
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/config/crd/bases/multicluster.crd.antrea.io_labelidentities.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  multicluster/config/crd/kustomization.yaml
  multicluster/config/overlays/leader-global/crd_patch.yaml
  multicluster/config/overlays/member/role.yaml
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/common/helper_test.go
  multicluster/controllers/multicluster/commonarea/labelidentityimport_controller.go
  multicluster/controllers/multicluster/commonarea/labelidentityimport_controller_test.go
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/controllers/multicluster/label_identity_controller.go
  multicluster/controllers/multicluster/label_identity_controller_test.go
  multicluster/controllers/multicluster/label_identity_export_controller.go
  multicluster/controllers/multicluster/label_identity_export_controller_test.go
  multicluster/controllers/multicluster/resourceexport_controller.go
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_labelidentity.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_multicluster_client.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/generated_expansion.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/labelidentity.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/multicluster_client.go
  multicluster/pkg/client/informers/externalversions/generic.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/interface.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/labelidentity.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/expansion_generated.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/labelidentity.go
Labels: area/multi-cluster

#4178 Add rule name to Audit Logging
  docs/antrea-network-policy.md
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/agent/controller/networkpolicy/audit_logging_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/testing/mock_openflow.go
  test/e2e/antreapolicy_test.go
Labels: area/network-policy, action/release-note

#4297 Fix route for IPv6 ClusterIPs
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
Labels: kind/bug, area/proxy, action/release-note

#4240 Fix unexpected reporting of empty MulticastGroupInfo
  pkg/agent/stats/collector.go
  pkg/agent/stats/collector_test.go
Labels: action/backport, action/release-note

#4259 Fix an issue when generating ExternalEntity from ExternalNode
  pkg/controller/externalnode/controller.go
  pkg/controller/externalnode/controller_test.go
Labels: action/release-note

#4251 Fix leak in resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go
  multicluster/controllers/multicluster/commonarea/clusterinfo_importer.go
  multicluster/controllers/multicluster/commonarea/clusterinfo_importer_test.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
Labels: kind/bug, area/multi-cluster

#4305 Fix data race in serviceexport_controller
  multicluster/controllers/multicluster/gateway_controller.go
  multicluster/controllers/multicluster/serviceexport_controller.go
Labels: kind/bug, area/multi-cluster, action/backport

#4296 Fix race condition in label_identity_controller
  multicluster/controllers/multicluster/label_identity_controller.go
Labels: kind/bug

#4126 Add OFSwitch connection check to Agent's liveness probes
  build/charts/antrea/templates/agent/daemonset.yaml
  build/images/scripts/container_liveness_probe
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_test.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/apiserver_test.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_bridge_test.go
Labels: action/backport, action/release-note

#4261 Enhance ACNP Service related feature
  pkg/agent/controller/networkpolicy/reject.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/service.go
  test/e2e/antreapolicy_test.go
  test/integration/agent/openflow_test.go
Labels: action/backport, action/release-note

#4313 Update Multi-cluster user guide about Gateway HA and antctl mc commands
  docs/antrea-ipam.md
  docs/multicluster/quick-start.md
  docs/multicluster/user-guide.md
Labels: kind/documentation, area/multi-cluster

#4303 Update Multi-cluster doc for Pod to Pod connectivity
  docs/multicluster/user-guide.md
Labels: area/multi-cluster

#4254 Add antcl mc commands to get/delete member token
  docs/multicluster/antctl.md
  pkg/antctl/antctl.go
  pkg/antctl/raw/multicluster/commands.go
  pkg/antctl/raw/multicluster/common/common.go
  pkg/antctl/raw/multicluster/common/common_test.go
  pkg/antctl/raw/multicluster/create/member_token.go
  pkg/antctl/raw/multicluster/create/member_token_test.go
  pkg/antctl/raw/multicluster/delete/member_token.go
  pkg/antctl/raw/multicluster/delete/member_token_test.go
  pkg/antctl/raw/multicluster/get/clusterset.go
  pkg/antctl/raw/multicluster/get/clusterset_test.go
  pkg/antctl/raw/multicluster/get/member_token.go
  pkg/antctl/raw/multicluster/get/member_token_test.go
  pkg/antctl/transform/clusterset/transform.go
  pkg/antctl/transform/membertoken/transform.go
Labels: area/multi-cluster

#3678 Add AppliedTo struct separately instead of sharing NetworkPolicyPeer
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go
  multicluster/controllers/multicluster/resourceexport_controller_test.go
  multicluster/controllers/multicluster/stale_controller_test.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/networkpolicy/antreanetworkpolicy.go
  pkg/controller/networkpolicy/antreanetworkpolicy_test.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/multicast_test.go
  test/e2e/traceflow_test.go
  test/e2e/utils/anp_spec_builder.go
  test/e2e/utils/cnp_spec_builder.go
Labels: area/network-policy

#4318 Set no-flood config with ports for TrafficControl after restarting
  pkg/agent/agent.go
Labels: action/backport, action/release-note

#4306 Fix nil pointer error when collecting agent supportbundle fails
  pkg/apiserver/registry/system/supportbundle/rest.go
  pkg/apiserver/registry/system/supportbundle/rest_test.go
Labels: action/backport, action/release-note

#4301 Update Multi-cluster user-guide about endpoint types
  docs/multicluster/quick-start.md
  docs/multicluster/user-guide.md
Labels: area/multi-cluster

#4319 Unify antctl mc commands help and error messages
  pkg/antctl/raw/featuregates/command.go
  pkg/antctl/raw/multicluster/common/cleanup.go
  pkg/antctl/raw/multicluster/common/cleanup_test.go
  pkg/antctl/raw/multicluster/common/common.go
  pkg/antctl/raw/multicluster/create/member_token.go
  pkg/antctl/raw/multicluster/create/member_token_test.go
  pkg/antctl/raw/multicluster/delete/member_token.go
  pkg/antctl/raw/multicluster/delete/member_token_test.go
  pkg/antctl/raw/multicluster/deploy/deploy_helper.go
  pkg/antctl/raw/multicluster/deploy/leader_cluster.go
  pkg/antctl/raw/multicluster/deploy/member_cluster.go
  pkg/antctl/raw/multicluster/destory_test.go
  pkg/antctl/raw/multicluster/destroy.go
  pkg/antctl/raw/multicluster/get/clusterset.go
  pkg/antctl/raw/multicluster/get/clusterset_test.go
  pkg/antctl/raw/multicluster/get/member_token.go
  pkg/antctl/raw/multicluster/get/resourceexport.go
  pkg/antctl/raw/multicluster/get/resourceexport_test.go
  pkg/antctl/raw/multicluster/get/resourceimport.go
  pkg/antctl/raw/multicluster/get/resourceimport_test.go
  pkg/antctl/raw/multicluster/init.go
  pkg/antctl/raw/multicluster/init_test.go
  pkg/antctl/raw/multicluster/join.go
  pkg/antctl/raw/multicluster/join_test.go
  pkg/antctl/raw/multicluster/leave.go
  pkg/antctl/raw/multicluster/leave_test.go
Labels: area/multi-cluster

#4316 Automated cherry pick of #4305: Fix data race in serviceexport_controller
  multicluster/controllers/multicluster/gateway_controller.go
  multicluster/controllers/multicluster/serviceexport_controller.go
Labels: kind/cherry-pick

#4315 Automated cherry pick of #4261: Enhance ACNP Service related feature
  pkg/agent/controller/networkpolicy/reject.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/service.go
  test/e2e/antreapolicy_test.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#4322 Automated cherry pick of #4318: Set no-flood config with ports for TrafficControl after
  pkg/agent/agent.go
Labels: kind/cherry-pick

#4321 Automated cherry pick of #4318: Set no-flood config with ports for TrafficControl after
  pkg/agent/agent.go
Labels: kind/cherry-pick

#4342 Fix wrong label normalization in stale_controller
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
Labels: kind/bug, area/multi-cluster
