Repository antrea-io/antrea, pull requests merged in 2022-03, with the labels that each got.

#3378 Automated cherry pick of #3360: Realize Egress for a Pod once its network is created
  cmd/antrea-agent/agent.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/status_controller_test.go
  pkg/agent/types/networkpolicy.go
  pkg/controller/egress/controller.go
  pkg/controller/egress/controller_test.go
  pkg/util/channel/channel.go
  pkg/util/channel/channel_test.go
  test/e2e/egress_test.go
  test/integration/agent/cniserver_test.go
Labels: kind/cherry-pick

#3383 Fix ipBlock referenced in nested ClusterGroup not processed correctly
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  test/e2e/antreapolicy_test.go
Labels: area/network-policy/controller, action/backport, action/release-note

#3371 Fix inability to access NodePort in particular case
  pkg/agent/flowexporter/connections/conntrack_linux_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/pipeline.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/ofctrl_flow_test.go
  pkg/ovs/openflow/ofctrl_nxfields.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/e2e/framework.go
  test/e2e/proxy_test.go
  test/integration/agent/openflow_test.go
  test/integration/ovs/ofctrl_test.go
Labels: action/backport, action/release-note

#3397 Automated cherry pick of #3371: Fix inability to access NodePort in particular case
  pkg/agent/flowexporter/connections/conntrack_linux_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_windows.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/ofctrl_flow_test.go
  pkg/ovs/openflow/ofctrl_nxfields.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/e2e/framework.go
  test/e2e/proxy_test.go
  test/integration/agent/openflow_test.go
  test/integration/ovs/ofctrl_test.go
Labels: kind/cherry-pick

#3407 Automated cherry pick of #3357: Integration test should check OpenFlow operations eventually
  test/integration/ovs/ofctrl_test.go
  test/integration/ovs/openflow_test_utils.go
Labels: kind/cherry-pick

#3405 Automated cherry pick of #3383: Fix ipBlock referenced in child ClusterGroup not processed
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  test/e2e/antreapolicy_test.go
Labels: kind/cherry-pick

#3406 Automated cherry pick of #3304: Fix AntreaNetworkPolicy e2e test random failures
  multicluster/test/e2e/framework.go
  test/e2e/k8s_util.go
Labels: kind/cherry-pick

#3393 Reduce permission of antrea service accounts
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-kind.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/controller-rbac.yml
  pkg/agent/agent.go
  pkg/agent/nodeportlocal/k8s/annotations.go
  pkg/agent/wireguard/client_linux.go
Labels: action/backport, action/release-note

#3408 Automated cherry pick of #3393: Reduce permission of antrea service accounts
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-kind.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/controller-rbac.yml
  pkg/agent/agent.go
  pkg/agent/nodeportlocal/k8s/annotations.go
  pkg/agent/wireguard/client_linux.go
Labels: kind/cherry-pick

#3411 Automated cherry pick of #3220: Upgrade default K8s version tested in eks
  ci/jenkins/README.md
  ci/test-conformance-eks.sh
Labels: kind/cherry-pick

#3421 Unconditionally sync CA cert for Controller webhooks
  pkg/apiserver/certificate/cacert_controller.go
Labels: kind/bug, action/release-note

#3391 Adding documentation for minikube
  docs/getting-started.md
  docs/kubernetes-installers.md
  docs/minikube.md
Labels: action/release-note

#3183 Support Pagination for ClusterGroupMembership
  pkg/apis/controlplane/register.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/register.go
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go
Labels: api-review, area/network-policy, action/release-note

#3430 Fix pkt mark conflict between HostLocalSourceMark and SNATIPMark
  pkg/agent/types/marks.go
  test/integration/agent/route_test.go
Labels: action/backport, action/release-note

#3425 Fix MC release build issue
  .github/workflows/build_tag.yml
  Makefile
  ci/jenkins/test-mc.sh
  docs/multicluster/getting-started.md
  multicluster/Makefile
  multicluster/build/images/Dockerfile
  multicluster/build/images/Dockerfile.build
Labels: area/multi-cluster, action/backport

#3413 Remove Kind-specific manifest and scripts
  .github/workflows/upload_release_assets.yml
  Makefile
  build/images/scripts/install_cni_kind
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-kind.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/patches/dev/onDeleteUpdateStrategy.yml
  build/yamls/patches/kind/README.md
  build/yamls/patches/kind/installCni.yml
  build/yamls/patches/kind/startAgent.yml
  build/yamls/patches/kind/startOvs.yml
  build/yamls/patches/kind/tunDevice.yml
  build/yamls/patches/kind/wireguardGo.yml
  ci/check-manifest.sh
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  ci/kind/test-upgrade-antrea.sh
  cmd/antrea-agent/options.go
  docs/kind.md
  hack/generate-manifest.sh
  hack/kind-fix-networking.sh
  hack/netpol-generator/test-kind.sh
  hack/netpol/test-kind.sh
  hack/release/prepare-assets.sh
  pkg/config/agent/config.go
  test/e2e/README.md
  test/e2e/antreapolicy_test.go
  test/e2e/bandwidth_test.go
  test/e2e/connectivity_test.go
  test/e2e/egress_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/ipsec_test.go
  test/e2e/k8s_util.go
  test/e2e/networkpolicy_test.go
  test/e2e/providers/kind.go
  test/e2e/proxy_test.go
  test/e2e/traceflow_test.go
  test/e2e/upgrade_test.go
  test/e2e/wireguard_test.go
Labels: action/release-note

#3459 Automated cherry pick of #3372: Move has-changes Github Action to is own repo #3445: Remove old has-changes Github Action code
  .github/workflows/benchmark.yml
  .github/workflows/build.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  ci/gh-actions/has-changes/Dockerfile
  ci/gh-actions/has-changes/README.md
  ci/gh-actions/has-changes/action.yml
  ci/gh-actions/has-changes/entrypoint.sh
Labels: kind/cherry-pick

#3458 Automated cherry pick of #3372: Move has-changes Github Action to is own repo #3445: Remove old has-changes Github Action code
  .github/workflows/benchmark.yml
  .github/workflows/build.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  ci/gh-actions/has-changes/Dockerfile
  ci/gh-actions/has-changes/README.md
  ci/gh-actions/has-changes/action.yml
  ci/gh-actions/has-changes/entrypoint.sh
Labels: kind/cherry-pick

#3456 Automated cherry pick of #3372: Move has-changes Github Action to is own repo #3445: Remove old has-changes Github Action code
  .github/workflows/build.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
  ci/gh-actions/has-changes/Dockerfile
  ci/gh-actions/has-changes/README.md
  ci/gh-actions/has-changes/action.yml
  ci/gh-actions/has-changes/entrypoint.sh
Labels: kind/cherry-pick

#3156 Fail in Agent initialization if GRE tunnel type is used with IPv6
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  docs/design/architecture.md
  docs/network-requirements.md
  docs/traffic-encryption.md
  pkg/agent/agent.go
Labels: area/transit/encapsulation, area/transit/ipv6, action/release-note

#3467 Fix duplicate IP case for NetworkPolicy
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
Labels: action/backport, action/release-note

#3475 Automated cherry pick of #3467: Fix duplicate IP case for NetworkPolicy
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
Labels: kind/cherry-pick

#3476 Automated cherry pick of #3467: Fix duplicate IP case for NetworkPolicy
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
Labels: kind/cherry-pick

#3389 [Multicast] Support IGMPv3 leave action
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/multicast/mcast_discovery.go
Labels: action/release-note

#3466 Update default image to vmware registry
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/hack/generate-manifest.sh
Labels: area/multi-cluster

#3155 Fix IPsec for IPv6 overlays
  build/images/ovs/apply-patches.sh
Labels: area/transit/encryption, action/release-note

#3485 Automated cherry pick of #3219: Add ignored interfaces names when getting interface by IP
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/serviceexternalip/controller.go
  pkg/agent/ipassigner/ip_assigner_linux.go
  pkg/agent/ipassigner/ip_assigner_windows.go
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
  test/integration/agent/ip_assigner_linux_test.go
  test/integration/agent/route_test.go
Labels: kind/cherry-pick

#3481 Automated cherry pick of #3430: Fix pkt mark conflict between HostLocalSourceMark and
  pkg/agent/types/marks.go
  test/integration/agent/route_test.go
Labels: kind/cherry-pick

#3341 Add [antctl mc] command for antrea multicluster resources
  pkg/antctl/antctl.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_definition_test.go
  pkg/antctl/command_list.go
  pkg/antctl/output/output.go
  pkg/antctl/raw/multicluster/commands.go
  pkg/antctl/raw/multicluster/get/output.go
  pkg/antctl/raw/multicluster/get/resourceimport.go
  pkg/antctl/raw/multicluster/scheme/scheme.go
  pkg/antctl/transform/resourceimport/transform.go
Labels: area/multi-cluster

#3454 Add SKIP_CNI_BINARIES env var to support skipping installing specified cni bins
  build/images/scripts/install_cni
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent.yml
Labels: action/release-note

#3314 [flexible-ipam] Fix IP leak issues
  pkg/agent/cniserver/ipam/antrea_ipam.go
  pkg/agent/cniserver/ipam/antrea_ipam_controller.go
Labels: action/release-note

#3496 Use upstream action for markdown link check
  .github/workflows/go.yml
Labels: area/test/infra

#3488 Use the correct mc controller image for e2e testing
  ci/jenkins/test-mc.sh
Labels: kind/bug, area/multi-cluster

#3436 Automated cherry pick of #3425: Fix MC release build issue
  .github/workflows/build_tag.yml
  Makefile
  ci/jenkins/test-mc.sh
  docs/multicluster/getting-started.md
  multicluster/Makefile
  multicluster/build/images/Dockerfile
  multicluster/build/images/Dockerfile.build
Labels: kind/cherry-pick

#3287 Antctl for multicluster
  pkg/antctl/raw/multicluster/commands.go
  pkg/antctl/raw/multicluster/get/clusterset.go
  pkg/antctl/raw/multicluster/get/resourceexport.go
  pkg/antctl/transform/clusterset/transform.go
  pkg/antctl/transform/resourceexport/transform.go
Labels: area/multi-cluster

#3363 Add ACNP copy span for multi-cluster
  ci/jenkins/test-mc.sh
  docs/multicluster/architecture.md
  docs/multicluster/getting-started.md
  multicluster/Makefile
  multicluster/apis/multicluster/v1alpha1/resourceexport_types.go
  multicluster/apis/multicluster/v1alpha1/resourceexport_webhook.go
  multicluster/apis/multicluster/v1alpha1/resourceimport_types.go
  multicluster/apis/multicluster/v1alpha1/zz_generated.deepcopy.go
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  multicluster/config/overlays/leader-ns/member_cluster_role.yaml
  multicluster/config/rbac/role.yaml
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_manager.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
  multicluster/controllers/multicluster/resourceexport_controller.go
  multicluster/controllers/multicluster/resourceexport_controller_test.go
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
  multicluster/controllers/multicluster/test_data.go
  pkg/apis/crd/v1alpha1/types.go
Labels: area/multi-cluster

#3511 Upgrade packaged Whereabouts version to v0.5.1
  build/images/base/Dockerfile
  build/images/base/Dockerfile.ubi
  hack/build-whereabouts.sh
Labels: area/dependency, area/build-release, action/release-note

#3404 Refine logs with upper case
  multicluster/apis/multicluster/v1alpha1/zz_generated.deepcopy.go
  multicluster/cmd/multicluster-controller/memberclusterannounce_webhook.go
  multicluster/controllers/multicluster/commonarea/common_area.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area.go
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/controllers/multicluster/leader_clusterset_controller.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/resourceexport_controller.go
  multicluster/controllers/multicluster/serviceexport_controller.go
Labels: area/multi-cluster

#3038 Add Node Selector in ACNP/ANP ingress/egress rules
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/crds.yml
  cmd/antrea-controller/controller.go
  docs/antrea-network-policy.md
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/antctl/command_definition_test.go
  pkg/antctl/transform/addressgroup/transform.go
  pkg/antctl/transform/appliedtogroup/transform.go
  pkg/antctl/transform/common/transform.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/egress/controller.go
  pkg/controller/grouping/group_entity_index_test.go
  pkg/controller/networkpolicy/antreanetworkpolicy_test.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/types/group.go
  pkg/util/k8s/node.go
  pkg/util/k8s/node_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/utils/cnpspecbuilder.go
Labels: action/release-note

#3513 Rename and update Antrea Multi-cluster user doc
  docs/multicluster/user-guide.md
  hack/.notableofcontents
Labels: area/multi-cluster

#3424 Share test functions between e2e and multicluster e2e package
  multicluster/test/e2e/fixtures.go
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
  test/e2e/antctl_test.go
  test/e2e/antreaipam_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/bandwidth_test.go
  test/e2e/basic_test.go
  test/e2e/batch_test.go
  test/e2e/connectivity_test.go
  test/e2e/egress_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/ipsec_test.go
  test/e2e/k8s_util.go
  test/e2e/main_test.go
  test/e2e/multicast_test.go
  test/e2e/networkpolicy_test.go
  test/e2e/nodeportlocal_test.go
  test/e2e/performance_test.go
  test/e2e/proxy_test.go
  test/e2e/service_externalip_test.go
  test/e2e/service_test.go
  test/e2e/supportbundle_test.go
  test/e2e/tls_test.go
  test/e2e/upgrade_test.go
  test/e2e/wireguard_test.go
Labels: area/test/e2e, area/multi-cluster

#3435 E2E test for MC ACNP copy-span
  ci/jenkins/test-mc.sh
  multicluster/test/e2e/antreapolicy_test.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
  multicluster/test/yamls/test-acnp-copy-span-ns-isolation.yml
  test/e2e/antreapolicy_test.go
  test/e2e/k8s_util.go
Labels: area/test/e2e, area/multi-cluster

#3491 Remove unnecessary CRDs and RBAC rules
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/config/default/kustomization.yaml
  multicluster/config/overlays/leader-global/crd_patch.yaml
  multicluster/config/overlays/leader-global/kustomization.yaml
  multicluster/config/overlays/leader-ns/kustomization.yaml
  multicluster/config/overlays/leader-ns/role.yaml
  multicluster/config/overlays/leader-ns/role_binding.yaml
  multicluster/config/overlays/leader-ns/service_account.yaml
  multicluster/config/overlays/member/additional_role_patch.yaml
  multicluster/config/overlays/member/crd_patch.yaml
  multicluster/config/overlays/member/kustomization.yaml
  multicluster/config/overlays/member/role.yaml
  multicluster/config/overlays/member/role_binding.yaml
  multicluster/config/overlays/member/service_account.yaml
  multicluster/config/rbac/kustomization.yaml
Labels: area/multi-cluster

#3519 Automated cherry pick of #3219: Add ignored interfaces names when getting interface by IP
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/config/node_config.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/ipassigner/ip_assigner_linux.go
  pkg/agent/controller/egress/ipassigner/ip_assigner_windows.go
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
  test/integration/agent/ip_assigner_linux_test.go
  test/integration/agent/route_test.go
Labels: kind/cherry-pick

#3374 Add upgrade guide for Multi-cluster
  docs/multicluster/api.md
  docs/multicluster/upgrade.md
  docs/multicluster/user-guide.md
  hack/.notableofcontents
Labels: area/multi-cluster, action/release-note

#3524 Update document for ServiceExternalIP feature
  docs/feature-gates.md
Labels: action/release-note

#3509 Graduate Egress feature from Alpha to Beta
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  build/yamls/base/conf/antrea-controller.conf
  cmd/antrea-agent/agent.go
  docs/egress.md
  docs/feature-gates.md
  pkg/agent/openflow/pipeline.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
  test/e2e/egress_test.go
Labels: action/release-note

#3499 Fix incorrect results by `antctl get networkpolicy` on Pods
  pkg/agent/apiserver/handlers/networkpolicy/handler.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/antctl/antctl.go
  pkg/querier/querier.go
Labels: kind/bug, area/component/antctl, action/release-note

#3414 Antctl multicluster Doc for antctl.md
  docs/antctl.md
  docs/multicluster/antctl.md
  hack/.notableofcontents
Labels: area/multi-cluster

#3526 Update generate-manifest-flow-aggregator.sh with new config
  ci/jenkins/README.md
  ci/test-flow-visibility.sh
  hack/generate-manifest-flow-aggregator.sh
Labels: area/flow-visibility, area/flow-visibility/aggregator

#3536 Fix stale service issue
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
Labels: area/multi-cluster

#3567 Use cache to reduce overall image build time
  ci/jenkins/test-mc.sh
Labels: area/multi-cluster

#3543 Fix integration test failure
  multicluster/test/integration/stale_controller_test.go
  multicluster/test/integration/suite_test.go
Labels: kind/failing-test, area/multi-cluster

#3564 Automated cherry pick of #3544: Declare Beta support for proxyAll
  CHANGELOG/CHANGELOG-1.6.md
Labels: kind/cherry-pick

#3565 Automated cherry pick of #3465: Remove stale ClusterIP routes after Antrea restart
  pkg/agent/route/route_linux.go
  test/e2e/basic_test.go
Labels: kind/cherry-pick
