Repository antrea-io/antrea, pull requests merged in 2022-07, with the labels that each got.

#3962 Automated cherry pick of #3948: Fix pkill failure in e2e test
  test/e2e/egress_test.go
  test/e2e/service_externalip_test.go
Labels: kind/cherry-pick

#3961 Automated cherry pick of #3948: Fix pkill failure in e2e test
  test/e2e/egress_test.go
  test/e2e/service_externalip_test.go
Labels: kind/cherry-pick

#3960 Automated cherry pick of #3948: Fix pkill failure in e2e test
  test/e2e/egress_test.go
  test/e2e/service_externalip_test.go
Labels: kind/cherry-pick

#3942 Upload Multi-cluster e2e coverage to codecov
  Makefile
  ci/jenkins/test-mc.sh
  ci/jenkins/test-vmc.sh
  multicluster/Makefile
  multicluster/build/images/Dockerfile.build.coverage
  multicluster/cmd/multicluster-controller/bincover_run_main_test.go
  multicluster/config/overlays/leader-ns/coverage/manager_command_patch_coverage.yaml
  multicluster/config/overlays/member/coverage/manager_command_patch_coverage.yaml
  multicluster/hack/generate-manifest.sh
Labels: area/multi-cluster

#3953 Fix egress e2e test
  pkg/agent/route/route_linux.go
  test/e2e/egress_test.go
Labels: action/backport

#3965 Use hostNetwork for Multi-cluster controller
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/config/manager/manager.yaml
Labels: area/multi-cluster

#3967 Release workflow: trigger website update after assets upload
  .github/workflows/process_release.yml
  .github/workflows/website.yml
  .github/workflows/website_release.yml
Labels: area/build-release

#3515 Support TopologyAwareHints in AntreaProxy
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/feature-gates.md
  pkg/agent/proxy/endpoints.go
  pkg/agent/proxy/endpointslicecache.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/topology.go
  pkg/agent/proxy/topology_test.go
  pkg/features/antrea_features.go
  third_party/proxy/config/config.go
  third_party/proxy/endpoints.go
  third_party/proxy/types.go
Labels: kind/feature, area/proxy, action/release-note

#3863 Multicluster E2E Test Refactoring
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
Labels: area/multi-cluster

#3969 Automated cherry pick of #3953: Fix egress e2e test
  pkg/agent/route/route_linux.go
  test/e2e/egress_test.go
Labels: kind/cherry-pick

#3970 Automated cherry pick of #3953: Fix egress e2e test
  pkg/agent/route/route_linux.go
  test/e2e/egress_test.go
Labels: kind/cherry-pick

#3971 Automated cherry pick of #3953: Fix egress e2e test
  pkg/agent/route/route_linux.go
  test/e2e/egress_test.go
Labels: kind/cherry-pick

#3973 Trigger "Update Helm index" workflow for releases
  .github/workflows/process_release.yml
  .github/workflows/website.yml
Labels: area/build-release

#3984 Automated cherry pick of #3942: Upload multi-cluster e2e coverage to codecov
  Makefile
  ci/jenkins/test-mc.sh
  ci/jenkins/test-vmc.sh
  multicluster/Makefile
  multicluster/build/images/Dockerfile.build.coverage
  multicluster/cmd/multicluster-controller/bincover_run_main_test.go
  multicluster/config/overlays/leader-ns/coverage/manager_command_patch_coverage.yaml
  multicluster/config/overlays/member/coverage/manager_command_patch_coverage.yaml
  multicluster/hack/generate-manifest.sh
Labels: kind/cherry-pick

#3938 [flexible-ipam] Use uplink interface name for host interface internal port
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/controller/trafficcontrol/controller.go
  pkg/agent/util/net.go
  pkg/agent/util/net_linux.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/ovs_schema.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/integration/ovs/ovs_client_test.go
Labels: action/backport

#3985 Reduce image building and unnecessary reruns
  .github/workflows/kind.yml
  .github/workflows/kind_upgrade.yml
Labels: area/test

#3991 Automated cherry pick of #3938: Use uplink interface name for host interface
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/controller/trafficcontrol/controller.go
  pkg/agent/util/net.go
  pkg/agent/util/net_linux.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/ovs_schema.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/integration/ovs/ovs_client_test.go
Labels: kind/cherry-pick

#3993 Fix apiVersion typo in the user-guide
  docs/multicluster/user-guide.md
Labels: area/multi-cluster

#3990 Fix Docker image tags for released Helm charts
  build/charts/antrea/Chart.yaml
  build/charts/antrea/README.md
  build/charts/antrea/templates/agent/daemonset.yaml
  build/charts/antrea/templates/controller/deployment.yaml
  build/charts/antrea/values.yaml
  build/charts/flow-aggregator/Chart.yaml
  build/charts/flow-aggregator/README.md
  build/charts/flow-aggregator/templates/deployment.yaml
  build/charts/flow-aggregator/values.yaml
Labels: kind/bug, area/build-release

#3989 Add documentation for Helm installation method
  docs/getting-started.md
  docs/helm.md
Labels: kind/documentation

#3975 Fix Pod-to-external traffic on EKS in policyOnly mode
  pkg/agent/route/route_linux.go
  pkg/agent/util/iptables/iptables.go
Labels: area/provider/aws, kind/bug, action/backport, action/release-note

#3999 Automated cherry pick of #3975: Fix Pod-to-external traffic on EKS in policyOnly mode
  pkg/agent/route/route_linux.go
  pkg/agent/util/iptables/iptables.go
Labels: kind/cherry-pick

#3647 [ci][flexible-ipam] Deliver K8s cluster when running flexible-ipam-e2e
  ci/jenkins/test.sh
Labels: action/backport

#4004 Automated cherry pick of #3994: Fix FlowExporter memory bloat when export process is dead
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
  pkg/agent/flowexporter/connections/deny_connections.go
  pkg/agent/flowexporter/connections/deny_connections_test.go
  pkg/agent/flowexporter/priorityqueue/priorityqueue.go
  pkg/agent/flowexporter/priorityqueue/priorityqueue_test.go
Labels: kind/cherry-pick

#4017 Automated cherry pick of #3670: Fix broken Markdown links check for main branch
  .github/workflows/go.yml
Labels: kind/cherry-pick

#4018 Automated cherry pick of #3670: Fix broken Markdown links check for main branch
  .github/workflows/go.yml
Labels: kind/cherry-pick

#4021 Update Prometheus dependencies
  build/yamls/antrea-prometheus-rbac.yml
  docs/prometheus-integration.md
  go.mod
  go.sum
  hack/make-metrics-doc.sh
  plugins/octant/go.mod
  plugins/octant/go.sum
Labels: area/dependency

#3964 Refactor Common Area and remove leader election
  go.mod
  multicluster/apis/multicluster/v1alpha1/clusterset_types.go
  multicluster/apis/multicluster/v1alpha1/clusterset_webhook.go
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/memberclusterannounce_webhook_test.go
  multicluster/config/crd/bases/multicluster.crd.antrea.io_clustersets.yaml
  multicluster/config/overlays/member/webhook_patch.yaml
  multicluster/config/webhook/manifests.yaml
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go
  multicluster/controllers/multicluster/commonarea/clusterinfo_importer_test.go
  multicluster/controllers/multicluster/commonarea/common_area.go
  multicluster/controllers/multicluster/commonarea/leader_elector.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area_manager.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area_wrapper.go
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_manager.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_manager_test.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_test.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
  multicluster/controllers/multicluster/gateway_controller_test.go
  multicluster/controllers/multicluster/leader_clusterset_controller.go
  multicluster/controllers/multicluster/leader_clusterset_controller_test.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/memberclusterannounce_controller.go
  multicluster/controllers/multicluster/memberclusterannounce_controller_test.go
  multicluster/controllers/multicluster/serviceexport_controller_test.go
  multicluster/controllers/multicluster/stale_controller_test.go
Labels: area/multi-cluster

#4012 Improve install_cni_chaining to support updates to CNI conf file
  build/charts/antrea/templates/agent/daemonset.yaml
  build/images/base/Dockerfile
  build/images/scripts/install_cni_chaining
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
Labels: area/provider/aws, area/provider/azure, action/backport, action/release-note

#4020 Remove dependency on github.com/satori/go.uuid module
  go.mod
  go.sum
  pkg/controller/networkpolicy/networkpolicy_controller.go
Labels: area/dependency

#3995 Set up Kind clusters to run multi-cluster e2e
  ci/jenkins/test-mc.sh
  multicluster/test/e2e/README.md
  multicluster/test/e2e/antreapolicy_test.go
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
Labels: area/multi-cluster

#4037 Fix Agent initialization for networkPolicyOnly mode
  pkg/agent/agent.go
Labels: kind/bug

#4025 Automated cherry pick of #3750: Update latest CI testbed to 1.24 and adjust related script
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#4024 Automated cherry pick of #3750: Update latest CI testbed to 1.24 and adjust related script
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#4026 Remove MemberClusterAnnounce if ClusterSet deleted
  docs/multicluster/quick-start.md
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/member_clusterset_controller_test.go
Labels: area/multi-cluster

#4043 Update ClusterSet and ClusterClaim webhooks
  multicluster/apis/multicluster/v1alpha2/clusterclaim_webhook.go
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/clusterset_webhook.go
  multicluster/cmd/multicluster-controller/clusterset_webhook_test.go
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/main.go
  multicluster/config/overlays/member/webhook_patch.yaml
  multicluster/config/webhook/manifests.yaml
Labels: area/multi-cluster

#4042 Use different CNI conf file when configuring chaining with Antrea
  build/images/scripts/install_cni_chaining
  build/yamls/antrea-aks-node-init.yml
  build/yamls/antrea-eks-node-init.yml
  build/yamls/antrea-gke-node-init.yml
Labels: area/provider/aws, area/provider/azure, action/release-note

#4016 Fix unit test flaky for IPsec controller
  pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go
Labels: action/backport

#4044 Automated cherry pick of #3802: Support K8s>=1.20
  ci/jenkins/test.sh
  test/e2e/service_test.go
Labels: kind/cherry-pick

#4045 Automated cherry pick of #3802: Support K8s>=1.20
  ci/jenkins/test.sh
  test/e2e/service_test.go
Labels: kind/cherry-pick

#3956 Auto update ClusterSet and MemberClusterAnnounce in leader cluster
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/memberclusterannounce_webhook.go
  multicluster/cmd/multicluster-controller/memberclusterannounce_webhook_test.go
  multicluster/config/overlays/leader-ns/role.yaml
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/memberclusterannounce_controller.go
  multicluster/controllers/multicluster/memberclusterannounce_controller_test.go
Labels: area/multi-cluster
