Repository antrea-io/antrea, pull requests merged in 2022-02, with the labels that each got.

#3256 Do not log error when Service for Endpoints is not found
  pkg/agent/controller/serviceexternalip/controller.go
Labels: action/release-note

#3282 Fix typo in CHANGELOG-1.5 and add a link for it
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/README.md
Labels: action/backport

#3290 Automated cherry pick of #3283: Fix markdownlint verification MD050/strong-style
  .github/workflows/go.yml
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#3291 Automated cherry pick of #3283: Fix markdownlint verification MD050/strong-style
  .github/workflows/go.yml
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#3292 Automated cherry pick of #3283: Fix markdownlint verification MD050/strong-style
  .github/workflows/go.yml
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#3293 Automated cherry pick of #3283: Fix markdownlint verification MD050/strong-style
  .github/workflows/go.yml
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#3266 Update label of antrea-mc-controller
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/config/manager/manager.yaml
  multicluster/config/prometheus/monitor.yaml
  multicluster/config/rbac/auth_proxy_service.yaml
  multicluster/config/webhook/service.yaml
Labels: area/multi-cluster

#3302 Automated cherry pick of #3282: Fix typo in CHANGELOG-1.5 and add a link for it
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/README.md
Labels: kind/cherry-pick

#3246 Use a smaller nginx image for multicluster e2e test
  ci/jenkins/test-mc.sh
  multicluster/test/e2e/framework.go
Labels: area/multi-cluster

#3305 Fix race condition in TestAggregatorCollectListGet unit test
  pkg/controller/stats/aggregator_test.go
Labels: area/test, kind/failing-test

#3276 Use iptables-wrapper in Antrea container
  build/images/base/Dockerfile
Labels: kind/bug, action/backport, action/release-note

#3308 Automated cherry pick of #3276: Use iptables-wrapper in Antrea container
  build/images/base/Dockerfile
Labels: kind/cherry-pick

#3310 Automated cherry pick of #3276: Use iptables-wrapper in Antrea container
  build/images/base/Dockerfile
Labels: kind/cherry-pick

#3309 Automated cherry pick of #3276: Use iptables-wrapper in Antrea container
  build/images/base/Dockerfile
Labels: kind/cherry-pick

#3311 Automated cherry pick of #3276: Use iptables-wrapper in Antrea container
  build/images/base/Dockerfile
Labels: kind/cherry-pick

#3295 Fix NodePort/LoadBalancer issue when proxyAll is enabled
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  test/e2e/framework.go
  test/e2e/proxy_test.go
Labels: action/backport, action/release-note

#3277 Add Port Number to Audit Logging
  docs/antrea-network-policy.md
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/agent/controller/networkpolicy/audit_logging_test.go
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/controller/networkpolicy/packetin_test.go
  pkg/ovs/openflow/ofctrl_packetin_test.go
  test/e2e/antreapolicy_test.go
Labels: area/network-policy, action/release-note

#3329 Automated cherry pick of #3295: Fix NodePort/LoadBalancer issue when proxyAll is enabled
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  test/e2e/framework.go
  test/e2e/proxy_test.go
Labels: kind/cherry-pick

#3331 Validate labels in ANP/ACNP/CG
  pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
Labels: action/release-note

#3322 Add document for Service of type LoadBalancer
  docs/service-loadbalancer.md
Labels: kind/documentation

#3350 Remove --k8s-1.15 flag from hack/generate-manifest.sh
  build/yamls/patches/legacy/controller.json
  build/yamls/patches/legacy/crdClusterInformation.json
  build/yamls/patches/legacy/crdClusterNetworkPolicy.json
  build/yamls/patches/legacy/crdExternalEntity.json
  build/yamls/patches/legacy/crdNetworkPolicy.json
  build/yamls/patches/legacy/crdTier.json
  build/yamls/patches/legacy/crdTraceflow.json
  build/yamls/patches/legacy/crdVersion.json
  hack/generate-manifest.sh
Labels: area/build-release, action/release-note

#3335 Fix dumping OVS flows of a NetworkPolicy
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
Labels: action/release-note

#3356 Add a per-rule example for NetworkpolicyStats docs
  docs/feature-gates.md
Labels: kind/documentation

#3297 Add an agent config parameter for enabling flexible IPAM (bridging mode)
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-kind.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_windows.go
  hack/generate-manifest.sh
  pkg/agent/agent_linux.go
  pkg/agent/agent_windows.go
  pkg/config/agent/config.go
Labels: area/ipam

#3303 Limit resource kinds in ResourceExport controller
  multicluster/controllers/multicluster/resourceexport_controller.go
Labels: area/multi-cluster

#3359 Add clusterID annotation to ServiceExport/Import
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
  multicluster/controllers/multicluster/serviceexport_controller.go
  multicluster/controllers/multicluster/serviceexport_controller_test.go
Labels: area/multi-cluster
