Repository antrea-io/antrea, pull requests merged in 2022-01, with the labels that each got.

#3173 Do not override global RUN_E2E_SKIP in e2e script
  ci/run-k8s-e2e-tests.sh
Labels: area/test/infra

#3136 Fix the AddressGroup duplicated deleted bug
  pkg/controller/networkpolicy/networkpolicy_controller.go
Labels: area/network-policy/controller

#3134 Add retry to update NetworkPolicy status
  pkg/controller/networkpolicy/status_controller.go
Labels: area/network-policy

#3153 Rename package 'core' to 'commonarea'
  multicluster/Makefile
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/config/crd/k8smcs/multicluster.x-k8s.io_serviceexports.yaml
  multicluster/config/crd/k8smcs/multicluster.x-k8s.io_serviceimports.yaml
  multicluster/config/crd/kustomization.yaml
  multicluster/controllers/multicluster/commonarea/common_area.go
  multicluster/controllers/multicluster/commonarea/fake_remote_common_area.go
  multicluster/controllers/multicluster/commonarea/leader_elector.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area_manager.go
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_manager.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_manager_test.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_test.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/serviceexport_controller.go
  multicluster/controllers/multicluster/serviceexport_controller_test.go
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
Labels: area/multi-cluster

#3175 Add reason field in antctl traceflow command output
  pkg/antctl/raw/traceflow/command.go
Labels: area/component/antctl

#3130 Make externalIP proxying configurable for AntreaProxy
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-kind.yml
  build/yamls/antrea.yml
  build/yamls/base/conf/antrea-agent.conf
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/config/agent/config.go
Labels: area/proxy

#3177 Fix leader eletion timeout issue
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/options.go
  multicluster/config/default/configmap/controller_manager_config.yaml
Labels: area/multi-cluster

#3180 Allow member and leader deployed in one cluster
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/member.go
  multicluster/config/overlays/member/kustomization.yaml
  multicluster/config/overlays/member/webhook_patch.yaml
  multicluster/controllers/multicluster/member_clusterset_controller.go
Labels: area/multi-cluster

#3124 Add E2E test for antrea multiclusters
  ci/jenkins/test-mc.sh
  ci/jenkins/test.sh
  multicluster/test/e2e/README.md
  multicluster/test/e2e/fixtures.go
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
  multicluster/test/e2e/util.go
  multicluster/test/yamls/clusterset.yml
  multicluster/test/yamls/east-member-cluster.yml
  multicluster/test/yamls/leader-access-token-secret.yml
  multicluster/test/yamls/test-east-serviceexport.yml
  multicluster/test/yamls/test-west-serviceexport.yml
  multicluster/test/yamls/west-member-cluster.yml
Labels: area/multi-cluster

#3032 add multi-cluster docs
  docs/multicluster/architecture.md
  docs/multicluster/assets/basic-topology.png
  docs/multicluster/assets/resource-export-import-pipeline.png
  docs/multicluster/getting-started.md
  hack/.notableofcontents
  multicluster/config/samples/multicluster_v1_serviceexports.yaml
  multicluster/config/samples/multicluster_v1_serviceimports.yaml
  multicluster/config/samples/multicluster_v1alpha1_clusterclaim.yaml
  multicluster/config/samples/multicluster_v1alpha1_clusterset.yaml
  multicluster/config/samples/multicluster_v1alpha1_resourceexport.yaml
  multicluster/config/samples/multicluster_v1alpha1_resourceimport.yaml
Labels: area/multi-cluster

#3227 Add ServiceExternalIP feature gate to documentation
  docs/feature-gates.md
Labels: kind/documentation

#3231 Automated cherry pick of #3227: Add ServiceExternalIP feature gate to documentation
  docs/feature-gates.md
Labels: kind/cherry-pick

#3218 Document Docker Desktop alternatives for contributors
  CONTRIBUTING.md
  docs/contributors/docker-desktop-alternatives.md
  hack/.notableofcontents
Labels: kind/documentation

#3237 Automated cherry pick of #2672: Convert NodeName obtained from env var to lowercase on
  pkg/util/env/env.go
Labels: kind/cherry-pick

#3248 Log Pod status when waiting for Pod condition fails
  test/e2e/framework.go
Labels: area/test/e2e

#3259 Automated cherry pick of #3162: Recover integration test by skipping certificate check
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#3260 Automated cherry pick of #3162: Recover integration test by skipping certificate check
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#3252 Automated cherry pick of #3176: Migrate VMC jenkins testbed to private VC
  ci/cluster-api/vsphere/templates/cluster.yaml
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/test-vmc.sh
  ci/run-k8s-e2e-tests.sh
Labels: kind/cherry-pick

#3261 Automated cherry pick of #3162: Recover integration test by skipping certificate check
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#3253 Automated cherry pick of #3176: Migrate VMC jenkins testbed to private VC
  ci/cluster-api/vsphere/templates/cluster.yaml
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/test-vmc.sh
  ci/run-k8s-e2e-tests.sh
Labels: kind/cherry-pick

#3238 Automated cherry pick of #3169: Fix agent initialization error by adjusting
  pkg/agent/util/net_windows.go
Labels: kind/cherry-pick

#3254 Automated cherry pick of #3176: Migrate VMC jenkins testbed to private VC
  ci/cluster-api/vsphere/templates/cluster.yaml
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
  ci/jenkins/test-vmc.sh
  ci/run-k8s-e2e-tests.sh
Labels: kind/cherry-pick

#3240 Automated cherry pick of #3169: Fix agent initialization error by adjusting
  pkg/agent/util/net_windows.go
Labels: kind/cherry-pick

#3239 Automated cherry pick of #3169: Fix agent initialization error by adjusting
  pkg/agent/util/net_windows.go
Labels: kind/cherry-pick

#3101 Automated cherry pick of #3083: Fix NetworkPolicy resources dump for Agent's supportbundle
  pkg/apis/controlplane/v1beta2/marshal.go
  pkg/support/dump.go
Labels: kind/cherry-pick

#3264 Add powershell command replacement in windows doc
  docs/windows.md
Labels: kind/documentation

#3086 Automated cherry pick of #3074: Fix status report of Antrea-native policies
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  test/e2e/antreapolicy_test.go
Labels: kind/cherry-pick

#3085 Automated cherry pick of #3074: Fix status report of Antrea-native policies
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  test/e2e/antreapolicy_test.go
Labels: kind/cherry-pick

#3241 Automated cherry pick of #2768: Fix triggerCNPUpdates panic
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: kind/cherry-pick

#3268 Automated cherry pick of #3079: Fix typo in antrea-network-policy doc
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#3269 Automated cherry pick of #3079: Fix typo in antrea-network-policy doc
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#3270 Automated cherry pick of #3079: Fix typo in antrea-network-policy doc
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#3154 Install cni conf after installing cni bins
  build/images/scripts/install_cni
Labels: action/release-note

#3275 Clarify in NPL doc that nodeportlocal.antrea.io is not for users
  docs/node-port-local.md
Labels: kind/documentation, area/proxy/nodeportlocal

#3114 Ignore Services of type ExternalName in NodePortLocal Controller
  pkg/agent/nodeportlocal/k8s/npl_controller.go
Labels: area/proxy/nodeportlocal, action/release-note
