Repository antrea-io/antrea, pull requests merged in 2022-05, with the labels that each got.

#3725 Fix Fluentd Cookbook Links
  docs/cookbooks/fluentd/README.md
Labels: kind/documentation

#3722 Add multi-cluster and Service LB doc links
  docs/design/architecture.md
  docs/getting-started.md
  docs/multicluster/architecture.md
Labels: kind/documentation

#3672 Implement garbage collector for IP Pools
  pkg/controller/ipam/antrea_ipam_controller.go
  pkg/controller/ipam/antrea_ipam_controller_test.go
Labels: kind/cleanup, action/release-note

#3719 Automated cherry pick of #3694: Document some of the Antrea Agent RBAC permissions
  docs/security.md
Labels: kind/cherry-pick

#3508 [Multicast] Use group as flow actions for multicast traffic
  cmd/antrea-agent/agent.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/multicast/mcast_discovery.go
  pkg/agent/multicast/mcast_route_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/framework.go
  pkg/agent/openflow/multicast.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/types/event.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/testing/mock_openflow.go
  pkg/util/channel/channel.go
  pkg/util/channel/channel_test.go
  test/e2e/multicast_test.go
  test/integration/agent/openflow_test.go
  test/integration/ovs/ofctrl_test.go
Labels: action/release-note

#3730 No longer assume that K8s creates a token for all ServiceAccounts
  CONTRIBUTING.md
  build/charts/antrea/templates/agent/secret.yaml
  build/charts/antrea/templates/antctl/secret.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-prometheus.yml
  build/yamls/antrea.yml
  docs/configuration.md
  docs/contributors/manual-installation.md
  docs/getting-started.md
  docs/troubleshooting.md
  hack/.notableofcontents
  hack/windows/Helper.psm1
  test/e2e/prometheus_test.go
Labels: action/release-note

#3691 Reduce permission of antrea-agent service account
  build/charts/antrea/templates/agent/clusterrole.yaml
  build/charts/antrea/templates/antctl/clusterrole.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/serviceexternalip/handler.go
  pkg/agent/controller/serviceexternalip/controller.go
  pkg/agent/controller/serviceexternalip/controller_test.go
  pkg/antctl/antctl.go
  pkg/querier/querier.go
  test/e2e/antctl_test.go
  test/e2e/service_externalip_test.go
Labels: kind/cleanup, action/backport, action/release-note

#3748 Automated cherry pick of #3661: Replace busybox source to fix image errors
  test/e2e/framework.go
Labels: kind/cherry-pick

#3747 Automated cherry pick of #3661: Replace busybox source to fix image errors
  test/e2e/framework.go
Labels: kind/cherry-pick

#3746 Automated cherry pick of #3731: Fix tolerations for Kubernetes >= 1.24
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/controller.yml
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
  test/e2e/performance_test.go
Labels: kind/cherry-pick

#3743 Automated cherry pick of #3691: Reduce permission of antrea-agent service account
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/antctl.yml
  cmd/antrea-agent/agent.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/serviceexternalip/handler.go
  pkg/agent/controller/serviceexternalip/controller.go
  pkg/agent/controller/serviceexternalip/controller_test.go
  pkg/antctl/antctl.go
  pkg/querier/querier.go
  test/e2e/antctl_test.go
  test/e2e/service_externalip_test.go
Labels: kind/cherry-pick

#3745 Automated cherry pick of #3731: Fix tolerations for Kubernetes >= 1.24
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-kind.yml
  build/yamls/antrea.yml
  build/yamls/base/controller.yml
  test/e2e/framework.go
  test/e2e/networkpolicy_test.go
  test/e2e/performance_test.go
Labels: kind/cherry-pick

#3749 Automated cherry pick of #3691: Reduce permission of antrea-agent service account
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-kind.yml
  build/yamls/antrea.yml
  build/yamls/base/agent-rbac.yml
  build/yamls/base/antctl.yml
  cmd/antrea-agent/agent.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/serviceexternalip/handler.go
  pkg/agent/controller/serviceexternalip/controller.go
  pkg/agent/controller/serviceexternalip/controller_test.go
  pkg/antctl/antctl.go
  pkg/querier/querier.go
  test/e2e/antctl_test.go
  test/e2e/service_externalip_test.go
Labels: kind/cherry-pick

#3739 Automated cherry pick of #3728: Fix identification of control-plane Node in e2e test
  test/e2e/framework.go
Labels: kind/cherry-pick

#3740 Automated cherry pick of #3728: Fix identification of control-plane Node in e2e test
  test/e2e/framework.go
Labels: kind/cherry-pick

#3738 Remove ELK Flow Collector
  build/yamls/elk-flow-collector/elk-flow-collector.yml
  build/yamls/elk-flow-collector/kibana.ndjson
  build/yamls/elk-flow-collector/logstash/filter.rb
  build/yamls/elk-flow-collector/logstash/ipfix.yml
  build/yamls/elk-flow-collector/logstash/logstash.conf
  build/yamls/elk-flow-collector/logstash/logstash.yml
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects.yaml
  ci/test-elk-flow-collector.sh
  docs/assets/README.md
  docs/assets/flow_visibility.svg
  docs/contributors/github-labels.md
  docs/network-flow-visibility.md
  test/e2e/infra/vagrant/Vagrantfile
  test/e2e/infra/vagrant/provision.sh
  test/e2e/infra/vagrant/push_antrea.sh
Labels: area/flow-visibility, action/release-note

#3773 Automated cherry pick of #3771: Fix GKE test
  ci/test-conformance-gke.sh
Labels: kind/cherry-pick

#3774 Automated cherry pick of #3771: Fix GKE test
  ci/test-conformance-gke.sh
Labels: kind/cherry-pick

#3772 Fix e2e and integration bug
  multicluster/test/e2e/antreapolicy_test.go
  multicluster/test/e2e/service_test.go
  multicluster/test/integration/suite_test.go
Labels: area/multi-cluster

#3782 Automated cherry pick of #3779: Fix image loading in GKE
  ci/test-conformance-gke.sh
Labels: kind/cherry-pick

#3780 Tolerate unset SKIP_CNI_BINARIES env var
  build/images/scripts/install_cni
Labels: kind/cleanup

#3788 Update ROADMAP doc
  ROADMAP.md
Labels: kind/documentation

#3354 [Multicast] Add Multicast statistics API
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apis/stats/register.go
  pkg/apis/stats/types.go
  pkg/apis/stats/v1alpha1/generated.pb.go
  pkg/apis/stats/v1alpha1/generated.proto
  pkg/apis/stats/v1alpha1/register.go
  pkg/apis/stats/v1alpha1/types.go
  pkg/apis/stats/v1alpha1/zz_generated.conversion.go
  pkg/apis/stats/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/stats/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/client/clientset/versioned/typed/stats/v1alpha1/fake/fake_multicastgroup.go
  pkg/client/clientset/versioned/typed/stats/v1alpha1/fake/fake_stats_client.go
  pkg/client/clientset/versioned/typed/stats/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/stats/v1alpha1/multicastgroup.go
  pkg/client/clientset/versioned/typed/stats/v1alpha1/stats_client.go
Labels: api-review, kind/api-change, action/release-note

#3807 [multicast] fix the issue multicast does not work if antreaPolicy is disabled
  cmd/antrea-agent/agent.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/packetin.go
  pkg/agent/openflow/testing/mock_openflow.go
Labels: action/release-note

#3811 Clean up stale images and fix e2e codes
  ci/jenkins/test-mc.sh
  ci/jenkins/test.sh
  multicluster/test/e2e/antreapolicy_test.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
Labels: area/multi-cluster

#3810 Stop using k8s.io/component-base/logs to configure logging
  cmd/antctl/main.go
  cmd/antrea-agent-simulator/main.go
  cmd/antrea-agent/main.go
  cmd/antrea-controller/main.go
  cmd/flow-aggregator/main.go
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/main.go
  multicluster/cmd/multicluster-controller/member.go
  pkg/antctl/antctl_test.go
  pkg/antctl/command_list.go
  pkg/log/log.go
  pkg/log/log_file.go
  pkg/log/log_file_test.go
Labels: area/monitoring/logging

#3801 Change deny connections IP address assignment methods
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/openflow/packetin.go
Labels: kind/bug, area/flow-visibility/exporter

#3463 Add Gateway, ClusterInfo exchange controllers
  multicluster/cmd/multicluster-controller/member.go
  multicluster/cmd/multicluster-controller/options.go
  multicluster/config/crd/bases/multicluster.crd.antrea.io_gateway.yaml
  multicluster/config/crd/patches/webhook_in_gatewaynodes.yaml
  multicluster/config/rbac/gateway_editor_role.yaml
  multicluster/config/rbac/gateway_viewer_role.yaml
  multicluster/controllers/multicluster/clusterinfoexport_handler.go
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go
  multicluster/controllers/multicluster/commonarea/clusterinfo_importer.go
  multicluster/controllers/multicluster/commonarea/clusterinfo_importer_test.go
  multicluster/controllers/multicluster/commonarea/fake_remote_common_area.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area.go
  multicluster/controllers/multicluster/commonarea/mock_remote_common_area_manager.go
  multicluster/controllers/multicluster/commonarea/remote_common_area.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_manager.go
  multicluster/controllers/multicluster/commonarea/remote_common_area_manager_test.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller.go
  multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
  multicluster/controllers/multicluster/controller_utils.go
  multicluster/controllers/multicluster/gateway_controller.go
  multicluster/controllers/multicluster/gateway_controller_test.go
  multicluster/controllers/multicluster/leader_clusterset_controller.go
  multicluster/controllers/multicluster/member_clusterset_controller.go
  multicluster/controllers/multicluster/node_controller.go
  multicluster/controllers/multicluster/node_controller_test.go
  multicluster/controllers/multicluster/resourceexport_controller.go
  multicluster/controllers/multicluster/resourceexport_controller_test.go
  multicluster/controllers/multicluster/serviceexport_controller.go
  multicluster/controllers/multicluster/serviceexport_controller_test.go
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
  multicluster/controllers/multicluster/test_data.go
  multicluster/test/e2e/service_test.go
  multicluster/test/integration/stale_controller_test.go
  multicluster/test/integration/suite_test.go
Labels: kind/api-change, kind/feature, area/multi-cluster, action/release-note

#3814 Update architecture doc for IPAM, Prometheus, and README for features
  README.md
  docs/design/architecture.md
Labels: kind/documentation

#3802 [e2e] Support K8s>=1.20
  ci/jenkins/test.sh
  test/e2e/service_test.go
Labels: action/backport

#3506 Create different namespaces for different e2e tests
  cmd/antrea-agent/agent.go
  multicluster/test/e2e/antreapolicy_test.go
  test/e2e/antreaipam_service_test.go
  test/e2e/antreaipam_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/bandwidth_test.go
  test/e2e/basic_test.go
  test/e2e/batch_test.go
  test/e2e/clustergroup_test.go
  test/e2e/connectivity_test.go
  test/e2e/egress_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/k8s_util.go
  test/e2e/multicast_test.go
  test/e2e/networkpolicy_test.go
  test/e2e/nodeportlocal_test.go
  test/e2e/performance_test.go
  test/e2e/providers/exec/docker.go
  test/e2e/proxy_test.go
  test/e2e/service_externalip_test.go
  test/e2e/service_test.go
  test/e2e/traceflow_test.go
  test/e2e/upgrade_test.go
  test/e2e/wireguard_test.go
Labels: area/test/e2e

#3832 Make disabling TX checksum offload configurable
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  pkg/config/agent/config.go
  test/integration/agent/cniserver_test.go
Labels: action/release-note

#3812 Limit max data values of Grafana panels
  build/yamls/flow-visibility.yml
  build/yamls/flow-visibility/base/provisioning/dashboards/flow_records_dashboard.json
  build/yamls/flow-visibility/base/provisioning/dashboards/networkpolicy_allow_dashboard.json
  build/yamls/flow-visibility/base/provisioning/dashboards/node_to_node_dashboard.json
  build/yamls/flow-visibility/base/provisioning/dashboards/pod_to_external_dashboard.json
  build/yamls/flow-visibility/base/provisioning/dashboards/pod_to_pod_dashboard.json
  build/yamls/flow-visibility/base/provisioning/dashboards/pod_to_service_dashboard.json
  docs/network-flow-visibility.md
Labels: area/flow-visibility

#3839 Improve unit tests
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/antctl/raw/traceflow/command_test.go
Labels: area/test

#3833 Fix inconsistent namespaces used in Flow Aggregator e2e test
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: area/test/e2e

#3778 Support IPsec Certificate-based Authentication
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/conf/antrea-controller.conf
  build/charts/antrea/templates/agent/clusterrole.yaml
  build/charts/antrea/templates/agent/daemonset.yaml
  build/charts/antrea/templates/controller/clusterrole.yaml
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-controller/controller.go
  cmd/antrea-controller/options.go
  pkg/agent/agent.go
  pkg/agent/config/ipsec_authentication_mode.go
  pkg/agent/config/node_config.go
  pkg/agent/controller/ipseccertificate/ipsec_certificate_controller.go
  pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
  pkg/agent/interfacestore/types.go
  pkg/apis/certificates.go
  pkg/config/agent/config.go
  pkg/config/controller/config.go
  pkg/controller/certificatesigningrequest/approving_controller.go
  pkg/controller/certificatesigningrequest/approving_controller_test.go
  pkg/controller/certificatesigningrequest/common.go
  pkg/controller/certificatesigningrequest/ipsec_csr_approver.go
  pkg/controller/certificatesigningrequest/ipsec_csr_approver_test.go
  pkg/controller/certificatesigningrequest/ipsec_csr_signing_controller.go
  pkg/controller/certificatesigningrequest/ipsec_csr_signing_controller_test.go
  pkg/features/antrea_features.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/e2e/ipsec_test.go
  test/integration/ovs/ovs_client_test.go
Labels: action/release-note

#3453 Support NodePortLocal on Antrea Windows Agent and Update NPL annotation
  build/yamls/antrea-windows.yml
  build/yamls/windows/base/conf/antrea-agent.conf
  docs/node-port-local.md
  pkg/agent/nodeportlocal/k8s/annotations.go
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/npl_agent_init.go
  pkg/agent/nodeportlocal/npl_agent_init_windows.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/portcache/port_table_linux.go
  pkg/agent/nodeportlocal/portcache/port_table_test.go
  pkg/agent/nodeportlocal/portcache/port_table_windows.go
  pkg/agent/nodeportlocal/rules/iptable_rule.go
  pkg/agent/nodeportlocal/rules/netnat_rule.go
  pkg/agent/nodeportlocal/rules/rules.go
  pkg/agent/nodeportlocal/rules/types.go
  pkg/agent/nodeportlocal/testing/annotations.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/route/route_windows.go
  pkg/agent/util/net.go
  pkg/agent/util/net_windows.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
  test/e2e/framework.go
  test/e2e/nodeportlocal_test.go
Labels: area/proxy/nodeportlocal, action/release-note

#3837 Fix Egress not working with kube-proxy IPVS strictARP mode
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/ipassigner/ip_assigner.go
  pkg/agent/ipassigner/ip_assigner_linux.go
  pkg/agent/ipassigner/ip_assigner_windows.go
  pkg/agent/ipassigner/testing/mock_ipassigner.go
  test/integration/agent/ip_assigner_linux_test.go
Labels: action/backport, action/release-note

#3836 Clean unused multicluster CRDs and dead codes
  multicluster/PROJECT
  multicluster/apis/multicluster/v1alpha1/resourceexportfilter_types.go
  multicluster/apis/multicluster/v1alpha1/resourceimportfilter_types.go
  multicluster/apis/multicluster/v1alpha1/zz_generated.deepcopy.go
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexportfilters.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimportfilters.yaml
  multicluster/config/crd/kustomization.yaml
  multicluster/config/crd/patches/webhook_in_resourceexportfilters.yaml
  multicluster/config/crd/patches/webhook_in_resourceimportfilters.yaml
  multicluster/config/overlays/leader-ns/role.yaml
  multicluster/config/overlays/member/role.yaml
  multicluster/config/rbac/resourceexportfilter_editor_role.yaml
  multicluster/config/rbac/resourceexportfilter_viewer_role.yaml
  multicluster/config/rbac/resourceimportfilter_editor_role.yaml
  multicluster/config/rbac/resourceimportfilter_viewer_role.yaml
  multicluster/config/rbac/role.yaml
  multicluster/config/samples/multicluster_v1alpha1_resourceexportfilter.yaml
  multicluster/config/samples/multicluster_v1alpha1_resourceimportfilter.yaml
  multicluster/controllers/multicluster/resourceexportfilter_controller.go
  multicluster/controllers/multicluster/resourceimportfilter_controller.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_multicluster_client.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_resourceexportfilter.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/fake/fake_resourceimportfilter.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/generated_expansion.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/multicluster_client.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/resourceexportfilter.go
  multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1/resourceimportfilter.go
  multicluster/pkg/client/informers/externalversions/generic.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/interface.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/resourceexportfilter.go
  multicluster/pkg/client/informers/externalversions/multicluster/v1alpha1/resourceimportfilter.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/expansion_generated.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/resourceexportfilter.go
  multicluster/pkg/client/listers/multicluster/v1alpha1/resourceimportfilter.go
Labels: area/multi-cluster

#3840 Add support for containerd to antrea-eks-node-init.yml
  build/yamls/antrea-eks-node-init.yml
  ci/test-conformance-eks.sh
Labels: area/provider/aws, action/release-note
