Repository antrea-io/antrea, pull requests merged in 2023-12, with the labels that each got.

#5766 Add Talos to the K8s installers document
  docs/kubernetes-installers.md
Labels: kind/documentation, action/release-note

#5436 Document Egress feature's options and usage on cloud
  docs/egress.md
Labels: kind/documentation, area/transit/egress

#5783 Fix Endpoint Querier RuleIndex In Response
  pkg/controller/networkpolicy/endpoint_querier.go
  pkg/controller/networkpolicy/endpoint_querier_test.go
Labels: kind/bug, action/release-note

#5777 Enable Pod network after realizing initial NetworkPolicies
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/util/wait/wait.go
  pkg/util/wait/wait_test.go
  test/e2e/networkpolicy_test.go
  test/integration/agent/cniserver_test.go
Labels: action/backport, action/release-note

#5788 Delete OVS port and flows before releasing Pod IP
  pkg/agent/cniserver/ipam/ipam_service.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux_test.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/cniserver/server_windows_test.go
  pkg/agent/cniserver/testing/utils.go
Labels: action/release-note

#5795 Support Local ExternalTrafficPolicy for Services with ExternalIPs
  pkg/agent/proxy/proxier_test.go
  third_party/proxy/util/service.go
Labels: area/proxy, action/backport, action/release-note

#5806 Update actions/upload-artifact and actions/download-artifact together
  .github/dependabot.yml
  .github/workflows/conformance.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
  .github/workflows/trivy_scan.yml
Labels: area/dependency, dependencies

#5816 Update workflow description for the input parameters
  .github/workflows/docker_update_base_windows.yml
Labels: size/XS

#5716 Add Controlplane changes for NodeNetworkPolicy
  build/charts/antrea/crds/clusternetworkpolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  pkg/apis/crd/v1beta1/types.go
  pkg/apis/crd/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/networkpolicy/adminnetworkpolicy.go
  pkg/controller/networkpolicy/antreanetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: area/network-policy, action/release-note
