Repository antrea-io/antrea, pull requests merged in 2023-09, with the labels that each got.

#5468 Automated cherry pick of #5184: Update sonobuoy version to v0.56.16
  ci/run-k8s-e2e-tests.sh
  ci/verify-sonobuoy.sh
Labels: kind/cherry-pick

#5471 Update Multi-cluster docs with more details
  docs/multicluster/quick-start.md
  docs/multicluster/user-guide.md
  docs/traffic-encryption.md
Labels: area/multi-cluster

#5477 Update Prometheus metrics doc
  docs/prometheus-integration.md
Labels: area/monitoring/metrics

#5473 Automated cherry pick of #5280: Sonobuoy e2e tests Enhancement
  ci/jenkins/test.sh
  ci/run-k8s-e2e-tests.sh
Labels: kind/cherry-pick

#5475 Add a ClusterSet deletion webhook for the leader cluster
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-leader.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/clusterset_webhook.go
  multicluster/cmd/multicluster-controller/clusterset_webhook_test.go
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/config/webhook/manifests.yaml
Labels: area/multi-cluster

#5503 Fix typo: s/enableFLowExporter/enableFlowExporter
  cmd/antrea-agent/agent.go
Labels: size/XS

#5495 Do not apply Egress to traffic destined for ServiceCIDRs
  cmd/antrea-agent/agent.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/servicecidr/discoverer.go
  pkg/agent/servicecidr/discoverer_test.go
  pkg/agent/servicecidr/testing/mock_servicecidr.go
Labels: area/transit/egress, action/backport, action/release-note

#5510 Fix Bugs and Introduce Enhancements in Install-OVS.ps1
  hack/windows/Install-OVS.ps1
Labels: action/release-note

#5393 Promote feature gate EndpointSlice to GA
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-windows-containerd-with-ovs.yml
  build/yamls/antrea-windows-containerd.yml
  build/yamls/antrea-windows.yml
  build/yamls/antrea.yml
  build/yamls/windows/base/conf/antrea-agent.conf
  docs/feature-gates.md
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
Labels: action/release-note

#5408 Add error logging for that Antrea network's MTU exceeds Suricata's maximum supported value
  pkg/agent/agent_linux.go
Labels: kind/bug, action/backport, action/release-note

#5511 Automated cherry pick of #5483: Do not delete IPv6 link-local route in reconciler
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  test/e2e/basic_test.go
Labels: kind/cherry-pick

#5512 Automated cherry pick of #5483: Do not delete IPv6 link-local route in reconciler
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  test/e2e/basic_test.go
Labels: kind/cherry-pick

#5513 Automated cherry pick of #5483: Do not delete IPv6 link-local route in reconciler
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  test/e2e/basic_test.go
Labels: kind/cherry-pick

#5502 Stop logging git fetch progress in actions/checkout
  .github/workflows/benchmark.yml
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  .github/workflows/codeql.yml
  .github/workflows/conformance.yml
  .github/workflows/dependabot.yml
  .github/workflows/docker_update_base_windows.yml
  .github/workflows/go.yml
  .github/workflows/golicense.yml
  .github/workflows/kind.yml
Labels: area/test, kind/cleanup

#5504 Fix flaky TestCluster_Run unit test
  pkg/agent/memberlist/cluster_test.go
Labels: area/test, kind/failing-test

#5314 Improve antctl get featuregates output
  pkg/agent/apiserver/handlers/featuregates/handler.go
  pkg/agent/apiserver/handlers/featuregates/handler_test.go
  pkg/antctl/raw/featuregates/command.go
  pkg/antctl/raw/featuregates/command_test.go
  pkg/apiserver/handlers/featuregates/handler.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
  pkg/features/antrea_features_test.go
Labels: area/component/antctl

#5509 Automated cherry pick of #5495: Do not apply Egress to traffic destined for ServiceCIDRs
  cmd/antrea-agent/agent.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/servicecidr/discoverer.go
  pkg/agent/servicecidr/discoverer_test.go
  pkg/agent/servicecidr/testing/mock_servicecidr.go
Labels: kind/cherry-pick

#5508 Automated cherry pick of #5495: Do not apply Egress to traffic destined for ServiceCIDRs
  cmd/antrea-agent/agent.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/servicecidr/discoverer.go
  pkg/agent/servicecidr/discoverer_test.go
  pkg/agent/servicecidr/testing/mock_servicecidr.go
Labels: kind/cherry-pick

#5519 Fix "make mockgen"
  hack/update-codegen.sh
Labels: size/XS, area/build-release

#5515 Fix flaky TestFlowAggregator_Run unit test
  pkg/flowaggregator/flowaggregator.go
Labels: area/test, kind/failing-test

#5411 Install flows for nested Services in EndpointDNAT only when MC is enabled
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
Labels: area/ovs/openflow

#5521 Make antrea-controller not tolerate Node unreachable
  build/charts/antrea/README.md
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: action/release-note
