Repository antrea-io/antrea, pull requests merged in 2023-10, with the labels that each got.

#5543 Automated cherry pick of #5526: Rename skip flag in custom Test Options
  ci/kind/test-e2e-kind.sh
  test/e2e/main_test.go
Labels: kind/cherry-pick

#5544 Automated cherry pick of #5526: Rename skip flag in custom Test Options
  ci/kind/test-e2e-kind.sh
  test/e2e/main_test.go
Labels: kind/cherry-pick

#5557 chore: unnecessary use of fmt.Sprintf
  pkg/apiserver/handlers/webhook/mutation_labels.go
  pkg/controller/ipam/validate.go
  pkg/controller/networkpolicy/mutate.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/supportbundlecollection/controller_test.go
  pkg/ovs/ovsctl/ovsctl.go
  test/integration/agent/openflow_test.go
  test/integration/agent/route_test.go
Labels: kind/cleanup

#5548 Fix rollback invocation after CmdAdd failure in CNI server
  pkg/agent/cniserver/ipam/ipam_service.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
Labels: action/backport, action/release-note

#5539 Fix an incorrect example yaml in noencap-hybrid-modes doc
  docs/noencap-hybrid-modes.md
Labels: kind/documentation

#5558 Automated cherry pick of #5548: Fix rollback invocation after CmdAdd failure in CNI
  pkg/agent/cniserver/ipam/ipam_service.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
Labels: kind/cherry-pick

#5538 Add goroutine stack dump in support bundle
  pkg/agent/supportbundlecollection/support_bundle_controller.go
  pkg/agent/supportbundlecollection/support_bundle_controller_test.go
  pkg/apiserver/registry/system/supportbundle/rest.go
  pkg/apiserver/registry/system/supportbundle/rest_test.go
  pkg/support/dump.go
  pkg/support/dump_test.go
Labels: action/release-note

#5527 [Dependabot] Group golang.org/x updates
  .github/dependabot.yml
Labels: area/build-release

#5559 Automated cherry pick of #5548: Fix rollback invocation after CmdAdd failure in CNI
  pkg/agent/cniserver/ipam/ipam_service.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
Labels: kind/cherry-pick

#5529 Use the first matching address when getting node address
  pkg/util/k8s/node.go
  pkg/util/k8s/node_test.go
Labels: action/release-note

#5554 Fix NetworkPolicy span calculation
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/subscribe.go
  pkg/controller/networkpolicy/subscribe_test.go
Labels: area/network-policy, action/backport, action/release-note

#5566 Fix deadlock when accessing dirtyRules in fqdn controller
  pkg/agent/controller/networkpolicy/fqdn.go
  pkg/agent/controller/networkpolicy/fqdn_test.go
Labels: kind/bug, action/backport, action/release-note

#5560 Automated cherry pick of #5548: Fix rollback invocation after CmdAdd failure in CNI
  pkg/agent/cniserver/ipam/ipam_service.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
Labels: kind/cherry-pick

#5563 Automated cherry pick of #5510: Fix Bugs and Introduce Enhancements in Install-OVS.ps1
  hack/windows/Install-OVS.ps1
Labels: kind/cherry-pick

#5562 Automated cherry pick of #5510: Fix Bugs and Introduce Enhancements in Install-OVS.ps1
  hack/windows/Install-OVS.ps1
Labels: kind/cherry-pick

#5561 Automated cherry pick of #5510: Fix Bugs and Introduce Enhancements in Install-OVS.ps1
  hack/windows/Install-OVS.ps1
Labels: kind/cherry-pick

#4221 Add unit tests for pkg/ovs/openflow
  pkg/ovs/openflow/ofctrl_action_test.go
  pkg/ovs/openflow/ofctrl_builder_test.go
  pkg/ovs/openflow/ofctrl_group_test.go
  pkg/ovs/openflow/ofctrl_meter_test.go
  pkg/ovs/openflow/ofctrl_packetout.go
  pkg/ovs/openflow/ofctrl_packetout_test.go
  pkg/ovs/openflow/utils.go
  pkg/ovs/ovsctl/interface.go
Labels: area/test

#5575 Automated cherry pick of #5554: Fix NetworkPolicy span calculation
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/subscribe.go
  pkg/controller/networkpolicy/subscribe_test.go
Labels: kind/cherry-pick

#5574 Automated cherry pick of #5554: Fix NetworkPolicy span calculation
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/subscribe.go
  pkg/controller/networkpolicy/subscribe_test.go
Labels: kind/cherry-pick

#5576 Automated cherry pick of #5554: Fix NetworkPolicy span calculation
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/subscribe.go
  pkg/controller/networkpolicy/subscribe_test.go
Labels: kind/cherry-pick

#5581 Automated cherry pick of #5566: Fix deadlock when accessing dirtyRules in fqdn controller
  pkg/agent/controller/networkpolicy/fqdn.go
  pkg/agent/controller/networkpolicy/fqdn_test.go
Labels: kind/cherry-pick

#5545 Add checksum of windows config files as annotations
  Makefile
  build/yamls/antrea-windows-containerd-with-ovs.yml
  build/yamls/antrea-windows-containerd.yml
  build/yamls/antrea-windows.yml
  build/yamls/windows/base/kustomization.yml
  build/yamls/windows/containerd-with-ovs/kustomization.yml
  build/yamls/windows/containerd/agent-containerd.yml
  build/yamls/windows/containerd/kustomization.yml
  build/yamls/windows/default/agent.yml
  build/yamls/windows/default/kustomization.yml
  hack/update-checksum-windows.sh
Labels: area/OS/windows, action/release-note

#5583 Fix data race in FQDN ruleSyncTracker
  pkg/agent/controller/networkpolicy/fqdn.go
Labels: priority/critical-urgent, action/backport

#5588 Fix antctl traceflow using IPv6 address
  pkg/antctl/raw/traceflow/command.go
  pkg/antctl/raw/traceflow/command_test.go
Labels: kind/bug, area/component/antctl, area/ops/traceflow, area/transit/ipv6

#5524 Add unit tests for pkg/agent/controller/noderoute
  pkg/agent/controller/noderoute/node_route_controller_test.go
Labels: area/test

#5598 Automated cherry pick of #5588: Fix antctl traceflow using IPv6 address
  pkg/antctl/raw/traceflow/command.go
  pkg/antctl/raw/traceflow/command_test.go
Labels: kind/cherry-pick

#5597 Automated cherry pick of #5588: Fix antctl traceflow using IPv6 address
  pkg/antctl/raw/traceflow/command.go
  pkg/antctl/raw/traceflow/command_test.go
Labels: kind/cherry-pick

#5531 Clarify the version of Multi-cluster user guide for the new leader manifest
  docs/multicluster/user-guide.md
Labels: area/multi-cluster

#5282 Add IPAllocated and IPAssigned conditions to Egress status
  build/charts/antrea/crds/egress.yaml
  build/charts/antrea/templates/controller/clusterrole.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/egress/ip_scheduler.go
  pkg/agent/controller/egress/ip_scheduler_test.go
  pkg/agent/memberlist/cluster.go
  pkg/apis/crd/v1alpha2/types.go
  pkg/apis/crd/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/crd/v1beta1/types.go
  pkg/apis/crd/v1beta1/util.go
  pkg/apis/crd/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/egress/controller.go
  pkg/controller/egress/controller_test.go
  pkg/util/k8s/semantic.go
  test/e2e/egress_test.go
Labels: api-review, area/transit/egress, action/release-note

#5401 Promote feature gate AntreaProxy to GA
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea-windows-containerd-with-ovs.yml
  build/yamls/antrea-windows-containerd.yml
  build/yamls/antrea-windows.yml
  build/yamls/antrea.yml
  build/yamls/windows/base/conf/antrea-agent.conf
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_linux_test.go
  cmd/antrea-agent/options_test.go
  cmd/antrea-agent/options_windows.go
  docs/feature-gates.md
  hack/generate-manifest.sh
  pkg/agent/agent.go
  pkg/agent/apiserver/handlers/featuregates/handler.go
  pkg/agent/apiserver/handlers/featuregates/handler_test.go
  pkg/agent/apiserver/handlers/ovsflows/handler.go
  pkg/agent/apiserver/handlers/ovsflows/handler_test.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
  pkg/apiserver/handlers/featuregates/handler.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/config/agent/config.go
  pkg/controller/networkpolicy/validate.go
  pkg/features/antrea_features.go
  test/e2e/antreapolicy_test.go
  test/e2e/basic_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/proxy_test.go
  test/e2e/secondary_network_ipam_test.go
  test/e2e/traceflow_test.go
Labels: action/release-note

#5491 Promote feature gate NodePortLocal to GA
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  docs/feature-gates.md
  docs/node-port-local.md
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
  test/e2e/nodeportlocal_test.go
Labels: action/release-note

#5536 e2e: switch from netshoot image to toolbox image
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/e2e/multicast_test.go
  test/e2e/performance_test.go
Labels: action/backport

#5440 Enable Windows OVS Container to run on pristine Host Environment
  build/yamls/antrea-windows-containerd-with-ovs.yml
  build/yamls/windows/containerd-with-ovs/conf/Run-AntreaOVS-Containerd.ps1
  ci/jenkins/test.sh
  docs/windows.md
  hack/windows/Prepare-AntreaAgent.ps1
Labels: area/OS/windows, kind/documentation, action/release-note

#5528 To support new changes for Windows HostProcess Pod for K8S v1.28 and containerd 1.7
  build/yamls/antrea-windows-containerd-with-ovs.yml
  build/yamls/antrea-windows-containerd.yml
  build/yamls/windows/containerd/conf/Install-WindowsCNI-Containerd.ps1
  ci/jenkins/test.sh
  hack/windows/Prepare-Node.ps1
Labels: area/OS/windows, action/release-note

#5351 Clean up auto-generated resources in leader and member clusters
  docs/multicluster/user-guide.md
  hack/.notableofcontents
  multicluster/cmd/multicluster-controller/clusterset_webhook.go
  multicluster/cmd/multicluster-controller/gateway_webhook.go
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/leader_test.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/cmd/multicluster-controller/options.go
  multicluster/controllers/multicluster/common/controller_utils.go
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/leader/clusterset_controller.go
  multicluster/controllers/multicluster/leader/clusterset_controller_test.go
  multicluster/controllers/multicluster/leader/memberclusterannounce_controller.go
  multicluster/controllers/multicluster/leader/stale_controller.go
  multicluster/controllers/multicluster/leader/stale_controller_test.go
  multicluster/controllers/multicluster/member/acnp_resourceimport_controller_test.go
  multicluster/controllers/multicluster/member/clusterinfo_importer_test.go
  multicluster/controllers/multicluster/member/clusterset_controller.go
  multicluster/controllers/multicluster/member/clusterset_controller_test.go
  multicluster/controllers/multicluster/member/gateway_controller_test.go
  multicluster/controllers/multicluster/member/labelidentity_controller_test.go
  multicluster/controllers/multicluster/member/labelidentity_import_controller_test.go
  multicluster/controllers/multicluster/member/node_controller.go
  multicluster/controllers/multicluster/member/resourceimport_controller_test.go
  multicluster/controllers/multicluster/member/serviceexport_controller_test.go
  multicluster/controllers/multicluster/member/stale_controller.go
  multicluster/controllers/multicluster/member/stale_controller_test.go
  multicluster/test/integration/suite_test.go
  pkg/config/controller/config.go
Labels: area/multi-cluster

#5410 Recreate resources when a member cluster rejoins the ClusterSet
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/controllers/multicluster/member/gateway_controller.go
  multicluster/controllers/multicluster/member/gateway_controller_test.go
  multicluster/controllers/multicluster/member/labelidentity_controller.go
  multicluster/controllers/multicluster/member/labelidentity_controller_test.go
  multicluster/controllers/multicluster/member/node_controller.go
  multicluster/controllers/multicluster/member/node_controller_test.go
  multicluster/controllers/multicluster/member/serviceexport_controller.go
  multicluster/controllers/multicluster/member/serviceexport_controller_test.go
  multicluster/test/integration/suite_test.go
Labels: area/multi-cluster

#5618 Automated cherry pick of #5536: e2e: switch from netshoot image to toolbox image
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/e2e/multicast_test.go
  test/e2e/performance_test.go
Labels: kind/cherry-pick

#5638 Automated cherry pick of #5633: Check deletion event matches ClusterSet before Multi-cluster
  multicluster/controllers/multicluster/member/clusterset_controller.go
  multicluster/controllers/multicluster/member/clusterset_controller_test.go
Labels: kind/cherry-pick

#5634 Remove saved ClusterSet from Multi-cluster ClusterSet reconciler
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/controllers/multicluster/leader/clusterset_controller.go
  multicluster/controllers/multicluster/leader/clusterset_controller_test.go
  multicluster/controllers/multicluster/member/clusterset_controller.go
  multicluster/controllers/multicluster/member/clusterset_controller_test.go
Labels: area/multi-cluster

#5620 Automated cherry pick of #5536: e2e: switch from netshoot image to toolbox image
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/e2e/multicast_test.go
  test/e2e/performance_test.go
Labels: kind/cherry-pick

#5619 Automated cherry pick of #5536: e2e: switch from netshoot image to toolbox image
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/e2e/multicast_test.go
  test/e2e/performance_test.go
Labels: kind/cherry-pick
