Repository antrea-io/antrea, pull requests merged in 2023-04, with the labels that each got.

#4802 Fix a broken link in docs/troubleshooting.md
  docs/troubleshooting.md
Labels: kind/documentation

#3889 Unify some functions in pkg/agent/route
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/nodeportlocal/rules/netnat_rule.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/route/testing/mock_route.go
  pkg/agent/util/net.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/net_windows_test.go
  test/integration/agent/route_test.go
Labels: area/OS/windows, action/release-note

#4803 Update documentation for recent MetalLB versions
  docs/service-loadbalancer.md
Labels: kind/documentation

#4587 Add more unit test for pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
Labels: area/test

#4819 Automated cherry pick of #4547: Add ServiceLocalToRemote reject type
  multicluster/test/e2e/fixtures.go
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  multicluster/test/e2e/service_test.go
  pkg/agent/controller/networkpolicy/reject.go
  pkg/agent/controller/networkpolicy/reject_test.go
  test/e2e/antreaipam_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/basic_test.go
  test/e2e/framework.go
  test/e2e/proxy_test.go
  test/e2e/service_externalip_test.go
  test/e2e/service_test.go
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#4812 Stop serving v1alpha2 version of the ClusterGroup CRD
  build/charts/antrea/crds/clustergroup.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/api.md
  test/e2e/antreapolicy_test.go
  test/e2e/clustergroup_test.go
  test/e2e/k8s_util.go
  test/e2e/utils/cg_spec_builder.go
Labels: api-review, area/api, kind/api-change, action/release-note

#4824 Automated cherry pick of #4331: Add docker network parameter to windows build command
  Makefile
Labels: kind/cherry-pick

#4840 Automated cherry pick of #4529: Fix tunnelDstIP field in traceflow on dual-stack
  pkg/agent/controller/traceflow/packetin.go
Labels: kind/cherry-pick

#4852 Fix EndpointSlice API availablility check
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
Labels: action/backport, action/release-note

#4851 Clean up old integration jenkins jobs
  ci/README.md
  ci/jenkins/jobs/job-templates.yaml
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-cloud.yaml
Labels: kind/cleanup, area/test/infra

#4856 Automated cherry pick of #4745: Set test Pod's TerminationGracePeriodSeconds to 1 for
  test/e2e/framework.go
Labels: kind/cherry-pick

#4833 Add timeout for sonobuoy deletion
  ci/run-k8s-e2e-tests.sh
Labels: area/test/e2e, action/backport

#4843 Ignore script exit code for conformance test
  ci/jenkins/test.sh
Labels: action/backport

#4850 Supplyment multicast document with a limitation
  docs/multicast-guide.md
Labels: kind/documentation, action/backport

#4845 Fix Service update processing
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
Labels: area/proxy, action/backport, action/release-note

#4577 SupportBundleCollection e2e test
  build/yamls/externalnode/support-bundle-collection-rbac.yml
  ci/jenkins/test-vm.sh
  docs/support-bundle-guide.md
  hack/externalnode/sftp-deployment.yml
  pkg/support/dump_windows.go
  pkg/support/dump_windows_test.go
  test/e2e/vmagent_test.go
Labels: area/test/e2e

#4879 Automated cherry pick of #4745: Set test Pod's TerminationGracePeriodSeconds to 1 for
  test/e2e/framework.go
Labels: kind/cherry-pick

#4877 Automated cherry pick of #4850: Supplyment multicast document with a limitation
  docs/multicast-guide.md
Labels: kind/cherry-pick

#4873 Stop exporting KUBECONFIG in ci/test-conformance-gke.sh
  ci/jenkins/jobs/projects-cloud.yaml
  ci/test-conformance-gke.sh
Labels: area/provider/gcp, area/test/infra

#4880 Automated cherry pick of #4870: Bump up ofnet library to v0.6.10
  go.mod
  go.sum
  pkg/ovs/openflow/ofctrl_bridge_test.go
Labels: kind/cherry-pick

#4890 Automated cherry pick of #4850: Supplyment multicast document with a limitation
  docs/multicast-guide.md
Labels: kind/cherry-pick

#4883 Automated cherry pick of #4862: Several fixes in ci/test-conformance-gke.sh
  ci/jenkins/test.sh
  ci/run-k8s-e2e-tests.sh
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
  docs/gke-installation.md
Labels: kind/cherry-pick

#4867 Support local multi-cluster image build
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  Makefile
  ci/jenkins/test-mc.sh
  docs/multicluster/user-guide.md
  multicluster/build/images/Dockerfile
Labels: area/multi-cluster

#4892 Automated cherry pick of #4740: Clean up agent images before building linux images on
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#4889 Update Multi-cluster user guide
  docs/multicluster/user-guide.md
Labels: kind/documentation, area/multi-cluster

#4825 Deprecate Antrea Octant Plugin
  ROADMAP.md
  docs/assets/arch.svg
  docs/assets/arch.svg.png
  docs/contributors/github-labels.md
  docs/design/architecture.md
  docs/getting-started.md
  docs/octant-plugin-installation.md
  docs/traceflow-guide.md
  plugins/octant/cmd/antrea-octant-plugin/main.go
Labels: action/release-note

#4814 Disable ExternalName type of Service exporting
  multicluster/controllers/multicluster/leader/resourceexport_controller.go
  multicluster/controllers/multicluster/member/serviceexport_controller.go
  multicluster/controllers/multicluster/member/serviceexport_controller_test.go
  multicluster/test/integration/serviceexport_controller_test.go
Labels: area/multi-cluster

#4903 [Multicast] Clone remoteMembers when creating an updated GroupMemberStatus
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
Labels: action/backport

#4909 Automated cherry pick of #4903: Clone remoteMembers when updating a
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
Labels: kind/cherry-pick

#4908 Automated cherry pick of #4903: Clone remoteMembers when updating a
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
Labels: kind/cherry-pick

#4615 Add unit test for pkg/antctl/raw/supportbundle
  pkg/antctl/raw/supportbundle/command.go
  pkg/antctl/raw/supportbundle/command_test.go
Labels: area/test

#4709 Refine Multi-cluster unit tests to remove unnecessary dependency
  pkg/antctl/raw/multicluster/deploy/deploy_helper.go
  pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
  pkg/antctl/raw/multicluster/deploy/leader_cluster_test.go
  pkg/antctl/raw/multicluster/deploy/member_cluster_test.go
Labels: area/test, area/multi-cluster

#4853 Fix race condition between stale controller and resourceimport reconcilers
  multicluster/controllers/multicluster/member/resourceimport_controller_test.go
  multicluster/controllers/multicluster/stale_controller.go
Labels: area/multi-cluster, action/backport
