Repository antrea-io/antrea, pull requests merged in 2023-11, with the labels that each got.

#5643 Automated cherry pick of #5528: Update prepare-node script, antrea-windows-containerd.yml and
  build/yamls/antrea-windows-containerd-with-ovs.yml
  build/yamls/antrea-windows-containerd.yml
  build/yamls/windows/containerd/conf/Install-WindowsCNI-Containerd.ps1
  ci/jenkins/test.sh
  hack/windows/Prepare-Node.ps1
Labels: kind/cherry-pick

#5646 Automated cherry pick of #5528: Update prepare-node script, antrea-windows-containerd.yml and
  build/yamls/antrea-windows-containerd.yml
  build/yamls/windows/containerd/conf/Install-WindowsCNI-Containerd.ps1
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#5023 Upgrade Prometheus to v2.46.0
  build/yamls/antrea-prometheus.yml
  docs/prometheus-integration.md
  test/e2e/prometheus_test.go
Labels: area/monitoring/metrics

#5657 Set net.ipv4.conf.antrea-gw0.arp_announce to 1
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/openflow/pod_connectivity.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/util/net_linux.go
  test/integration/agent/openflow_test.go
Labels: kind/bug, action/backport, action/release-note

#5257 Revise `antctl mc deploy` to support manifest update
  pkg/antctl/raw/multicluster/deploy/deploy_helper.go
  pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
Labels: area/multi-cluster

#5339 [doc][flexible-ipam] Add Flexible IPAM design section
  docs/antrea-ipam.md
Labels: area/ipam, kind/documentation

#5672 Check all multi-cluster manifests in check-manifest.sh
  ci/check-manifest.sh
Labels: area/multi-cluster

#5678 Automated cherry pick of #5657: Set net.ipv4.conf.antrea-gw0.arp_announce to 1
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/openflow/pod_connectivity.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/util/net_linux.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#5679 Automated cherry pick of #5657: Set net.ipv4.conf.antrea-gw0.arp_announce to 1
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/openflow/pod_connectivity.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/util/net_linux.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#5680 Automated cherry pick of #5657: Set net.ipv4.conf.antrea-gw0.arp_announce to 1
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/openflow/pod_connectivity.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/util/net_linux.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#5627 Add more unit tests for node_route_controller.go
  hack/update-codegen-dockerized.sh
  pkg/agent/controller/noderoute/node_route_controller_test.go
  pkg/agent/multicluster/mc_route_controller_test.go
  pkg/agent/wireguard/testing/mock_wireguard.go
Labels: area/test

#5687 Fix NP not working on hairpin Service connection
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  test/e2e/antreapolicy_test.go
  test/e2e/networkpolicy_test.go
Labels: action/backport

#5675 [ci][flexible-ipam] Upgrade FlexibleIPAM e2e testbed to k8s 1.28.2
  ci/jenkins/test.sh
Labels: area/test/infra

#5701 Automated cherry pick of #5687: Fix NP not working on Hairpin
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  test/e2e/antreapolicy_test.go
  test/e2e/networkpolicy_test.go
Labels: kind/cherry-pick

#5700 Automated cherry pick of #5687: Fix NP not working on Hairpin
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  test/e2e/antreapolicy_test.go
  test/e2e/networkpolicy_test.go
Labels: kind/cherry-pick

#5592 Remove redundant log in fillPodInfo/fillServiceInfo and update deny connection store.
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/flowexporter/connections/connections.go
  pkg/agent/flowexporter/connections/conntrack_connections.go
  pkg/agent/flowexporter/connections/deny_connections.go
  pkg/agent/flowexporter/connections/deny_connections_test.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  test/e2e/bandwidth_test.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: action/backport, action/release-note

#5660 Add host-local IPAM GC on startup
  go.mod
  go.sum
  pkg/agent/cniserver/ipam/hostlocal/gc.go
  pkg/agent/cniserver/ipam/hostlocal/gc_test.go
  pkg/agent/cniserver/ipam/ipam_delegator.go
  pkg/agent/cniserver/pod_configuration.go
  test/integration/agent/cniserver_test.go
Labels: area/component/cni, action/release-note

#5689 Use Traceflow API v1beta1
  pkg/antctl/raw/traceflow/command.go
  pkg/antctl/raw/traceflow/command_test.go
  pkg/controller/traceflow/validate.go
  pkg/controller/traceflow/validate_test.go
  test/e2e/traceflow_test.go
Labels: kind/bug, area/component/antctl, area/ops/traceflow, action/backport, action/release-note

#5712 Automated cherry pick of #5705: Add Hairpin traffic limitation doc
  docs/antrea-network-policy.md
  test/e2e/networkpolicy_test.go
Labels: kind/cherry-pick

#5711 Automated cherry pick of #5705: Add Hairpin traffic limitation doc
  docs/antrea-network-policy.md
  test/e2e/networkpolicy_test.go
Labels: kind/cherry-pick

#5667 Add NetworkPolicy rule name in Traceflow observation
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
  pkg/apis/crd/v1beta1/types.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  test/e2e/traceflow_test.go
Labels: kind/feature, area/ops/traceflow, action/release-note

#5713 Automated cherry pick of #5689: Use Traceflow API v1beta1
  pkg/antctl/raw/traceflow/command.go
  pkg/antctl/raw/traceflow/command_test.go
  pkg/controller/traceflow/validate.go
  pkg/controller/traceflow/validate_test.go
  test/e2e/traceflow_test.go
Labels: kind/cherry-pick

#5714 Automated cherry pick of #5689: Use Traceflow API v1beta1
  pkg/antctl/raw/traceflow/command.go
  pkg/antctl/raw/traceflow/command_test.go
  test/e2e/traceflow_test.go
Labels: kind/cherry-pick

#5723 Fix antrea-ubi image build
  build/images/Dockerfile.build.ubi
Labels: action/backport, action/release-note

#5728 Automated cherry pick of #5723: Fix antrea-ubi image build #5727: Add git to antrea-build image for UBI build
  build/images/Dockerfile.build.ubi
Labels: kind/cherry-pick

#5427 Use Antrea IPAM for Antrea native secondary network support
  hack/update-codegen-dockerized.sh
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/ipam/antrea_ipam.go
  pkg/agent/cniserver/ipam/antrea_ipam_test.go
  pkg/agent/cniserver/ipam/hostlocal/gc.go
  pkg/agent/cniserver/ipam/ipam_service.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/secondary.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/secondarynetwork/cnipodcache/types.go
  pkg/agent/secondarynetwork/ipam/ipam_delegator.go
  pkg/agent/secondarynetwork/ipam/testing/mock_ipam.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  pkg/agent/secondarynetwork/podwatch/testing/mock_podwatch.go
  pkg/agent/secondarynetwork/podwatch/types.go
Labels: area/ipam, area/interface

#5744 Remove Whereabouts installation
  build/charts/antrea/README.md
  build/charts/antrea/templates/NOTES.txt
  build/charts/antrea/templates/_helpers.tpl
  build/charts/antrea/templates/agent/daemonset.yaml
  build/charts/antrea/templates/whereabouts/clusterrole.yaml
  build/charts/antrea/templates/whereabouts/clusterrolebinding.yaml
  build/charts/antrea/templates/whereabouts/secret.yaml
  build/charts/antrea/templates/whereabouts/serviceaccount.yaml
  build/charts/antrea/values.yaml
  build/images/base/Dockerfile
  build/images/base/Dockerfile.ubi
  build/images/scripts/install_whereabouts_config
  hack/generate-manifest.sh
Labels: area/secondary-network

#5743 Clarify hairpin Service traffic case in NP doc
  docs/antrea-network-policy.md
Labels: kind/documentation

#5739 Store NetworkPolicy in filesystem as fallback data source
  cmd/antrea-agent/agent.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/cache_test.go
  pkg/agent/controller/networkpolicy/filestore.go
  pkg/agent/controller/networkpolicy/filestore_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  test/e2e/networkpolicy_test.go
Labels: area/network-policy, action/backport, action/release-note

#5708 Clarify getting started doc for upgrade
  docs/getting-started.md
Labels: kind/documentation, size/XS
