Repository antrea-io/antrea, pull requests merged in 2023-05, with the labels that each got.

#4608 Introduce "Failed" phase in ANP status
  pkg/apis/crd/v1alpha1/types.go
  pkg/controller/networkpolicy/status_controller.go
  pkg/controller/networkpolicy/status_controller_test.go
Labels: api-review, area/network-policy/api, kind/api-change

#4934 Fix FQDN upper-case issue
  pkg/agent/controller/networkpolicy/fqdn.go
  test/e2e/antreapolicy_test.go
Labels: action/backport

#4946 Run modules that rely on Services after AntreaProxy is ready
  cmd/antrea-agent/agent.go
Labels: action/backport, action/release-note

#4705 Update windows ovs download link to ovs 2.16.7
  hack/windows/Install-OVS.ps1
  test/e2e/nodeportlocal_test.go
Labels: area/OS/windows, action/release-note

#4951 Automated cherry pick of #4946: Run modules that rely on Services after AntreaProxy is ready
  cmd/antrea-agent/agent.go
Labels: kind/cherry-pick

#4950 Automated cherry pick of #4946: Run modules that rely on Services after AntreaProxy is ready
  cmd/antrea-agent/agent.go
Labels: kind/cherry-pick

#4945 Automated cherry pick of #4934: Fix FQDN upper-case issue
  pkg/agent/controller/networkpolicy/fqdn.go
  test/e2e/antreapolicy_test.go
Labels: kind/cherry-pick

#4872 Add Containerd to Windows Jenkins Jobs
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test.sh
Labels: area/test, area/test/e2e

#4959 Update Open vSwitch to 2.17.6
  build/images/deps/ovs-version
  build/images/ovs/apply-patches.sh
  docs/troubleshooting.md
Labels: action/release-note

#4963 [traceflow] Use ramdom port when UDP source port is 0
  pkg/agent/openflow/client.go
Labels: action/release-note

#4964 Automated cherry pick of #4959: Update Open vSwitch to 2.17.6
  build/images/deps/ovs-version
  build/images/ovs/apply-patches.sh
  docs/troubleshooting.md
Labels: kind/cherry-pick

#4965 Automated cherry pick of #4959: Update Open vSwitch to 2.17.6
  build/images/deps/ovs-version
  build/images/ovs/apply-patches.sh
  docs/troubleshooting.md
Labels: kind/cherry-pick

#4722 [Windows] Improvement in cleanup script
  hack/windows/Clean-AntreaNetwork.ps1
Labels: area/OS/windows, kind/cleanup

#4957 Add openEuler 22.03 in tested distributions
  docs/kubernetes-installers.md
Labels: kind/documentation

#4970 Automated cherry pick of #4722: Improvement in cleanup script
  hack/windows/Clean-AntreaNetwork.ps1
Labels: kind/cherry-pick

#4971 Automated cherry pick of #4722: Improvement in cleanup script
  hack/windows/Clean-AntreaNetwork.ps1
Labels: kind/cherry-pick

#4976 Automated cherry pick of #4872: Add containerd to windows jenkins jobs
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#4977 Automated cherry pick of #4872: Add containerd to windows jenkins jobs
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#4866 Add support for ExternalIP in AntreaProxy
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/route/testing/mock_route.go
  pkg/ovs/openflow/testing/utils.go
  test/integration/agent/openflow_test.go
  third_party/proxy/types.go
Labels: area/proxy, action/release-note

#4807 Add IP based group association query API and ClientSet
  cmd/antrea-controller/controller.go
  pkg/apis/controlplane/register.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/register.go
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/apiserver/registry/networkpolicy/groupassociation/rest.go
  pkg/apiserver/registry/networkpolicy/groupassociation/rest_test.go
  pkg/apiserver/registry/networkpolicy/ipgroupassociation/rest.go
  pkg/apiserver/registry/networkpolicy/ipgroupassociation/rest_test.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_ipgroupassociation.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/generated_expansion.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/ipgroupassociation.go
  pkg/controller/grouping/controller.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/group.go
  pkg/controller/networkpolicy/group_test.go
  pkg/controller/networkpolicy/store/group.go
  pkg/controller/traceflow/controller.go
  pkg/controller/traceflow/controller_test.go
  pkg/controller/types/group.go
Labels: area/network-policy

#4942 Look up Pods by name to fetch labels in Flow Aggregator
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
Labels: area/flow-visibility/aggregator, action/release-note

#4891 Adds unit test for pkg/antctl/raw/proxy/command.go
  pkg/antctl/raw/proxy/command.go
  pkg/antctl/raw/proxy/command_test.go
Labels: area/test

#4606 Add WireGuard tunnels for Multi-cluster traffic
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/templates/agent/clusterrole.yaml
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  docs/network-requirements.md
  multicluster/apis/multicluster/v1alpha1/gateway_types.go
  multicluster/apis/multicluster/v1alpha1/zz_generated.deepcopy.go
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/gateway_webhook.go
  multicluster/config/crd/bases/multicluster.crd.antrea.io_clusterinfoimports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_gateways.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  multicluster/controllers/multicluster/member/gateway_controller.go
  multicluster/controllers/multicluster/member/gateway_controller_test.go
  pkg/agent/agent.go
  pkg/agent/multicluster/mc_route_controller.go
  pkg/agent/multicluster/mc_route_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/multicluster.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/testing/mock_route.go
  pkg/agent/wireguard/client_linux.go
  pkg/agent/wireguard/client_test.go
  pkg/agent/wireguard/client_windows.go
  pkg/agent/wireguard/client_windows_test.go
  pkg/agent/wireguard/interface.go
  pkg/agent/wireguard/testing/mock_wireguard.go
  pkg/apis/ports.go
  pkg/config/agent/config.go
Labels: area/multi-cluster, action/release-note

#4768 Change to use PacketIn2/Controller2
  go.mod
  go.sum
  pkg/agent/controller/networkpolicy/audit_logging_test.go
  pkg/agent/controller/networkpolicy/fqdn.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/controller/networkpolicy/packetin_test.go
  pkg/agent/controller/networkpolicy/reject.go
  pkg/agent/controller/networkpolicy/reject_test.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/multicast/mcast_discovery.go
  pkg/agent/multicast/mcast_discovery_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/multicast.go
  pkg/agent/openflow/multicast_test.go
  pkg/agent/openflow/multicluster.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/packetin.go
  pkg/agent/openflow/packetin_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/service.go
  pkg/agent/openflow/service_test.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/proxy/proxier.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_bridge_test.go
  pkg/ovs/openflow/ofctrl_packetin_test.go
  pkg/ovs/openflow/testing/mock_openflow.go
  pkg/ovs/openflow/testing/utils.go
  test/integration/ovs/ofctrl_test.go
Labels: area/ovs/openflow, kind/cleanup, action/release-note

#4687 Add source ports in Antrea-native policy API
  build/charts/antrea/crds/clusternetworkpolicy.yaml
  build/charts/antrea/crds/networkpolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/k8s_util.go
  test/e2e/utils/anp_spec_builder.go
  test/e2e/utils/cnp_spec_builder.go
  test/e2e/utils/helper.go
  test/e2e/vmagent_test.go
Labels: area/network-policy, action/release-note

#4992 Use LOCAL instead of CONTROLLER as the in_port of packet-out message
  pkg/agent/proxy/proxier.go
Labels: area/OS/windows, area/proxy, action/backport, action/release-note

#4815 Add support for short-circuiting in AntreaProxy
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/service.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/topology_test.go
  test/e2e/proxy_test.go
  test/integration/agent/openflow_test.go
  third_party/proxy/service.go
Labels: area/proxy, action/release-note

#5003 Automated cherry pick of #4986: Fix policy not being cleaned if a policy with the same name
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
Labels: kind/cherry-pick

#4495 Cache Flow modification message in Antrea Agent
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/egress.go
  pkg/agent/openflow/egress_test.go
  pkg/agent/openflow/externalnode_connectivity.go
  pkg/agent/openflow/externalnode_connectivity_test.go
  pkg/agent/openflow/framework.go
  pkg/agent/openflow/multicast.go
  pkg/agent/openflow/multicast_test.go
  pkg/agent/openflow/multicluster.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
  pkg/agent/openflow/pod_connectivity.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/openflow/service.go
  pkg/agent/openflow/service_test.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/openflow/traceflow.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_action.go
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/ofctrl_flow.go
  pkg/ovs/openflow/ofctrl_flow_test.go
  pkg/ovs/openflow/ofctrl_group.go
  pkg/ovs/openflow/ofctrl_meter.go
  pkg/ovs/openflow/testing/mock_openflow.go
  pkg/ovs/openflow/utils.go
  pkg/ovs/openflow/utils_test.go
  test/integration/ovs/ofctrl_test.go
Labels: kind/cleanup, action/release-note

#4748 Add Log Label to Audit Logging
  build/charts/antrea/crds/clusternetworkpolicy.yaml
  build/charts/antrea/crds/networkpolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/antrea-network-policy.md
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/agent/controller/networkpolicy/audit_logging_test.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/agent/flowexporter/connections/conntrack_connections_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/testing/mock_openflow.go
  pkg/agent/types/networkpolicy.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/networkpolicy/antreanetworkpolicy.go
  pkg/controller/networkpolicy/antreanetworkpolicy_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/utils/anp_spec_builder.go
  test/e2e/utils/cnp_spec_builder.go
Labels: api-review, area/network-policy/api, area/network-policy, action/release-note

#4993 Upgrade to go-ipfix v0.6.1
  ci/kind/test-e2e-kind.sh
  go.mod
  go.sum
  test/e2e/framework.go
Labels: area/dependency

#5008 Prevent headless Service from updating Service CIDR
  pkg/agent/servicecidr/discoverer.go
  pkg/agent/servicecidr/discoverer_test.go
Labels: size/S, area/component/agent, action/backport, action/release-note

#4666 Update CA Bundle on the existing APIServices/Webhooks
  build/charts/antrea/crds/clustergroup.yaml
  build/charts/antrea/templates/controller/apiservices.yaml
  build/charts/antrea/templates/controller/clusterrole.yaml
  build/charts/antrea/templates/webhooks/mutating/crdmutator.yaml
  build/charts/antrea/templates/webhooks/mutating/labelsmutator.yaml
  build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/controller_test.go
  multicluster/cmd/multicluster-controller/leader.go
  multicluster/cmd/multicluster-controller/leader_test.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/cmd/multicluster-controller/member_test.go
  multicluster/config/overlays/leader-ns/webhook_patch.yaml
  multicluster/config/overlays/leader-ns/webhook_rbac.yaml
  multicluster/config/overlays/member/additional_role_patch.yaml
  multicluster/config/overlays/member/webhook_patch.yaml
  multicluster/hack/generate-manifest.sh
  pkg/apiserver/apiserver.go
  pkg/apiserver/certificate/cacert_controller.go
  pkg/apiserver/certificate/cacert_controller_test.go
  pkg/apiserver/certificate/config.go
Labels: kind/cleanup

#4948 Set default flag to 2 for TCP traceflow
  docs/traceflow-guide.md
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
Labels: action/release-note

#4994 Fix concurrent map write in mc controller
  multicluster/controllers/multicluster/leader/labelidentity_export_controller.go
  multicluster/controllers/multicluster/leader/labelidentity_export_controller_test.go
Labels: kind/bug, area/multi-cluster, action/backport, action/release-note

#4905 Add E2E test for Multi-cluster WireGuard encryption
  multicluster/test/e2e/fixtures.go
  multicluster/test/e2e/framework.go
  multicluster/test/e2e/main_test.go
  test/e2e/framework.go
  test/e2e/k8s_util.go
  test/e2e/nodeportlocal_test.go
  test/e2e/upgrade_test.go
Labels: area/multi-cluster

#5017 Avoid ServiceCIDR flapping on agent start
  cmd/antrea-agent/agent.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/servicecidr/discoverer.go
  pkg/agent/servicecidr/discoverer_test.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
Labels: action/release-note

#4629 Adds unit tests for pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
Labels: area/test

#4941 Improve AntreaProxy route syncing on Windows
  pkg/agent/route/route_windows.go
  pkg/agent/util/powershell/powershell_windows.go
Labels: area/OS/windows, area/proxy, action/backport

#4895 Support EndpointSlice API for ServiceExport controller
  CONTRIBUTING.md
  docs/antrea-proxy.md
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/member.go
  multicluster/cmd/multicluster-controller/options.go
  multicluster/cmd/multicluster-controller/options_test.go
  multicluster/cmd/multicluster-controller/testdata/antrea-mc-config-with-invalid-endpointiptype.yml
  multicluster/config/overlays/member/role.yaml
  multicluster/config/rbac/role.yaml
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/common/test_data.go
  multicluster/controllers/multicluster/common/types.go
  multicluster/controllers/multicluster/member/serviceexport_controller.go
  multicluster/controllers/multicluster/member/serviceexport_controller_test.go
  multicluster/test/integration/serviceexport_controller_test.go
  multicluster/test/integration/suite_test.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/util/k8s/client.go
  pkg/util/k8s/client_test.go
Labels: area/multi-cluster

#5011 Graduate features from Alpha to Beta
  .github/workflows/kind.yml
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/conf/antrea-controller.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  ci/jenkins/test.sh
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  docs/antrea-ipam.md
  docs/feature-gates.md
  docs/multicast-guide.md
  hack/generate-manifest.sh
  pkg/agent/apiserver/handlers/multicast/handler.go
  pkg/apiserver/handlers/featuregates/handler.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/config/agent/config.go
  pkg/features/antrea_features.go
  test/e2e/antreapolicy_test.go
  test/e2e/framework.go
  test/e2e/main_test.go
  test/e2e/multicast_test.go
Labels: action/release-note

#5026 waitForAntreaDaemonSetPods should wait for Pods being ready
  test/e2e/framework.go
Labels: area/test/e2e

#5009 Automated cherry pick of #4988: Bump up whereabouts to v0.6.1
  build/images/base/Dockerfile
  build/images/base/Dockerfile.ubi
  test/e2e-secondary-network/infra/prepare_cluster.sh
  test/e2e-secondary-network/infra/prepare_sriov.sh
Labels: kind/cherry-pick

#5042 Automated cherry pick of #5035: Remove uninitialized taint to recover CAPV testbeds
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#5041 Automated cherry pick of #5035: Remove uninitialized taint to recover CAPV testbeds
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#5040 Automated cherry pick of #5035: Remove uninitialized taint to recover CAPV testbeds
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#5036 Automated cherry pick of #4988: Bump up whereabouts to v0.6.1
  build/images/base/Dockerfile
  build/images/base/Dockerfile.ubi
  test/e2e-secondary-network/infra/prepare_cluster.sh
  test/e2e-secondary-network/infra/prepare_sriov.sh
Labels: kind/cherry-pick

#5046 Automated cherry pick of #4991: Fix UBI image build error
  build/images/ovs/Dockerfile.ubi
Labels: kind/cherry-pick

#5045 Automated cherry pick of #4991: Fix UBI image build error
  build/images/ovs/Dockerfile.ubi
Labels: kind/cherry-pick

#5044 Automated cherry pick of #5008: Prevent headless Service from updating Service CIDR
  pkg/agent/servicecidr/discoverer.go
  pkg/agent/servicecidr/discoverer_test.go
Labels: kind/cherry-pick
