Repository antrea-io/antrea, pull requests merged in 2023-08, with the labels that each got.

#5299 Add "X-Load-Balancing-Endpoint-Weight" header to AntreaProxy Service healthcheck
  third_party/proxy/healthcheck/service_health.go
Labels: area/proxy, action/release-note

#5337 Add log rotation configuration for audit logs
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/config/agent/config.go
Labels: area/monitoring/logging, area/monitoring/auditing, area/network-policy, action/release-note

#5353 Fix error log when agent fails to connect to K8s API
  pkg/agent/agent.go
  pkg/agent/agent_test.go
Labels: action/release-note

#5349 Always run antctl in Pod for e2e tests
  build/images/Dockerfile.build.coverage
  build/images/Dockerfile.build.ubi
  build/images/Dockerfile.build.ubuntu
  test/e2e/antctl_test.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/main_test.go
  test/e2e/service_externalip_test.go
Labels: area/test/e2e

#5279 Support OVS bridge creation for secondary network
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_test.go
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/secondarynetwork/init.go
  pkg/agent/secondarynetwork/init_test.go
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
  pkg/config/agent/config.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/util/k8s/client.go
  test/integration/ovs/ovs_client_test.go
Labels: area/ovs/ovsdb, area/interface

#5356 Optimize ovs-pipeline-external-node.svg
  docs/assets/ovs-pipeline-external-node.svg
Labels: kind/documentation

#5363 Fix unit tests for pkg/apiserver/registry/stats
  pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest.go
  pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest_test.go
  pkg/apiserver/registry/stats/antreanetworkpolicystats/rest.go
  pkg/apiserver/registry/stats/antreanetworkpolicystats/rest_test.go
  pkg/apiserver/registry/stats/networkpolicystats/rest.go
  pkg/apiserver/registry/stats/networkpolicystats/rest_test.go
Labels: area/test

#5364 Stop using /bin/sh for OVS commands
  pkg/agent/cniserver/sriov.go
  pkg/ovs/ovsctl/appctl.go
  pkg/ovs/ovsctl/interface.go
  pkg/ovs/ovsctl/mock_ovsctl_test.go
  pkg/ovs/ovsctl/ofctl.go
  pkg/ovs/ovsctl/ovsctl.go
  pkg/ovs/ovsctl/ovsctl_others.go
  pkg/ovs/ovsctl/ovsctl_windows.go
  pkg/ovs/ovsctl/testing/mock_ovsctl.go
Labels: action/backport

#5264 Automated cherry pick of #5254: Fix VM e2e script to import updated image
  ci/jenkins/test-vm.sh
Labels: kind/cherry-pick

#5372 Automated cherry pick of #5364: Stop using /bin/sh for OVS commands
  pkg/agent/cniserver/sriov.go
  pkg/ovs/ovsctl/appctl.go
  pkg/ovs/ovsctl/interface.go
  pkg/ovs/ovsctl/mock_ovsctl_test.go
  pkg/ovs/ovsctl/ofctl.go
  pkg/ovs/ovsctl/ovsctl.go
  pkg/ovs/ovsctl/ovsctl_others.go
  pkg/ovs/ovsctl/ovsctl_windows.go
  pkg/ovs/ovsctl/testing/mock_ovsctl.go
Labels: kind/cherry-pick, action/release-note

#5373 Automated cherry pick of #5364: Stop using /bin/sh for OVS commands
  pkg/agent/cniserver/sriov.go
  pkg/ovs/ovsctl/appctl.go
  pkg/ovs/ovsctl/interface.go
  pkg/ovs/ovsctl/mock_ovsctl_test.go
  pkg/ovs/ovsctl/ofctl.go
  pkg/ovs/ovsctl/ovsctl.go
  pkg/ovs/ovsctl/ovsctl_others.go
  pkg/ovs/ovsctl/ovsctl_windows.go
  pkg/ovs/ovsctl/testing/mock_ovsctl.go
Labels: kind/cherry-pick, action/release-note

#5338 Fix a bug that ClusterSet status is no longer updated
  multicluster/controllers/multicluster/leader/clusterset_controller.go
  multicluster/controllers/multicluster/leader/clusterset_controller_test.go
  multicluster/controllers/multicluster/member/clusterset_controller.go
  multicluster/controllers/multicluster/member/clusterset_controller_test.go
Labels: area/multi-cluster, action/backport

#5370 Fix missing protocol in service when processing ANP named ports
  pkg/agent/controller/networkpolicy/reconciler.go
  pkg/agent/controller/networkpolicy/reconciler_test.go
  pkg/controller/networkpolicy/adminnetworkpolicy.go
Labels: action/backport, action/release-note

#5367 [Multicast] Remove NetworkPolicyStats dependency of MulticastGroup API
  pkg/apiserver/registry/stats/multicastgroup/rest.go
  pkg/apiserver/registry/stats/multicastgroup/rest_test.go
Labels: action/backport, action/release-note

#5381 [doc][network-policy] Add explanation for existing connection behavior
  docs/antrea-network-policy.md
Labels: kind/documentation

#5390 Automated cherry pick of #5338: Fix a bug that ClusterSet status is no longer updated
  multicluster/controllers/multicluster/leader/clusterset_controller.go
  multicluster/controllers/multicluster/leader/clusterset_controller_test.go
  multicluster/controllers/multicluster/member/clusterset_controller.go
  multicluster/controllers/multicluster/member/clusterset_controller_test.go
Labels: kind/cherry-pick

#5407 Automated cherry pick of #5385: Support querying all NDIS network adapters
  pkg/agent/config/ipsec_authentication_mode.go
  pkg/agent/util/net_windows.go
Labels: kind/cherry-pick, action/release-note

#5230 Switch traceflow CRD validation to webhook validation.
  build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-controller/controller.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
  pkg/apiserver/apiserver.go
  pkg/controller/traceflow/controller.go
  pkg/controller/traceflow/controller_test.go
  pkg/controller/traceflow/validate.go
  pkg/controller/traceflow/validate_test.go
  test/e2e/fixtures.go
  test/e2e/traceflow_test.go
Labels: action/release-note

#5394 Automated cherry pick of #5367: Remove NetworkPolicyStats dependency of of MulticastGroup API
  pkg/apiserver/registry/stats/multicastgroup/rest.go
  pkg/apiserver/registry/stats/multicastgroup/rest_test.go
Labels: kind/cherry-pick

#5395 Automated cherry pick of #5367: Remove NetworkPolicyStats dependency of of MulticastGroup API
  pkg/apiserver/registry/stats/multicastgroup/rest.go
  pkg/apiserver/registry/stats/multicastgroup/rest_test.go
Labels: kind/cherry-pick

#5396 Automated cherry pick of #5367: Remove NetworkPolicyStats dependency of of MulticastGroup API
  pkg/apiserver/registry/stats/multicastgroup/rest.go
  pkg/apiserver/registry/stats/multicastgroup/rest_test.go
Labels: kind/cherry-pick

#5352 Decouple Audit logging from AntreaPolicy feature gate
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/agent/controller/networkpolicy/audit_logging_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/openflow/framework.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
Labels: action/release-note

#5404 Fix controller issue in handling empty pod labels for labelidentity
  multicluster/controllers/multicluster/member/labelidentity_controller.go
  multicluster/controllers/multicluster/member/labelidentity_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: kind/bug, action/backport

#5378 Refine the default flow in ARPSpoofGuardTable
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
Labels: area/ovs/openflow, action/backport

#5397 Automated cherry pick of #5061: Use OpenFlow group for Network Policy logging
  cmd/antrea-agent/agent.go
  hack/update-codegen-dockerized.sh
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/agent/controller/networkpolicy/audit_logging_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/packetin.go
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/egress.go
  pkg/agent/openflow/externalnode_connectivity.go
  pkg/agent/openflow/externalnode_connectivity_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/framework.go
  pkg/agent/openflow/framework_test.go
  pkg/agent/openflow/multicast.go
  pkg/agent/openflow/multicast_test.go
  pkg/agent/openflow/multicluster.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/packetin_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_other.go
  pkg/agent/openflow/pipeline_windows.go
  pkg/agent/openflow/pod_connectivity.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/openflow/service.go
  pkg/agent/openflow/service_test.go
  pkg/agent/openflow/traceflow.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_group.go
  pkg/ovs/openflow/testing/mock_openflow.go
  test/integration/agent/openflow_test.go
  test/integration/ovs/openflow_test_utils.go
Labels: kind/cherry-pick

#5386 Add hostAliases to Helm values for Flow Aggregator
  build/charts/flow-aggregator/README.md
  build/charts/flow-aggregator/templates/deployment.yaml
  build/charts/flow-aggregator/values.yaml
  build/yamls/flow-aggregator.yml
Labels: area/flow-visibility/aggregator, action/release-note

#5415 Fix e2e test testTraceflowValidation for IPv6-only cluster
  test/e2e/traceflow_test.go
Labels: kind/failing-test

#5389 Add a new all-in-one manifest for the Multi-cluster leader cluster
  ci/jenkins/test-mc.sh
  docs/multicluster/user-guide.md
  hack/release/prepare-assets.sh
  multicluster/Makefile
  multicluster/build/yamls/antrea-multicluster-leader.yml
  multicluster/config/overlays/leader/coverage/manager_command_patch_coverage.yaml
  multicluster/config/overlays/leader/crd_patch.yaml
  multicluster/config/overlays/leader/kustomization.yaml
  multicluster/config/overlays/leader/kustomizeconfig.yaml
  multicluster/config/overlays/leader/manager_command_patch.yaml
  multicluster/config/overlays/leader/member_cluster_role.yaml
  multicluster/config/overlays/leader/member_cluster_rolebinding.yaml
  multicluster/config/overlays/leader/member_cluster_serviceaccount.yaml
  multicluster/config/overlays/leader/prefix_transformer.yaml
  multicluster/config/overlays/leader/role.yaml
  multicluster/config/overlays/leader/role_binding.yaml
  multicluster/config/overlays/leader/secret.yaml
  multicluster/config/overlays/leader/service_account.yaml
  multicluster/config/overlays/leader/webhook_patch.yaml
  multicluster/config/overlays/leader/webhook_rbac.yaml
  multicluster/hack/generate-manifest.sh
  pkg/antctl/raw/multicluster/deploy/deploy_helper.go
  pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
Labels: area/multi-cluster, action/release-note

#5365 Support Pod secondary interfaces on VLAN network
  cmd/antrea-agent/agent.go
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_linux_test.go
  pkg/agent/cniserver/secondary.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux_test.go
  pkg/agent/cniserver/server_windows_test.go
  pkg/agent/cniserver/sriov.go
  pkg/agent/secondarynetwork/cnipodcache/cache.go
  pkg/agent/secondarynetwork/cnipodcache/types.go
  pkg/agent/secondarynetwork/init.go
  pkg/agent/secondarynetwork/init_test.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  pkg/agent/secondarynetwork/podwatch/sriov.go
  pkg/agent/secondarynetwork/podwatch/testing/mock_podwatch.go
  pkg/agent/secondarynetwork/podwatch/types.go
  pkg/agent/util/net.go
  pkg/agent/util/net_test.go
Labels: area/component/cni, area/interface, area/ovs

#5416 Support creating extra Docker networks in kind tests
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
Labels: area/test/infra

#5377 Update Go to v1.21
  .github/workflows/go.yml
  CONTRIBUTING.md
  Makefile
  build/images/codegen/Dockerfile
  build/images/codegen/README.md
  build/images/deps/go-version
  build/images/test/Dockerfile
  cmd/antctl/main.go
  docs/prometheus-integration.md
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/windows/Install-DevTools.ps1
  multicluster/hack/update-codegen.sh
  multicluster/test/e2e/main_test.go
  pkg/agent/openflow/cookie/allocator_test.go
  pkg/flowaggregator/exporter/log.go
  test/e2e/antctl_test.go
  test/e2e/main_test.go
  test/e2e/performance_test.go
  test/integration/agent/net_test.go
Labels: action/release-note

#5419 Automated cherry pick of #5378: Refine the default flow in ARPSpoofGuardTable
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
Labels: kind/cherry-pick

#5420 Automated cherry pick of #5378: Refine the default flow in ARPSpoofGuardTable
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
Labels: kind/cherry-pick

#5421 Automated cherry pick of #5378: Refine the default flow in ARPSpoofGuardTable
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
Labels: kind/cherry-pick

#5424 Automated cherry pick of #5404: Fix controller issue in handling empty pod labels for
  multicluster/controllers/multicluster/member/labelidentity_controller.go
  multicluster/controllers/multicluster/member/labelidentity_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: kind/cherry-pick

#5423 Automated cherry pick of #5404: Fix controller issue in handling empty pod labels for
  multicluster/controllers/multicluster/member/labelidentity_controller.go
  multicluster/controllers/multicluster/member/labelidentity_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: kind/cherry-pick

#5422 Automated cherry pick of #5404: Fix controller issue in handling empty pod labels for
  multicluster/controllers/multicluster/member/labelidentity_controller.go
  multicluster/controllers/multicluster/member/labelidentity_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: kind/cherry-pick

#5417 Clean up code in pkg/antctl/command_message.go
  pkg/antctl/client.go
  pkg/antctl/command_message.go
  pkg/antctl/command_message_test.go
Labels: kind/cleanup, area/component/antctl

#5392 Uniform TCP and UDP DNS interception flows
  pkg/agent/metrics/prometheus.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/packetin.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/types/networkpolicy.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/testing/mock_openflow.go
Labels: action/backport, action/release-note

#5432 Automated cherry pick of #5392: Uniform DNS Interception
  pkg/agent/metrics/prometheus.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/packetin.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/types/networkpolicy.go
  pkg/ovs/openflow/interfaces.go
  pkg/ovs/openflow/ofctrl_builder.go
  pkg/ovs/openflow/testing/mock_openflow.go
Labels: kind/cherry-pick

#5435 Fix antctl proxy not using user specified port
  pkg/antctl/raw/proxy/command.go
Labels: area/component/antctl, action/release-note

#5434 Do not attempt to join Windows agents to memberlist cluster
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: area/transit/egress, action/backport, action/release-note

#5439 Automated cherry pick of #5435: Fix antctl proxy not using user specified port
  pkg/antctl/raw/proxy/command.go
Labels: kind/cherry-pick

#5375 Add Namespace field selector in cache to filter Gateway and ClusterSet
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/controllers/multicluster/member/clusterset_controller.go
Labels: area/multi-cluster

#5335 Optimize getting routes function for Windows
  pkg/agent/agent_windows.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/net_windows_test.go
Labels: area/OS/windows

#5445 Automated cherry pick of #5434: Do not attempt to join Windows agents to memberlist cluster
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: kind/cherry-pick

#5444 Automated cherry pick of #5434: Do not attempt to join Windows agents to memberlist cluster
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: kind/cherry-pick

#5442 Automated cherry pick of #5434: Do not attempt to join Windows agents to memberlist cluster
  pkg/agent/memberlist/cluster.go
  pkg/agent/memberlist/cluster_test.go
Labels: kind/cherry-pick

#5449 Handle stale LabelIdentities created for empty Pod labels correctly after upgrade
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: action/backport

#5380 Add Namespaced Group Membership API
  hack/update-codegen-dockerized.sh
  pkg/apis/controlplane/register.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/register.go
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go
  pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go
  pkg/apiserver/registry/networkpolicy/groupmember/rest.go
  pkg/apiserver/registry/networkpolicy/groupmember/rest_test.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_groupmembers.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/generated_expansion.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/groupmembers.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/group.go
  pkg/controller/networkpolicy/group_test.go
Labels: area/api

#5452 Automated cherry pick of #5449: Handle stale LabelIdentities created for empty Pod labels
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: kind/cherry-pick

#5441 Clean up parameters of constructors
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  pkg/agent/cniserver/ipam/antrea_ipam_controller.go
  pkg/agent/cniserver/ipam/antrea_ipam_test.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/nodeportlocal/npl_agent_init.go
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
  pkg/controller/ipam/antrea_ipam_controller.go
  pkg/controller/ipam/antrea_ipam_controller_test.go
Labels: kind/cleanup

#5275 Add NSX VPC jobs to the Jenkins pipeline
  ci/jenkins/jobs/projects-lab.yaml
Labels: area/test/e2e

#5456 Fix burst of PacketInQueue
  pkg/ovs/openflow/ofctrl_bridge.go
  pkg/ovs/openflow/ofctrl_bridge_test.go
Labels: area/network-policy, action/backport, action/release-note

#5458 Automated cherry pick of #5449: Handle stale LabelIdentities created for empty Pod labels
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: kind/cherry-pick

#5459 Automated cherry pick of #5449: Handle stale LabelIdentities created for empty Pod labels
  multicluster/controllers/multicluster/stale_controller.go
  multicluster/controllers/multicluster/stale_controller_test.go
  pkg/controller/labelidentity/label_group_index.go
  pkg/controller/labelidentity/label_group_index_test.go
Labels: kind/cherry-pick

#5437 Automated cherry pick of #5409: Enable IPv6 on OVS internal port if needed in bridging mode
  pkg/agent/agent_linux.go
  pkg/agent/agent_linux_test.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows_test.go
  pkg/agent/util/net_linux.go
  pkg/agent/util/sysctl/sysctl_linux.go
Labels: kind/cherry-pick

#5460 Increase Rate-limit config
  pkg/agent/openflow/packetin.go
Labels: action/backport, action/release-note
