Repository antrea-io/antrea, pull requests merged in 2024-11, with the labels that each got.

#6257 Add packetcapture api
  build/charts/antrea/crds/packetcapture.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/api.md
  pkg/apis/crd/v1alpha1/register.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_packetcapture.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/packetcapture.go
  pkg/client/informers/externalversions/crd/v1alpha1/interface.go
  pkg/client/informers/externalversions/crd/v1alpha1/packetcapture.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/crd/v1alpha1/expansion_generated.go
  pkg/client/listers/crd/v1alpha1/packetcapture.go
Labels: api-review, kind/api-change, action/release-note

#6521 Migrate kind jobs to the cloud Jenkins
  CONTRIBUTING.md
  ci/jenkins/jobs/projects-cloud.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test.sh
Labels: area/test/infra, area/test/jenkins

#6756 Add packetcatpure feature
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/crds/packetcapture.yaml
  build/charts/antrea/templates/agent/clusterrole.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  docs/feature-gates.md
  docs/packetcapture-guide.md
  go.mod
  go.sum
  hack/.notableofcontents
  pkg/agent/packetcapture/capture/bpf.go
  pkg/agent/packetcapture/capture/bpf_test.go
  pkg/agent/packetcapture/capture/pcap_linux.go
  pkg/agent/packetcapture/capture/pcap_windows.go
  pkg/agent/packetcapture/capture_interface.go
  pkg/agent/packetcapture/packetcapture_controller.go
  pkg/agent/packetcapture/packetcapture_controller_test.go
  pkg/agent/supportbundlecollection/support_bundle_controller_test.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
  test/e2e/packetcapture_test.go
Labels: action/release-note

#6816 Bump github.com/gammazero/deque to v1.0.0
  go.mod
  go.sum
  pkg/flowaggregator/clickhouseclient/clickhouseclient.go
  pkg/flowaggregator/clickhouseclient/clickhouseclient_test.go
Labels: area/dependency

#6804 Fix PacketCapture pcapng file issue on macOS
  pkg/agent/packetcapture/capture/pcap_linux.go
  pkg/agent/packetcapture/capture/pcap_unsupported.go
  pkg/agent/packetcapture/capture_interface.go
  pkg/agent/packetcapture/packetcapture_controller.go
  pkg/agent/packetcapture/packetcapture_controller_test.go
  test/e2e/packetcapture_test.go
Labels: kind/bug, action/backport, action/release-note

#6826 Automated cherry pick of #6823: Fix race condition when getting BGP routes in BGPController
  pkg/agent/controller/bgp/controller.go
Labels: kind/cherry-pick

#6716 Migrate flxible-ipam job to the cloud Jenkins
  ci/jenkins/jobs/projects-cloud.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/kind/kind-setup.sh
Labels: area/test/infra, area/test/jenkins
