Repository antrea-io/antrea, pull requests merged in 2024-06, with the labels that each got.

#6389 Add recommend usage of FQDN policies
  docs/antrea-network-policy.md
Labels: kind/documentation, action/backport

#6388 Improve Docker build for FlowAggregator image
  build/images/flow-aggregator/Dockerfile
  build/images/flow-aggregator/Dockerfile.coverage
Labels: area/build-release, area/flow-visibility/aggregator

#6342 Delay removal of flow-restore-wait
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/controller/noderoute/node_route_controller.go
  pkg/agent/controller/noderoute/node_route_controller_test.go
  test/e2e/connectivity_test.go
  test/integration/agent/cniserver_test.go
Labels: action/release-note

#6394 Update kube version in helm charts
  build/charts/antrea/Chart.yaml
  build/charts/flow-aggregator/Chart.yaml
Labels: action/backport

#6391 Antrea version update for rancher
  docs/kubernetes-installers.md
Labels: kind/documentation

#6387 Fix kubectl cp failure with wildcard
  ci/jenkins/test-mc.sh
  ci/jenkins/test-vmc.sh
Labels: size/S

#6321 Remove unexpected AltName after rename interface
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_linux_test.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
Labels: area/OS/linux, kind/bug, area/interface, action/backport, action/release-note

#5295 Handle unexpected error when the test is aborted
  ci/jenkins/test-rancher.sh
  ci/jenkins/test-vmc.sh
  ci/jenkins/test.sh
Labels: area/test/e2e, size/S

#6259 Fix antrea-agent crashing with proxyAll enabled in networkPolicyOnly mode
  pkg/agent/agent.go
  pkg/agent/route/route_linux.go
Labels: action/backport, action/release-note

#6406 Automated cherry pick of #6193: Fix that AntreaProxy could unintentionally delete conntrack
  go.mod
  go.sum
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  test/integration/agent/cniserver_test.go
Labels: kind/cherry-pick

#6404 Automated cherry pick of #6193: Fix that AntreaProxy could unintentionally delete conntrack
  go.mod
  go.sum
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  test/integration/agent/cniserver_test.go
Labels: kind/cherry-pick

#6405 Automated cherry pick of #6193: Fix that AntreaProxy could unintentionally delete conntrack
  go.mod
  go.sum
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  test/integration/agent/cniserver_test.go
Labels: kind/cherry-pick

#6410 Automated cherry pick of #6259: Fix antrea-agent crashing with proxyAll enabled in
  pkg/agent/agent.go
  pkg/agent/route/route_linux.go
Labels: kind/cherry-pick

#6408 Automated cherry pick of #6259: Fix antrea-agent crashing with proxyAll enabled in
  pkg/agent/agent.go
  pkg/agent/route/route_linux.go
Labels: kind/cherry-pick

#6409 Automated cherry pick of #6259: Fix antrea-agent crashing with proxyAll enabled in
  pkg/agent/agent.go
  pkg/agent/route/route_linux.go
Labels: kind/cherry-pick

#6379 Fix AntreaProxy not deleting stale UDP conntrack entries for the virtual NodePort DNAT IP
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
Labels: area/proxy, action/backport, action/release-note

#6413 antctl: minor improvements about error message and CI
  .github/workflows/kind.yml
  pkg/antctl/raw/check/installation/command.go
  pkg/antctl/raw/check/installation/command_test.go
Labels: kind/cleanup

#6407 Fix racy unit test TestIdAllocatorWorker
  pkg/agent/controller/networkpolicy/allocator_test.go
Labels: area/test

#6417 Automated cherry pick of #6379: Fix AntreaProxy not deleting stale UDP conntrack entries for
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
Labels: kind/cherry-pick

#6416 Automated cherry pick of #6379: Fix AntreaProxy not deleting stale UDP conntrack entries for
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/proxier_test.go
Labels: kind/cherry-pick

#6402 Automated cherry pick of #6321: Remove unexpected AltName after rename interface (#6321)
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_linux_test.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
Labels: kind/cherry-pick

#6401 Automated cherry pick of #6321: Remove unexpected AltName after rename interface (#6321)
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_linux_test.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
Labels: kind/cherry-pick

#6360 Use helm to generate Antrea Windows manifests
  Makefile
  build/charts/antrea-windows/.helmignore
  build/charts/antrea-windows/Chart.yaml
  build/charts/antrea-windows/README.md
  build/charts/antrea-windows/conf/Install-WindowsCNI.ps1
  build/charts/antrea-windows/conf/Run-AntreaAgent.ps1
  build/charts/antrea-windows/conf/antrea-agent.conf
  build/charts/antrea-windows/conf/antrea-cni.conflist
  build/charts/antrea-windows/conf/ovs/Install-OVSDriver.ps1
  build/charts/antrea-windows/conf/ovs/Run-AntreaOVS.ps1
  build/charts/antrea-windows/conf/ovs/VMSwitchExtension-AntreaAgent.ps1
  build/charts/antrea-windows/templates/configmaps/antrea-agent-windows.yaml
  build/charts/antrea-windows/templates/configmaps/antrea-windows-config.yaml
  build/charts/antrea-windows/templates/daemonset.yaml
  build/charts/antrea-windows/values.yaml
  build/yamls/antrea-windows-with-ovs.yml
  build/yamls/antrea-windows.yml
  build/yamls/windows/base/kustomization.yml
  build/yamls/windows/containerd-with-ovs/containerd-with-ovs.yml
  build/yamls/windows/containerd-with-ovs/kustomization.yml
  build/yamls/windows/containerd/agent-containerd.yml
  build/yamls/windows/containerd/kustomization.yml
  build/yamls/windows/patches/dev/imagePullPolicy.yml
  build/yamls/windows/patches/release/.gitignore
  hack/generate-manifest-windows.sh
  hack/update-checksum-windows.sh
Labels: area/OS/windows

#6434 Automated cherry pick of #6402: Remove unexpected AltName after rename interface (#6321)
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_linux_test.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
Labels: kind/cherry-pick

#6420 Refactor pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/proxier_test.go
Labels: area/test

#6431 Do not log the whole Service object in log messages
  pkg/antctl/raw/check/installation/test_podtoservice.go
Labels: kind/cleanup

#6439 Automated cherry pick of #6368: Add Docker login to Jenkins script to avoid rate limit issue
  ci/jenkins/docker_login.sh
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-cloud.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#6440 Automated cherry pick of #6368: Add Docker login to Jenkins script to avoid rate limit issue
  ci/jenkins/docker_login.sh
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-cloud.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test-vmc.sh
Labels: kind/cherry-pick

#6372 Promote feature CleanupStaleUDPSvcConntrack from Alpha to Beta
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/feature-gates.md
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
Labels: action/release-note

#6429 Add unit tests for NodeLatencyMonitor
  hack/update-codegen-dockerized.sh
  pkg/agent/monitortool/latency_store.go
  pkg/agent/monitortool/monitor.go
  pkg/agent/monitortool/monitor_test.go
  pkg/agent/monitortool/testing/mock_monitortool.go
  pkg/agent/util/nettest/packetconn.go
Labels: area/test

#6010 Run Multiple Kind CI Jobs on a single testbed
  Makefile
  build/images/base/build.sh
  build/images/ovs/build.sh
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/test.sh
  hack/build-antrea-linux-all.sh
  hack/generate-manifest.sh
Labels: kind/design, area/test/infra, area/test/jenkins

#6436 Fix dependency of flowRestoreCompleteWait on podNetworkWait
  cmd/antrea-agent/agent.go
Labels: kind/bug

#6451 Automated cherry pick of #6264: Skip IPSec/WireGuard e2e test when the Multicast feature is
  test/e2e/fixtures.go
  test/e2e/ipsec_test.go
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#6450 Automated cherry pick of #5937: Update BuildKit Configurations to Enhance Compatibility
  ci/jenkins/test-mc.sh
  ci/jenkins/test-rancher.sh
  ci/jenkins/test-vmc.sh
  ci/jenkins/test.sh
  ci/jenkins/utils.sh
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
  docs/minikube.md
  hack/build-antrea-linux-all.sh
Labels: kind/cherry-pick

#6452 Fix manifest generation step for e2e test
  ci/jenkins/test.sh
Labels: kind/bug

#6009 Add BGPPolicy API
  build/charts/antrea/crds/bgppolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/apis/crd/v1alpha1/register.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/bgppolicy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_bgppolicy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/crd/v1alpha1/bgppolicy.go
  pkg/client/informers/externalversions/crd/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/crd/v1alpha1/bgppolicy.go
  pkg/client/listers/crd/v1alpha1/expansion_generated.go
Labels: area/api, kind/feature, area/component/agent, action/release-note, area/transit/bgp

#6444 [FlowAggregator e2e tests] Collect logs when setup fails
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: kind/failing-test, area/flow-visibility

#6461 [Flaky unit test] Fix TestEndpointResolver
  pkg/agent/client/endpoint_resolver_test.go
Labels: area/test, kind/failing-test

#6466 Automated cherry pick of #6264: Skip IPSec/WireGuard e2e test when the Multicast feature is
  test/e2e/fixtures.go
  test/e2e/ipsec_test.go
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#6475 Upgrade CNI plugins from v1.4.0 to v1.5.1
  build/images/deps/cni-binaries-version
Labels: action/backport

#6472 Wait for OVS bridge datapath ID to be available after creating br-int
  pkg/agent/agent.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  test/integration/ovs/ovs_client_test.go
Labels: action/release-note

#6485 Automated cherry pick of #6337: Fix mingw download in base Windows image (#6337)
  build/images/base-windows/Dockerfile
Labels: kind/cherry-pick

#6484 Automated cherry pick of #6475: Upgrade CNI plugins from v1.4.0 to v1.5.1 (#6475)
  build/images/deps/cni-binaries-version
Labels: kind/cherry-pick

#6447 Add BGP datapath interface and implement goBGP integration
  go.mod
  go.sum
  hack/update-codegen-dockerized.sh
  pkg/agent/bgp/gobgp/gobgp.go
  pkg/agent/bgp/gobgp/gobgp_test.go
  pkg/agent/bgp/gobgp/logs.go
  pkg/agent/bgp/interface.go
  pkg/agent/bgp/testing/mock_bgp.go
  test/integration/agent/gobgp_test.go
Labels: action/release-note, area/transit/bgp

#6480 Support shared LoadBalancerIP for multiple Services
  docs/service-loadbalancer.md
  pkg/agent/types/annotations.go
  pkg/controller/serviceexternalip/controller.go
  pkg/controller/serviceexternalip/controller_test.go
  test/e2e/framework.go
  test/e2e/service_externalip_test.go
Labels: action/release-note

#6383 [Windows] Optimize the containerized OVS installation
  build/charts/antrea-windows/conf/Run-AntreaAgent.ps1
  build/charts/antrea-windows/conf/ovs/Install-OVSDriver.ps1
  build/charts/antrea-windows/conf/ovs/Run-AntreaOVS.ps1
  build/images/Dockerfile.build.windows
  build/yamls/antrea-windows-with-ovs.yml
  build/yamls/antrea-windows.yml
  ci/jenkins/test.sh
  docs/windows.md
  hack/windows/Install-OVS.ps1
  hack/windows/Uninstall-OVS.ps1
Labels: area/OS/windows
