Repository antrea-io/antrea, pull requests merged in 2024-02, with the labels that each got.

#5954 Fix race condition in agent Traceflow controller
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
Labels: area/ops/traceflow, action/backport, action/release-note

#5957 Fix image information in docs and scripts
  docs/external-node.md
  docs/kind.md
  docs/minikube.md
  hack/externalnode/install-vm.sh
  test/e2e/README.md
Labels: action/backport

#5955 Persist TLS certificate and key of antrea-controller
  build/charts/antrea/templates/controller/clusterrole.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  multicluster/cmd/multicluster-controller/controller.go
  multicluster/cmd/multicluster-controller/controller_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/certificate/cacert_controller.go
  pkg/apiserver/certificate/cacert_controller_test.go
  pkg/apiserver/certificate/certificate.go
  pkg/apiserver/certificate/certificate_test.go
  pkg/apiserver/certificate/config.go
  pkg/apiserver/certificate/selfsignedcert_provider.go
  pkg/apiserver/certificate/selfsignedcert_provider_test.go
  pkg/util/env/env.go
  test/e2e/security_test.go
Labels: action/release-note

#5973 Automated cherry pick of #5971: Update NodeNetworkPolicy document example case (#5971)
  docs/antrea-node-network-policy.md
Labels: kind/cherry-pick

#5949 Add EgressNode field in Traceflow observation
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/apis/crd/v1beta1/types.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/querier/querier.go
  pkg/querier/testing/mock_querier.go
  test/e2e/traceflow_test.go
Labels: area/ops/traceflow, action/release-note

#5745 Add e2e test for VLAN secondary network
  .github/workflows/kind.yml
  build/charts/antrea/conf/antrea-agent.conf
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  ci/kind/test-secondary-network-kind.sh
  hack/generate-manifest.sh
  test/e2e-secondary-network/framework.go
  test/e2e-secondary-network/infra/prepare_cluster.sh
  test/e2e-secondary-network/infra/prepare_sriov.sh
  test/e2e-secondary-network/infra/secondary-network-configuration.yml
  test/e2e-secondary-network/infra/secondary-networks.yml
  test/e2e-secondary-network/infra/virtual-network-instance-crd.yml
  test/e2e-secondary-network/main_test.go
  test/e2e-secondary-network/secondary_network_test.go
  test/e2e/antctl_test.go
  test/e2e/bandwidth_test.go
  test/e2e/connectivity_test.go
  test/e2e/egress_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/main_test.go
  test/e2e/performance_test.go
  test/e2e/proxy_test.go
Labels: area/test/e2e, area/secondary-network

#5997 Use 65000 MTU upper bound for interfaces in encap mode
  pkg/agent/agent.go
Labels: kind/bug, action/backport, action/release-note

#5979 Skip loading openvswitch Kernel module if built-in
  build/charts/antrea/README.md
  build/charts/antrea/templates/agent/daemonset.yaml
  build/charts/antrea/values.yaml
  build/images/scripts/install_cni
  build/images/scripts/install_cni_chaining
  build/images/scripts/module_utils
  build/images/scripts/start_ovs
Labels: action/backport, action/release-note

#6002 Clean up deprecated APIServices
  build/charts/antrea/templates/controller/clusterrole.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/apiserver/apiserver.go
Labels: kind/cleanup, action/release-note

#6007 Automated cherry pick of #5979: Skip loading openvswitch Kernel module if built-in (#5979)
  build/charts/antrea/README.md
  build/charts/antrea/templates/agent/daemonset.yaml
  build/charts/antrea/values.yaml
  build/images/scripts/install_cni
  build/images/scripts/install_cni_chaining
  build/images/scripts/module_utils
  build/images/scripts/start_ovs
Labels: kind/cherry-pick

#6005 Automated cherry pick of #5997: Use 65000 MTU upper bound for interfaces in encap mode
  pkg/agent/agent.go
Labels: kind/cherry-pick

#6006 Automated cherry pick of #5997: Use 65000 MTU upper bound for interfaces in encap mode
  pkg/agent/agent.go
Labels: kind/cherry-pick

#6004 Fix race condition in pkg/apiserver/certificate unit tests
  pkg/apiserver/certificate/selfsignedcert_provider.go
  pkg/apiserver/certificate/selfsignedcert_provider_test.go
Labels: kind/failing-test

#6016 Automated cherry pick of #5942: Update maximum number of buckets in an OVS group message
  go.mod
  go.sum
  pkg/agent/openflow/multicast.go
  pkg/agent/openflow/multicast_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
  pkg/ovs/openflow/ofctrl_group.go
Labels: kind/cherry-pick

#6017 Automated cherry pick of #5942: Update maximum number of buckets in an OVS group message
  go.mod
  go.sum
  pkg/agent/openflow/multicast.go
  pkg/agent/openflow/multicast_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
  pkg/ovs/openflow/ofctrl_group.go
Labels: kind/cherry-pick

#5989 Refactor Endpoint Query Controller and Antctl
  pkg/antctl/antctl.go
  pkg/antctl/command_definition.go
  pkg/antctl/command_definition_test.go
  pkg/antctl/output/output.go
  pkg/antctl/output/output_test.go
  pkg/apiserver/handlers/endpoint/handler.go
  pkg/apiserver/handlers/endpoint/handler_test.go
  pkg/controller/networkpolicy/endpoint_querier.go
  pkg/controller/networkpolicy/endpoint_querier_perf_test.go
  pkg/controller/networkpolicy/endpoint_querier_test.go
  pkg/controller/networkpolicy/testing/mock_networkpolicy.go
  pkg/controller/types/networkpolicy.go
Labels: area/component/antctl

#6025 Add more information about Colima
  docs/contributors/docker-desktop-alternatives.md
Labels: kind/documentation

#6015 Add user document for Antrea native secondary network support
  docs/antrea-ipam.md
  docs/secondary-network.md
  hack/.notableofcontents
Labels: kind/documentation, area/secondary-network

#6026 RegisterPacketInHandler should not use empty interface as parameter
  hack/update-codegen-dockerized.sh
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/externalnode_connectivity_test.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/operations/operations.go
  pkg/agent/openflow/operations/testing/mock_operations.go
  pkg/agent/openflow/packetin.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_test.go
  pkg/agent/openflow/testing/mock_openflow.go
Labels: kind/cleanup

#6038 Reduce antrea cni binary size
  pkg/agent/secondarynetwork/podwatch/sriov.go
  pkg/agent/util/net.go
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_windows.go
  pkg/cni/client.go
  pkg/cni/dial_linux.go
  pkg/cni/dial_windows.go
Labels: kind/cleanup, action/release-note
