Repository antrea-io/antrea, pull requests merged in 2024-01, with the labels that each got.

#5829 Replace curl with built-in Invoke-WebRequest on Windows
  build/images/base-windows/Dockerfile
Labels: area/OS/windows, size/XS

#5765 Record an event when Egress IP assignment changes
  build/charts/antrea/templates/agent/clusterrole.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/serviceexternalip/controller.go
  pkg/agent/ipassigner/ip_assigner.go
  pkg/agent/ipassigner/ip_assigner_linux.go
  pkg/agent/ipassigner/testing/mock_ipassigner.go
  test/e2e/egress_test.go
  test/integration/agent/ip_assigner_linux_test.go
Labels: area/transit/egress, action/release-note

#5813 Upgrade CNI plugins from v1.3.0 to v1.4.0
  build/images/deps/cni-binaries-version
Labels: size/XS

#5807 Update ROADMAP
  README.md
  ROADMAP.md
Labels: kind/documentation

#5833 Enable IPv4/IPv6 forwarding on demand automatically
  pkg/agent/route/route_linux.go
Labels: action/release-note

#5836 Automated cherry pick of #5819: Add DHCP IP Retries in PrepareHNSNetwork
  ci/jenkins/test.sh
  pkg/agent/util/net_windows.go
  pkg/agent/util/net_windows_test.go
Labels: kind/cherry-pick

#5835 Automated cherry pick of #5819: Add DHCP IP Retries in PrepareHNSNetwork
  ci/jenkins/test.sh
  pkg/agent/util/net_windows.go
  pkg/agent/util/net_windows_test.go
Labels: kind/cherry-pick

#5830 Update NetworkPolicy version to v1beta1 in documents
  docs/antrea-l7-network-policy.md
  docs/antrea-network-policy.md
  docs/design/ovs-pipeline.md
  docs/external-node.md
  docs/multicluster/user-guide.md
Labels: kind/documentation, action/backport

#5799 Support Egress using IPs from a separate subnet
  .github/workflows/kind.yml
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/crds/externalippool.yaml
  build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  cmd/antrea-agent/agent.go
  docs/egress.md
  docs/feature-gates.md
  pkg/agent/controller/egress/egress_controller.go
  pkg/agent/controller/egress/egress_controller_test.go
  pkg/agent/controller/serviceexternalip/controller.go
  pkg/agent/controller/serviceexternalip/controller_test.go
  pkg/agent/ipassigner/ip_assigner.go
  pkg/agent/ipassigner/ip_assigner_linux.go
  pkg/agent/ipassigner/testing/mock_ipassigner.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/testing/mock_route.go
  pkg/agent/types/net.go
  pkg/agent/util/net_linux.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
  pkg/apis/crd/v1beta1/types.go
  pkg/apis/crd/v1beta1/util.go
  pkg/apis/crd/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/externalippool/validate.go
  pkg/controller/externalippool/validate_test.go
  pkg/features/antrea_features.go
  test/e2e/egress_test.go
  test/e2e/framework.go
  test/e2e/main_test.go
  test/e2e/service_externalip_test.go
  test/integration/agent/ip_assigner_linux_test.go
  test/integration/agent/openflow_test.go
Labels: action/release-note

#5839 Update windows ovs download link to remove the redundant certificate
  hack/windows/Install-OVS.ps1
Labels: action/backport

#5848 Automated cherry pick of #5839: Update windows ovs download link to remove the redundant
  hack/windows/Install-OVS.ps1
Labels: kind/cherry-pick

#5847 Automated cherry pick of #5839: Update windows ovs download link to remove the redundant
  hack/windows/Install-OVS.ps1
Labels: kind/cherry-pick

#5826 Use recommended 'inputs' context in github workflows
  .github/workflows/docker_update_base_windows.yml
  .github/workflows/trivy_scan.yml
Labels: size/XS

#5838 Fix antctl trace-packet arguments missing issue
  pkg/agent/apiserver/handlers/ovstracing/handler.go
  pkg/agent/apiserver/handlers/ovstracing/handler_test.go
  pkg/ovs/ovsctl/appctl.go
  pkg/ovs/ovsctl/ovsctl.go
Labels: size/XS, action/backport, action/release-note

#5858 Add missing space for kubelet args in Prepare-Node.ps1
  hack/windows/Prepare-Node.ps1
Labels: action/backport, action/release-note

#5864 Automated cherry pick of #5858: Add missing space for kubelet args in Prepare-Node.ps1
  hack/windows/Prepare-Node.ps1
Labels: kind/cherry-pick

#5863 Automated cherry pick of #5858: Add missing space for kubelet args in Prepare-Node.ps1
  hack/windows/Prepare-Node.ps1
Labels: kind/cherry-pick

#5859 Fix Clean-AntreaNetwork.ps1 invocation in Prepare-AntreaAgent.ps1
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Prepare-AntreaAgent.ps1
Labels: action/backport, action/release-note

#5865 Automated cherry pick of #5859: Fix Clean-AntreaNetwork.ps1 invocation in
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Prepare-AntreaAgent.ps1
Labels: kind/cherry-pick

#5866 Automated cherry pick of #5859: Fix Clean-AntreaNetwork.ps1 invocation in
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Prepare-AntreaAgent.ps1
Labels: kind/cherry-pick

#5870 Automated cherry pick of #5838: Fix antctl trace-packet arguments missing issue
  pkg/agent/apiserver/handlers/ovstracing/handler.go
  pkg/agent/apiserver/handlers/ovstracing/handler_test.go
  pkg/ovs/ovsctl/appctl.go
  pkg/ovs/ovsctl/ovsctl.go
Labels: kind/cherry-pick

#5871 Automated cherry pick of #5838: Fix antctl trace-packet arguments missing issue
  pkg/agent/apiserver/handlers/ovstracing/handler.go
  pkg/agent/apiserver/handlers/ovstracing/handler_test.go
  pkg/ovs/ovsctl/appctl.go
  pkg/ovs/ovsctl/ovsctl.go
Labels: kind/cherry-pick

#5872 Automated cherry pick of #5830: Update NetworkPolicy version to v1beta1 in documents
  docs/antrea-l7-network-policy.md
  docs/antrea-network-policy.md
  docs/design/ovs-pipeline.md
  docs/external-node.md
  docs/multicluster/user-guide.md
Labels: kind/cherry-pick

#5873 Automated cherry pick of #5830: Update NetworkPolicy version to v1beta1 in documents
  docs/antrea-l7-network-policy.md
  docs/antrea-network-policy.md
  docs/design/ovs-pipeline.md
  docs/external-node.md
  docs/multicluster/user-guide.md
Labels: kind/cherry-pick

#5658 Add support for NodeNetworkPolicy datapath
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  docs/antrea-network-policy.md
  docs/antrea-node-network-policy.md
  docs/feature-gates.md
  multicluster/test/e2e/antreapolicy_test.go
  pkg/agent/config/node_config.go
  pkg/agent/controller/networkpolicy/cache.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
  pkg/agent/controller/networkpolicy/node_reconciler_unsupported.go
  pkg/agent/controller/networkpolicy/pod_reconciler.go
  pkg/agent/controller/networkpolicy/pod_reconciler_test.go
  pkg/agent/route/interfaces.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/route/testing/mock_route.go
  pkg/agent/types/networkpolicy.go
  pkg/agent/util/iptables/builder.go
  pkg/agent/util/iptables/builder_test.go
  pkg/agent/util/iptables/iptables.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
  test/e2e/antreaipam_anp_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/k8s_util.go
  test/e2e/nodenetworkpolicy_test.go
  test/e2e/utils/cnp_spec_builder.go
  test/integration/agent/route_test.go
Labels: action/release-note

#5677 Add script for migrating from other CNI to Antrea
  .github/workflows/build.yml
  Makefile
  build/images/Dockerfile.build.migrator
  build/images/scripts/migrate_cni
  build/yamls/antrea-migrator.yml
  docs/migrate-to-antrea.md
  hack/.notableofcontents
Labels: action/release-note

#5789 Update Windows documentation
  docs/design/windows-design.md
  docs/windows.md
Labels: area/OS/windows, kind/documentation

#5884 Update docs and clients with latest API versions
  docs/api.md
  docs/service-loadbalancer.md
  test/e2e/antreapolicy_test.go
Labels: size/XS

#5885 Don't create tunnel interface (antrea-tun0) when using Wireguard
  pkg/agent/config/node_config.go
Labels: action/release-note

#5897 Some minor updates to Architecture documentation
  docs/design/architecture.md
Labels: kind/documentation, size/XS

#5912 e2e: Fix the wrong expectation of Traceflow observation
  test/e2e/traceflow_test.go
Labels: area/test/e2e

#5901 Add instructions to install Antrea in encap mode in AKS
  docs/aks-installation.md
Labels: area/provider/azure, kind/documentation, action/release-note

#5880 Fix incorrect MTU configurations
  cmd/antrea-agent/agent.go
  pkg/agent/agent.go
  pkg/agent/config/node_config.go
  pkg/agent/config/node_config_test.go
  pkg/agent/multicluster/mc_route_controller.go
  test/e2e-secondary-network/secondary_network_test.go
  test/e2e/antreaipam_test.go
  test/e2e/connectivity_test.go
  test/e2e/framework.go
  test/e2e/ipsec_test.go
  test/e2e/traceflow_test.go
  test/e2e/upgrade_test.go
  test/e2e/vmagent_test.go
  test/e2e/wireguard_test.go
Labels: action/backport, action/release-note

#5229 Support running Ginkgo in parallel on Windows testbeds
  ci/jenkins/test.sh
Labels: area/OS/windows

#5903 Modify workflows, ci and manifest scripts for split images
  .github/workflows/conformance.yml
  .github/workflows/kind.yml
  .github/workflows/trivy_scan_before_release.yml
  build/charts/antrea/README.md
  build/charts/antrea/templates/_helpers.tpl
  build/charts/antrea/templates/agent/daemonset.yaml
  build/charts/antrea/templates/controller/deployment.yaml
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  ci/jenkins/mellanox/scripts/start_ci.sh
  ci/jenkins/test-mc.sh
  ci/jenkins/test-rancher.sh
  ci/jenkins/test-vm.sh
  ci/jenkins/test-vmc.sh
  ci/jenkins/test.sh
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  ci/kind/test-netpol-v2-conformance-kind.sh
  ci/kind/test-upgrade-antrea.sh
  ci/test-conformance-aks.sh
  ci/test-conformance-eks.sh
  ci/test-conformance-gke.sh
  hack/externalnode/install-vm.sh
  hack/generate-helm-release.sh
  hack/generate-manifest.sh
  hack/generate-standard-manifests.sh
  hack/netpol-generator/test-kind.sh
  hack/release/prepare-assets.sh
  test/e2e/infra/vagrant/push_antrea.sh
Labels: action/release-note

#5934 Add a link to CHANGELOG-1.15
  CHANGELOG/README.md
Labels: action/backport

#5936 Automated cherry pick of #5934: Add a link to CHANGELOG-1.15 (#5934)
  CHANGELOG/README.md
Labels: kind/cherry-pick

#5898 Enhance ExternalIPPool validation
  cmd/antrea-controller/controller.go
  pkg/apiserver/apiserver.go
  pkg/controller/externalippool/validate.go
  pkg/controller/externalippool/validate_test.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
Labels: action/release-note

#5947 Refactor Windows CNI interface configuration
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_linux.go
  pkg/agent/cniserver/pod_configuration_windows.go
Labels: area/OS/windows, area/interface
