Repository antrea-io/antrea, pull requests merged in 2024-03, with the labels that each got.

#6042 Add important limitation to SecondaryNetwork document
  docs/secondary-network.md
Labels: kind/documentation, area/secondary-network

#6041 [e2e tests] Wait for secondary IPs before running ping test
  ci/kind/test-secondary-network-kind.sh
  test/e2e-secondary-network/secondary_network_test.go
Labels: area/test/e2e, area/secondary-network

#6050 [traceflow] Fix wrong TCP flags validation
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: kind/bug, area/ops/traceflow, action/backport, action/release-note

#5740 Add Versioned API and Antctl for NetworkPolicyEvaluation (effective policy rule prediction)
  README.md
  build/charts/antrea/templates/antctl/clusterrole.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/antctl.md
  docs/feature-gates.md
  docs/multicluster/user-guide.md
  docs/traceflow-guide.md
  hack/update-codegen-dockerized.sh
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/antctl/antctl.go
  pkg/antctl/client.go
  pkg/antctl/command_definition.go
  pkg/antctl/parameter/parameter.go
  pkg/antctl/parameter/parameter_test.go
  pkg/antctl/transform/networkpolicy/transform.go
  pkg/antctl/transform/networkpolicy/transform_test.go
  pkg/apis/controlplane/register.go
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/register.go
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/handlers/endpoint/handler.go
  pkg/apiserver/handlers/endpoint/handler_test.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/apiserver/registry/networkpolicy/networkpolicyevaluation/rest.go
  pkg/apiserver/registry/networkpolicy/networkpolicyevaluation/rest_test.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_controlplane_client.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_networkpolicyevaluation.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/generated_expansion.go
  pkg/client/clientset/versioned/typed/controlplane/v1beta2/networkpolicyevaluation.go
  pkg/controller/networkpolicy/endpoint_querier.go
  pkg/controller/networkpolicy/endpoint_querier_test.go
  pkg/controller/networkpolicy/testing/mock_networkpolicy.go
  pkg/controller/types/networkpolicy.go
Labels: area/component/antctl, action/release-note

#6055 Automated cherry pick of #6050: Fix wrong TCP flags validation (#6050)
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: kind/cherry-pick

#6056 Automated cherry pick of #6050: Fix wrong TCP flags validation (#6050)
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: kind/cherry-pick

#6057 Automated cherry pick of #6050: Fix wrong TCP flags validation (#6050)
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: kind/cherry-pick

#5998 Save secondary network interfaces in InterfaceStore
  pkg/agent/agent_test.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_linux.go
  pkg/agent/cniserver/pod_configuration_linux_test.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/secondary.go
  pkg/agent/cniserver/server_linux_test.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/cniserver/server_windows_test.go
  pkg/agent/interfacestore/interface_cache.go
  pkg/agent/interfacestore/interface_cache_test.go
  pkg/agent/interfacestore/types.go
  pkg/agent/secondarynetwork/cnipodcache/cache.go
  pkg/agent/secondarynetwork/cnipodcache/types.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  pkg/agent/secondarynetwork/podwatch/sriov.go
  pkg/agent/secondarynetwork/podwatch/testing/mock_podwatch.go
  pkg/agent/secondarynetwork/podwatch/types.go
  pkg/agent/util/net.go
Labels: area/interface, area/secondary-network

#6069 Automated cherry pick of #5954: Fix race condition in agent Traceflow controller (#5954)
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
Labels: kind/cherry-pick

#6070 Automated cherry pick of #5954: Fix race condition in agent Traceflow controller (#5954)
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
Labels: kind/cherry-pick

#6073 Stop using projects.registry.vmware.com for user-facing images
  ci/kind/test-upgrade-antrea.sh
  docs/kind.md
  hack/generate-helm-release.sh
  hack/release/prepare-assets.sh
Labels: area/build-release, action/backport, action/release-note

#6077 Fix nil pointer dereference when ClusterGroup/Group is used
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
  pkg/controller/types/networkpolicy.go
Labels: area/component/controller, area/network-policy, area/network-policy/controller, action/backport, action/release-note

#6082 Automated cherry pick of #6073: Stop using projects.registry.vmware.com for user-facing
  ci/kind/test-upgrade-antrea.sh
  docs/kind.md
  hack/generate-helm-release.sh
  hack/release/prepare-assets.sh
Labels: kind/cherry-pick

#6086 Automated cherry pick of #6077: Fix nil pointer dereference when ClusterGroup/Group is used
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
  pkg/controller/types/networkpolicy.go
Labels: kind/cherry-pick

#6087 Automated cherry pick of #6077: Fix nil pointer dereference when ClusterGroup/Group is used
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
  pkg/controller/types/networkpolicy.go
Labels: kind/cherry-pick

#6078 Remove unused index from AppliedToGroup and AddressGroup storages
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
Labels: kind/cleanup

#6088 Automated cherry pick of #6077: Fix nil pointer dereference when ClusterGroup/Group is used
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/controller/networkpolicy/store/addressgroup.go
  pkg/controller/networkpolicy/store/appliedtogroup.go
  pkg/controller/types/networkpolicy.go
Labels: kind/cherry-pick

#6048 Fix Improve log when agent fails to join a new Node
  pkg/agent/memberlist/cluster.go
Labels: kind/cleanup

#6083 Automated cherry pick of #6073: Stop using projects.registry.vmware.com for user-facing
  ci/kind/test-upgrade-antrea.sh
  docs/kind.md
  hack/generate-helm-release.sh
  hack/release/prepare-assets.sh
Labels: kind/cherry-pick

#6084 Automated cherry pick of #6073: Stop using projects.registry.vmware.com for user-facing
  ci/kind/test-upgrade-antrea.sh
  docs/kind.md
  hack/generate-helm-release.sh
  hack/release/prepare-assets.sh
Labels: kind/cherry-pick

#6093 Automated cherry pick of #6052: Fix log rotation in UBI images (#6052)
  build/images/ovs/Dockerfile.ubi
  test/e2e/basic_test.go
Labels: kind/cherry-pick

#6092 Automated cherry pick of #6052: Fix log rotation in UBI images (#6052)
  build/images/ovs/Dockerfile.ubi
  test/e2e/basic_test.go
Labels: kind/cherry-pick

#6100 Update the command to print OVS table names
  docs/antctl.md
Labels: kind/documentation

#4537 SameLabels support for ACNP peer Namespace selection
  build/charts/antrea/crds/clusternetworkpolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  multicluster/test/e2e/antreapolicy_test.go
  pkg/apis/crd/v1beta1/types.go
  pkg/apis/crd/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
  test/e2e/antreaipam_anp_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/clustergroup_test.go
  test/e2e/group_test.go
  test/e2e/k8s_util.go
  test/e2e/nodenetworkpolicy_test.go
  test/e2e/reachability.go
  test/e2e/utils/cnp_spec_builder.go
Labels: area/network-policy, action/release-note

#6128 Remove unnecessary code from UBI Dockerfiles
  build/images/Dockerfile.build.agent.ubi
  build/images/Dockerfile.build.controller.ubi
Labels: kind/cleanup, area/build-release

#6102 Support LoadBalancerIPMode in AntreaProxy
  pkg/agent/proxy/proxier_test.go
  pkg/agent/proxy/topology_test.go
  third_party/proxy/service.go
  third_party/proxy/util/utils.go
Labels: area/proxy, action/release-note

#6146 Automated cherry pick of #5988: Disable cgo for all Antrea binaries (#5988)
  Makefile
  build/images/Dockerfile.build.coverage
  build/images/Dockerfile.build.ubi
  build/images/Dockerfile.build.ubuntu
  hack/release/prepare-assets.sh
Labels: kind/cherry-pick

#6156 Fall back to lenient decoding when strict decoding config fails
  cmd/antrea-agent/options.go
  cmd/antrea-controller/options.go
  multicluster/cmd/multicluster-controller/options.go
  pkg/flowaggregator/options/options.go
  pkg/util/yaml/decode.go
  pkg/util/yaml/decode_test.go
  test/e2e/basic_test.go
Labels: action/release-note

#6123 [Bugfix] Install Multicast related iptables rules only on IPv4 chains
  cmd/antrea-agent/agent.go
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
Labels: action/backport, action/release-note

#6134 Remove deprecated ServiceAccount field in ClusterSet type
  multicluster/apis/multicluster/v1alpha2/clusterset_types.go
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader.yml
  multicluster/build/yamls/antrea-multicluster-member.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_clustersets.yaml
Labels: area/multi-cluster, action/release-note
