Repository antrea-io/antrea, pull requests merged in 2024-10, with the labels that each got.

#6680 Automated cherry pick of #6669: Add docker credentials to windows CI to avoid rate limit
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#6689 Add "antctl get bgppeers" agent command
  docs/antctl.md
  pkg/agent/apis/types.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/bgppeer/handler.go
  pkg/agent/apiserver/handlers/bgppeer/handler_test.go
  pkg/agent/controller/bgp/controller.go
  pkg/agent/controller/bgp/controller_test.go
  pkg/antctl/antctl.go
  pkg/antctl/command_list_test.go
  pkg/querier/querier.go
  pkg/querier/testing/mock_querier.go
Labels: area/component/antctl, action/release-note, area/transit/bgp

#6715 fix: fix slice init length
  pkg/controller/networkpolicy/store/group.go
Labels: kind/bug, area/network-policy

#6714 Always require the cluster UUID in the FlowAggregator
  cmd/flow-aggregator/flow-aggregator.go
  pkg/flowaggregator/cluster_uuid.go
  pkg/flowaggregator/cluster_uuid_test.go
  pkg/flowaggregator/exporter/clickhouse.go
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/exporter/ipfix_test.go
  pkg/flowaggregator/exporter/s3.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
Labels: area/flow-visibility/aggregator

#6713 Fix flaky TestSubscribe test in pkg/util/channel
  pkg/util/channel/channel_test.go
Labels: area/test

#6712 Update NodeLatencyMonitor unit tests
  pkg/agent/monitortool/monitor.go
  pkg/agent/monitortool/monitor_test.go
Labels: area/test

#6696 More robust system Tier creation / update
  pkg/apiserver/apiserver.go
  pkg/controller/networkpolicy/tier.go
  pkg/controller/networkpolicy/tier_test.go
Labels: kind/bug, action/backport, action/release-note

#6702 Fix flaky e2e test TestProxyLoadBalancerModeDSR
  test/e2e/proxy_test.go
Labels: area/test/e2e, kind/cleanup

#6707 Fix issue with ipset or iptables chain removal during NodeNetworkPolicy updates or deletions
  pkg/agent/controller/networkpolicy/node_reconciler_linux.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
Labels: action/backport, action/release-note

#6728 Automated cherry pick of #6707: Fix issue with ipset or iptables chain removal during
  pkg/agent/controller/networkpolicy/node_reconciler_linux.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
Labels: kind/cherry-pick

#6727 Automated cherry pick of #6707: Fix issue with ipset or iptables chain removal during
  pkg/agent/controller/networkpolicy/node_reconciler_linux.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
Labels: kind/cherry-pick

#6726 Automated cherry pick of #6707: Fix issue with ipset or iptables chain removal during
  pkg/agent/controller/networkpolicy/node_reconciler_linux.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
Labels: kind/cherry-pick

#6658 Add Except for Antrea-native ipBlock
  build/charts/antrea/crds/clustergroup.yaml
  build/charts/antrea/crds/clusternetworkpolicy.yaml
  build/charts/antrea/crds/group.yaml
  build/charts/antrea/crds/networkpolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  multicluster/build/yamls/antrea-multicluster-leader-global.yml
  multicluster/build/yamls/antrea-multicluster-leader.yml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
  multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
  pkg/apis/crd/v1beta1/types.go
  pkg/apis/crd/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clustergroup_test.go
  pkg/controller/networkpolicy/clusternetworkpolicy_test.go
  pkg/controller/networkpolicy/crd_utils.go
  pkg/controller/networkpolicy/crd_utils_test.go
  pkg/controller/networkpolicy/group.go
  pkg/controller/networkpolicy/group_test.go
  pkg/controller/networkpolicy/networkpolicy_controller.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
  pkg/controller/types/group.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/utils/cnp_spec_builder.go
Labels: kind/feature, area/network-policy, action/release-note

#6723 Automated cherry pick of #6696: More robust system Tier creation / update (#6696)
  pkg/apiserver/apiserver.go
  pkg/controller/networkpolicy/tier.go
  pkg/controller/networkpolicy/tier_test.go
Labels: kind/cherry-pick

#6724 Automated cherry pick of #6696: More robust system Tier creation / update (#6696)
  pkg/apiserver/apiserver.go
  pkg/controller/networkpolicy/tier.go
  pkg/controller/networkpolicy/tier_test.go
Labels: kind/cherry-pick

#6725 Automated cherry pick of #6696: More robust system Tier creation / update (#6696)
  pkg/apiserver/apiserver.go
  pkg/controller/networkpolicy/tier.go
  pkg/controller/networkpolicy/tier_test.go
Labels: kind/cherry-pick

#6626 Add `EnableLogging` and `LogLabel` supports for Node NetworkPolicy
  docs/antrea-node-network-policy.md
  pkg/agent/controller/networkpolicy/node_reconciler_linux.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
  pkg/agent/types/networkpolicy.go
  pkg/agent/util/iptables/builder.go
  pkg/agent/util/iptables/builder_test.go
  pkg/agent/util/iptables/iptables.go
  pkg/controller/networkpolicy/validate.go
  pkg/controller/networkpolicy/validate_test.go
  test/e2e/nodenetworkpolicy_test.go
Labels: action/release-note

#6699 [FlowAggregator] Add templateRefreshTimeout configuration
  build/charts/flow-aggregator/README.md
  build/charts/flow-aggregator/conf/flow-aggregator.conf
  build/charts/flow-aggregator/values.yaml
  build/yamls/flow-aggregator.yml
  pkg/agent/flowexporter/exporter/exporter.go
  pkg/agent/flowexporter/exporter/exporter_test.go
  pkg/config/flowaggregator/config.go
  pkg/config/flowaggregator/default.go
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/exporter/ipfix_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/options/options.go
Labels: area/flow-visibility/aggregator, action/release-note

#6666 [SecondaryNetwork] Fix agent crash if host interface is already attached to OVS bridge
  pkg/agent/util/net_linux.go
Labels: kind/bug, action/backport, action/release-note, area/secondary-network

#6737 Automated cherry pick of #6691: Run IPPool webhook handler when SecondaryNetwork is enabled.
  pkg/apiserver/apiserver.go
Labels: kind/cherry-pick

#6738 Automated cherry pick of #6691: Run IPPool webhook handler when SecondaryNetwork is enabled.
  pkg/apiserver/apiserver.go
Labels: kind/cherry-pick

#6744 Avoid error log when unmarshalling config for MC controller
  multicluster/cmd/multicluster-controller/options.go
  multicluster/cmd/multicluster-controller/options_test.go
  multicluster/embed.go
Labels: area/multi-cluster

#6673 Fix invalid conversion between unsafe.Pointer and uintptr
  pkg/agent/util/syscall/syscall_windows.go
  pkg/agent/util/syscall/syscall_windows_test.go
Labels: area/OS/windows, action/backport, action/release-note

#6750 Automated cherry pick of #6691: Run IPPool webhook handler when SecondaryNetwork is enabled.
  pkg/apiserver/apiserver.go
Labels: kind/cherry-pick

#6670 Automated cherry pick of #6664: Replace unsafe.Slice with memory copying to avoid potential
  pkg/agent/util/syscall/syscall_windows.go
  pkg/agent/util/syscall/syscall_windows_test.go
Labels: kind/cherry-pick

#6671 Automated cherry pick of #6664: Replace unsafe.Slice with memory copying to avoid potential
  pkg/agent/util/syscall/syscall_windows.go
  pkg/agent/util/syscall/syscall_windows_test.go
Labels: kind/cherry-pick

#6672 Automated cherry pick of #6664: Replace unsafe.Slice with memory copying to avoid potential
  pkg/agent/util/syscall/syscall_windows.go
  pkg/agent/util/syscall/syscall_windows_test.go
Labels: kind/cherry-pick

#6742 Update finalizer of ResourceExport to be domain-qualified
  multicluster/apis/multicluster/constants/constants.go
  multicluster/apis/multicluster/v1alpha1/resourceexport_webhook.go
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/leader/clusterinfo_export_handler.go
  multicluster/controllers/multicluster/leader/memberclusterannounce_controller.go
  multicluster/controllers/multicluster/leader/resourceexport_controller.go
  multicluster/controllers/multicluster/leader/resourceexport_controller_test.go
  multicluster/controllers/multicluster/leader/stale_controller.go
  multicluster/test/integration/resourceexport_controller_test.go
Labels: area/multi-cluster, action/release-note

#6758 Improve some Antrea IPAM unit tests
  pkg/controller/ipam/antrea_ipam_controller_test.go
Labels: area/test

#6734 Add "antctl get bgproutes" agent command
  docs/antctl.md
  pkg/agent/apis/types.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/bgproute/handler.go
  pkg/agent/apiserver/handlers/bgproute/handler_test.go
  pkg/agent/controller/bgp/controller.go
  pkg/agent/controller/bgp/controller_test.go
  pkg/antctl/antctl.go
  pkg/antctl/command_list_test.go
  pkg/querier/querier.go
  pkg/querier/testing/mock_querier.go
Labels: area/component/antctl, action/release-note, area/transit/bgp

#6486 Build Arm images from this repo using Github-hosted Arm runners
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  Makefile
  build/images/.gitignore
  build/images/Dockerfile.agent.ubuntu
  build/images/Dockerfile.build.agent.coverage
  build/images/Dockerfile.build.agent.ubi
  build/images/Dockerfile.build.agent.ubuntu
  build/images/Dockerfile.build.controller.coverage
  build/images/Dockerfile.build.controller.ubi
  build/images/Dockerfile.build.controller.ubuntu
  build/images/base/Dockerfile
  build/images/base/Dockerfile.ubi
  build/images/base/build.sh
  build/images/build-utils.sh
  build/images/ovs/build.sh
  build/images/test/Dockerfile
  hack/build-antrea-linux-all.sh
Labels: area/build-release

#6755 Add "ipv4-only" and "ipv6-only" flags for "antctl get bgppeers"
  docs/antctl.md
  pkg/agent/apiserver/handlers/bgppeer/handler.go
  pkg/agent/apiserver/handlers/bgppeer/handler_test.go
  pkg/agent/controller/bgp/controller.go
  pkg/agent/controller/bgp/controller_test.go
  pkg/antctl/antctl.go
  pkg/querier/querier.go
  pkg/querier/testing/mock_querier.go
Labels: area/component/antctl, action/release-note, area/transit/bgp
