Repository antrea-io/antrea, pull requests merged in 2024-04, with the labels that each got.

#6170 Automated cherry pick of #6163: Increase timeout to 15m for Multicluster e2e test (#6163)
  ci/jenkins/test-mc.sh
Labels: kind/cherry-pick

#6167 Automated cherry pick of #6163: Increase timeout to 15m for Multicluster e2e test (#6163)
  ci/jenkins/test-mc.sh
Labels: kind/cherry-pick

#6175 Automated cherry pick of #6123: Install Multicast related iptables rules only on
  cmd/antrea-agent/agent.go
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
Labels: kind/cherry-pick

#6174 Automated cherry pick of #6123: Install Multicast related iptables rules only on
  cmd/antrea-agent/agent.go
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
Labels: kind/cherry-pick

#6173 Automated cherry pick of #6123: Install Multicast related iptables rules only on
  cmd/antrea-agent/agent.go
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
Labels: kind/cherry-pick

#6184 Automated cherry pick of #6154: Fix a flaky failure in VM Agent e2e test "testExternalNode"
  test/e2e/vmagent_test.go
Labels: kind/cherry-pick

#6185 Automated cherry pick of #6154: Fix a flaky failure in VM Agent e2e test "testExternalNode"
  test/e2e/vmagent_test.go
Labels: kind/cherry-pick

#6183 Clarify documentation for IPPool and ExternalIPPool CRDs
  docs/antrea-ipam.md
  docs/egress.md
Labels: kind/documentation

#6112 Add Action to NetworkPolicy Evaluation response
  pkg/antctl/output/output.go
  pkg/antctl/transform/networkpolicy/response.go
  pkg/antctl/transform/networkpolicy/response_test.go
  pkg/apiserver/apis/types.go
  pkg/controller/networkpolicy/endpoint_querier.go
  pkg/controller/networkpolicy/endpoint_querier_test.go
  pkg/controller/types/networkpolicy.go
Labels: action/release-note

#6205 Do not try to update type of Secret in selfSignedCertProvider
  pkg/apiserver/certificate/selfsignedcert_provider.go
  pkg/apiserver/certificate/selfsignedcert_provider_test.go
Labels: action/backport

#6206 Automated cherry pick of #6205: Do not try to update type of Secret in selfSignedCertProvider
  pkg/apiserver/certificate/selfsignedcert_provider.go
  pkg/apiserver/certificate/selfsignedcert_provider_test.go
Labels: kind/cherry-pick

#6207 Automated cherry pick of #6205: Do not try to update type of Secret in selfSignedCertProvider
  pkg/apiserver/certificate/selfsignedcert_provider.go
  pkg/apiserver/certificate/selfsignedcert_provider_test.go
Labels: kind/cherry-pick

#6208 Automated cherry pick of #6205: Do not try to update type of Secret in selfSignedCertProvider
  pkg/apiserver/certificate/selfsignedcert_provider.go
  pkg/apiserver/certificate/selfsignedcert_provider_test.go
Labels: kind/cherry-pick

#6200 Avoid unnecessary DNS queries for FQDN rule of NetworkPolicy
  pkg/agent/controller/networkpolicy/fqdn.go
  pkg/agent/controller/networkpolicy/fqdn_test.go
Labels: area/network-policy, action/release-note

#6177 Remove deprecated v1alpha1/ExternalEntity
  build/charts/antrea/crds/externalentity.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/api.md
Labels: kind/api-change, action/release-note

#6182 Remove unified image
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  .github/workflows/conformance.yml
  .github/workflows/trivy_scan.yml
  .github/workflows/trivy_scan_before_release.yml
  Makefile
  build/images/Dockerfile.agent.ubuntu
  build/images/Dockerfile.build.coverage
  build/images/Dockerfile.build.ubi
  build/images/Dockerfile.build.ubuntu
  build/images/Dockerfile.controller.ubuntu
  ci/jenkins/mellanox/scripts/start_ci.sh
  ci/jenkins/test-vmc.sh
  docs/antctl.md
  docs/getting-started.md
  docs/maintainers/antrea-docker-image.md
  hack/build-antrea-linux-all.sh
Labels: action/release-note

#6211 Fix typo in NodePortLocal documentation
  docs/node-port-local.md
Labels: kind/documentation, size/XS, area/proxy/nodeportlocal

#6231 Increase default rate limit of antrea-controller
  cmd/antrea-controller/options.go
  cmd/antrea-controller/options_test.go
Labels: action/release-note

#6223 [Windows] Remove prefix "rancher-wins" when collecting antrea-agent logs
  pkg/support/dump_windows.go
  pkg/support/dump_windows_test.go
Labels: action/release-note

#6162 Remove deprecated v1alpha1 CRDs
  build/charts/antrea/crds/tier.yaml
  build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/api.md
  pkg/apis/crd/v1alpha1/register.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/clusternetworkpolicy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_clusternetworkpolicy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_networkpolicy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_tier.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/fake/fake_traceflow.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/networkpolicy.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/tier.go
  pkg/client/clientset/versioned/typed/crd/v1alpha1/traceflow.go
  pkg/client/informers/externalversions/crd/v1alpha1/clusternetworkpolicy.go
  pkg/client/informers/externalversions/crd/v1alpha1/interface.go
  pkg/client/informers/externalversions/crd/v1alpha1/networkpolicy.go
  pkg/client/informers/externalversions/crd/v1alpha1/tier.go
  pkg/client/informers/externalversions/crd/v1alpha1/traceflow.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/crd/v1alpha1/clusternetworkpolicy.go
  pkg/client/listers/crd/v1alpha1/expansion_generated.go
  pkg/client/listers/crd/v1alpha1/networkpolicy.go
  pkg/client/listers/crd/v1alpha1/tier.go
  pkg/client/listers/crd/v1alpha1/traceflow.go
Labels: kind/api-change, action/release-note

#6230 Document Pods using FQDN based policies must respect DNS TTL
  docs/antrea-network-policy.md
Labels: kind/documentation, area/network-policy

#6225 Document the limitations of Audit Logging for policy rules
  docs/antrea-network-policy.md
Labels: kind/documentation

#6233 Request basic memory for antrea-controller
  build/charts/antrea/README.md
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: action/release-note

#6242 Remove incorrect AntreaProxy warning on Windows
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_linux.go
  cmd/antrea-agent/options_windows.go
Labels: area/OS/windows, kind/bug, action/release-note

#6241 Add missing TrafficControl CRD from docs/api.md
  docs/api.md
Labels: kind/documentation

#6213 Automated cherry pick of #6076: Replace test Harbor images with DockerHub images (#6076)
  build/charts/antrea/templates/simulator/statefulset.yaml
  ci/docker-registry
  ci/jenkins/test-vm.sh
  ci/jenkins/test.sh
  ci/kind/test-e2e-kind.sh
  ci/run-k8s-e2e-tests.sh
  hack/externalnode/sftp-deployment.yml
  multicluster/test/e2e/framework.go
  test/e2e/charts/flow-visibility/templates/clickhouseinstallation.yaml
  test/e2e/framework.go
Labels: kind/cherry-pick

#6214 Automated cherry pick of #6076: Replace test Harbor images with DockerHub images (#6076)
  build/charts/antrea/templates/simulator/statefulset.yaml
  ci/docker-registry
  ci/jenkins/test-vm.sh
  ci/jenkins/test.sh
  ci/kind/test-e2e-kind.sh
  ci/run-k8s-e2e-tests.sh
  hack/externalnode/sftp-deployment.yml
  multicluster/test/e2e/framework.go
  test/e2e/charts/flow-visibility/templates/clickhouseinstallation.yaml
  test/e2e/framework.go
Labels: kind/cherry-pick

#6238 Remove left over versions from CRD declarations
  build/charts/antrea/crds/clusternetworkpolicy.yaml
  build/charts/antrea/crds/networkpolicy.yaml
  build/charts/antrea/crds/traceflow.yaml
  build/charts/antrea/templates/webhooks/mutating/crdmutator.yaml
  build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: kind/api-change

#6202 Use reserved OVS controller ports for default Antrea ports
  cmd/antrea-agent/agent.go
  docs/antctl.md
  docs/design/ovs-pipeline.md
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_linux_test.go
  pkg/agent/agent_test.go
  pkg/agent/agent_windows.go
  pkg/agent/apiserver/handlers/ovstracing/handler_test.go
  pkg/agent/config/node_config.go
  pkg/agent/controller/networkpolicy/fqdn_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_controller_test.go
  pkg/agent/multicluster/mc_route_controller.go
  pkg/agent/multicluster/mc_route_controller_test.go
  pkg/agent/openflow/client.go
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/multicast.go
  pkg/agent/openflow/multicast_test.go
  pkg/agent/openflow/network_policy_test.go
  pkg/agent/openflow/pod_connectivity.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/openflow/service_test.go
  pkg/agent/secondarynetwork/init_test.go
  pkg/ovs/ovsconfig/interfaces.go
  pkg/ovs/ovsconfig/ovs_client.go
  pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
  pkg/ovs/ovsctl/ovsctl_test.go
  test/integration/agent/openflow_test.go
  test/integration/ovs/ovs_client_test.go
Labels: action/release-note

#6256 Minor doc improvement for Pass action in Antrea-native policies
  docs/antrea-network-policy.md
Labels: kind/documentation

#6239 Remove additional deprecated CRD apis
  build/charts/antrea/crds/clustergroup.yaml
  build/charts/antrea/crds/egress.yaml
  build/charts/antrea/crds/externalippool.yaml
  build/charts/antrea/crds/group.yaml
  build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/api.md
  hack/update-codegen-dockerized.sh
  pkg/apis/crd/v1alpha2/register.go
  pkg/apis/crd/v1alpha2/types.go
  pkg/apis/crd/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/crd/v1alpha3/doc.go
  pkg/apis/crd/v1alpha3/register.go
  pkg/apis/crd/v1alpha3/types.go
  pkg/apis/crd/v1alpha3/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/crd/v1alpha2/crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha2/egress.go
  pkg/client/clientset/versioned/typed/crd/v1alpha2/externalippool.go
  pkg/client/clientset/versioned/typed/crd/v1alpha2/fake/fake_crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha2/fake/fake_egress.go
  pkg/client/clientset/versioned/typed/crd/v1alpha2/fake/fake_externalippool.go
  pkg/client/clientset/versioned/typed/crd/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/clustergroup.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/doc.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/fake/doc.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/fake/fake_clustergroup.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/fake/fake_crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/fake/fake_group.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/generated_expansion.go
  pkg/client/clientset/versioned/typed/crd/v1alpha3/group.go
  pkg/client/informers/externalversions/crd/interface.go
  pkg/client/informers/externalversions/crd/v1alpha2/egress.go
  pkg/client/informers/externalversions/crd/v1alpha2/externalippool.go
  pkg/client/informers/externalversions/crd/v1alpha2/interface.go
  pkg/client/informers/externalversions/crd/v1alpha3/clustergroup.go
  pkg/client/informers/externalversions/crd/v1alpha3/group.go
  pkg/client/informers/externalversions/crd/v1alpha3/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/crd/v1alpha2/egress.go
  pkg/client/listers/crd/v1alpha2/expansion_generated.go
  pkg/client/listers/crd/v1alpha2/externalippool.go
  pkg/client/listers/crd/v1alpha3/clustergroup.go
  pkg/client/listers/crd/v1alpha3/expansion_generated.go
  pkg/client/listers/crd/v1alpha3/group.go
  test/e2e/service_externalip_test.go
Labels: kind/api-change, action/release-note

#6172 Fix NodeNetworkPolicy e2e test failure
  test/e2e/fixtures.go
  test/e2e/k8s_util.go
  test/e2e/nodenetworkpolicy_test.go
Labels: area/test/e2e

#6251 Fix that local traffic cannot be identified in networkPolicyOnly mode
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/openflow/service.go
  test/integration/agent/openflow_test.go
Labels: area/ovs/openflow, action/backport, action/release-note

#6036 Unify IPPool subnet and ExternalIPPool definitions
  build/charts/antrea/crds/ippool.yaml
  build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  docs/antrea-ipam.md
  docs/api.md
  docs/cookbooks/multus/README.md
  docs/cookbooks/multus/resources/netattachdef-ippool.yml
  pkg/agent/cniserver/ipam/antrea_ipam.go
  pkg/agent/cniserver/ipam/antrea_ipam_controller.go
  pkg/agent/cniserver/ipam/antrea_ipam_test.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  pkg/agent/secondarynetwork/podwatch/testing/mock_podwatch.go
  pkg/apis/crd/v1beta1/register.go
  pkg/apis/crd/v1beta1/types.go
  pkg/apis/crd/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  pkg/client/clientset/versioned/typed/crd/v1beta1/crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1beta1/fake/fake_crd_client.go
  pkg/client/clientset/versioned/typed/crd/v1beta1/fake/fake_ippool.go
  pkg/client/clientset/versioned/typed/crd/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/crd/v1beta1/ippool.go
  pkg/client/informers/externalversions/crd/v1beta1/interface.go
  pkg/client/informers/externalversions/crd/v1beta1/ippool.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/crd/v1beta1/expansion_generated.go
  pkg/client/listers/crd/v1beta1/ippool.go
  pkg/controller/ipam/antrea_ipam_controller.go
  pkg/controller/ipam/antrea_ipam_controller_test.go
  pkg/controller/ipam/convert.go
  pkg/controller/ipam/convert_test.go
  pkg/controller/ipam/validate.go
  pkg/controller/ipam/validate_test.go
  pkg/ipam/poolallocator/allocator.go
  pkg/ipam/poolallocator/allocator_test.go
  pkg/ipam/poolallocator/testing/fake_client.go
  test/e2e-secondary-network/infra/secondary-networks.yml
  test/e2e/antreaipam_test.go
  test/e2e/basic_test.go
  test/e2e/secondary_network_ipam_test.go
Labels: action/release-note

#5330 Improve macros for job updater builder
  .gitignore
  ci/jenkins/jobs/macros.yaml
Labels: area/test/infra, area/test/jenkins

#6261 Add upgrade instructions for Antrea v2.0
  docs/versioning.md
Labels: kind/documentation, priority/critical-urgent

#5737 Upgrade base image of UBI to UBI9
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  .github/workflows/kind_ubi.yml
  build/images/Dockerfile.build.controller.ubi
  build/images/base/Dockerfile.ubi
  build/images/ovs/CentOS.repo
  build/images/ovs/Dockerfile.ubi
  build/images/ovs/build.sh
  hack/build-antrea-linux-all.sh
Labels: action/release-note

#5412 Update OVS pipeline document
  docs/assets/ovs-pipeline-antrea-proxy.svg
  docs/assets/ovs-pipeline.svg
  docs/design/ovs-pipeline.md
  pkg/agent/openflow/fields.go
Labels: kind/documentation

#6268 Automated cherry pick of #6251: Fix that local traffic cannot be identified in
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/openflow/service.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick
