Repository antrea-io/antrea, pull requests merged in 2024-08, with the labels that each got.

#6565 antctl: fix cluster checker image
  pkg/antctl/raw/check/cluster/command.go
Labels: area/component/antctl, action/backport, action/release-note

#6579 antctl: unify checker image and make it configurable
  pkg/antctl/raw/check/cluster/command.go
  pkg/antctl/raw/check/constants.go
  pkg/antctl/raw/check/installation/command.go
  pkg/antctl/raw/check/installation/command_test.go
  pkg/antctl/raw/check/installation/test_denyall.go
  pkg/antctl/raw/check/installation/test_podtointernet.go
  pkg/antctl/raw/check/installation/test_podtopodinternode.go
  pkg/antctl/raw/check/installation/test_podtopodintranode.go
  pkg/antctl/raw/check/installation/test_podtoservice.go
Labels: area/component/antctl, action/release-note

#6581 Log Flow Aggregator version on start
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  cmd/flow-aggregator/flow-aggregator.go
Labels: size/XS

#6577 Use same MTU as uplink for bridge port
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/noencap-hybrid-modes.md
  pkg/agent/agent_linux.go
  pkg/agent/secondarynetwork/init_linux.go
  pkg/agent/util/net_linux.go
Labels: kind/bug, action/release-note

#6528 Match dstIP in Classifier to address windows promiscuous mode issue
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pipeline_other.go
  pkg/agent/openflow/pipeline_windows.go
  pkg/agent/openflow/pod_connectivity_test.go
Labels: area/OS/windows

#6566 Update Egress Document to include egress dummy interface
  docs/egress.md
Labels: kind/documentation, area/transit/egress

#6618 Fix IPv6 address parameter in testEgressClientIPFromVLANSubnet
  test/e2e/egress_test.go
Labels: area/test/e2e

#6604 Add support for Service Traffic Distribution in Antrea Proxy
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/feature-gates.md
  pkg/agent/proxy/proxier.go
  pkg/agent/proxy/topology.go
  pkg/agent/proxy/topology_test.go
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
Labels: action/release-note

#6602 Support --random-fully for iptables SNAT / MASQUERADE rules
  build/charts/antrea/README.md
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  cmd/antrea-agent/options.go
  cmd/antrea-agent/options_windows.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/route/route_windows.go
  pkg/agent/util/iptables/iptables.go
  pkg/agent/util/iptables/testing/mock_iptables_linux.go
  pkg/config/agent/config.go
  test/integration/agent/route_test.go
Labels: action/release-note

#6601 Use default protocol/port when destination is service in antrea traceflow
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
Labels: kind/bug, area/ops/traceflow, action/release-note

#6630 [Flow Aggregator] Fix template ID error in IPFIX exporter
  pkg/flowaggregator/exporter/ipfix.go
Labels: action/backport, action/release-note

#6589 Upgrade Suricata to 7.0
  build/images/deps/suricata-version
  docs/antrea-l7-network-policy.md
  pkg/agent/controller/networkpolicy/l7engine/reconciler.go
  test/e2e/l7networkpolicy_test.go
Labels: area/dependency, action/release-note

#6634 Automated cherry pick of #6630: Fix template ID error in IPFIX exporter
  pkg/flowaggregator/exporter/ipfix.go
Labels: kind/cherry-pick

#6635 [FlowAggregator] Close connection to IPFIX collector on Stop
  pkg/flowaggregator/exporter/ipfix.go
Labels: action/backport, action/release-note

#6640 Add antctl-darwin-arm64 to release assets
  hack/release/prepare-assets.sh
Labels: area/build-release, action/release-note
