Repository antrea-io/antrea, pull requests merged in 2024-09, with the labels that each got.

#6638 Automated cherry pick of #6635: Close connection to IPFIX collector on Stop
  pkg/flowaggregator/exporter/ipfix.go
Labels: kind/cherry-pick

#6649 Fix some if conditions in Github workflows
  .github/workflows/build.yml
Labels: kind/bug, area/build-release

#6667 Remove unused code in v1alpha1/crd/types
  pkg/apis/crd/v1alpha1/types.go
Labels: kind/cleanup

#6646 Add "antctl get bgppolicy" agent command
  cmd/antrea-agent/agent.go
  docs/antctl.md
  docs/bgp-policy.md
  hack/update-codegen-dockerized.sh
  pkg/agent/apis/types.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/apiserver_test.go
  pkg/agent/apiserver/handlers/bgppolicy/handler.go
  pkg/agent/apiserver/handlers/bgppolicy/handler_test.go
  pkg/agent/controller/bgp/controller.go
  pkg/agent/controller/bgp/controller_test.go
  pkg/agent/querier/querier.go
  pkg/agent/querier/testing/mock_querier.go
  pkg/antctl/antctl.go
  pkg/antctl/command_list_test.go
  pkg/monitor/agent_test.go
  pkg/querier/querier.go
  pkg/querier/testing/mock_querier.go
  test/e2e/antctl_test.go
Labels: area/component/antctl, action/release-note, area/transit/bgp

#5974 To support running Antrea Flexible IPAM tests on KIND.
  CONTRIBUTING.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test.sh
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  test/e2e/fixtures.go
  test/e2e/framework.go
Labels: area/test/infra, area/test/jenkins

#6675 Add missing metav1.ObjectMeta to NetworkPolicyEvaluation API type
  pkg/apis/controlplane/types.go
  pkg/apis/controlplane/v1beta2/generated.pb.go
  pkg/apis/controlplane/v1beta2/generated.proto
  pkg/apis/controlplane/v1beta2/types.go
  pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
  pkg/apis/controlplane/v1beta2/zz_generated.deepcopy.go
  pkg/apis/controlplane/zz_generated.deepcopy.go
  pkg/apiserver/openapi/zz_generated.openapi.go
Labels: api-review, kind/api-change, kind/bug

#6679 Automated cherry pick of #6669: Add docker credentials to windows CI to avoid rate limit
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#6686 Change antctl make target
  .github/workflows/go.yml
  Makefile
Labels: kind/cleanup, area/component/antctl, area/build-release

#6651 Fix L7NP enable logging wrong packet
  docs/antrea-l7-network-policy.md
  pkg/agent/controller/networkpolicy/l7engine/reconciler.go
  pkg/agent/controller/networkpolicy/l7engine/reconciler_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  test/e2e/l7networkpolicy_test.go
Labels: action/release-note

#6685 Handle ExternalIPPool range changes in Egress controller
  pkg/controller/egress/controller.go
  pkg/controller/egress/controller_test.go
  pkg/controller/externalippool/controller.go
Labels: kind/bug, area/transit/egress, action/release-note

#6701 Automated cherry pick of #6000: [tests/e2e]: Remove all references to busybox in e2e tests
  test/e2e/antreapolicy_test.go
  test/e2e/basic_test.go
  test/e2e/batch_test.go
  test/e2e/connectivity_test.go
  test/e2e/egress_test.go
  test/e2e/fixtures.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
  test/e2e/infra/vagrant/playbook/roles/common/tasks/busybox.yml
  test/e2e/infra/vagrant/playbook/roles/common/tasks/main.yml
  test/e2e/networkpolicy_test.go
  test/e2e/proxy_test.go
  test/e2e/service_test.go
  test/e2e/wireguard_test.go
Labels: kind/cherry-pick

#6691 Run IPPool webhook handler when SecondaryNetwork is enabled
  pkg/apiserver/apiserver.go
Labels: kind/bug

#6705 Log ipset command output on failure
  pkg/agent/util/ipset/ipset.go
Labels: kind/cleanup
