Repository antrea-io/antrea, pull requests merged in 2024-05, with the labels that each got.

#6269 Automated cherry pick of #6251: Fix that local traffic cannot be identified in
  pkg/agent/openflow/client_test.go
  pkg/agent/openflow/fields.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/pod_connectivity_test.go
  pkg/agent/openflow/service.go
  test/integration/agent/openflow_test.go
Labels: kind/cherry-pick

#6258 Document Kind CI trigger phrases
  CONTRIBUTING.md
Labels: kind/documentation

#6280 Add documentation for the sameLabels feature in ACNP
  docs/antrea-network-policy.md
Labels: kind/documentation, action/backport

#6286 Automated cherry pick of #6280: Add documentation for the sameLabels feature in ACNP (#6280)
  docs/antrea-network-policy.md
Labels: kind/cherry-pick

#6302 Automated cherry pick of #6296: Update documentation link for GCP cloud provider (#6296)
  docs/noencap-hybrid-modes.md
Labels: kind/documentation, kind/cherry-pick

#6304 Automated cherry pick of #6296: Update documentation link for GCP cloud provider (#6296)
  docs/noencap-hybrid-modes.md
Labels: kind/documentation, kind/cherry-pick

#6274 Update document antrea-proxy.md
  docs/antrea-proxy.md
Labels: kind/documentation, action/backport

#6306 Automated cherry pick of #6274: Mention LoadbalancerIPMode support in AntreaProxy doc(#6274)
  docs/antrea-proxy.md
Labels: kind/cherry-pick

#6297 Automated cherry pick of #6284: Fix single rule deletion for NodePortLocal on Linux (#6284)
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/portcache/port_table_others.go
  pkg/agent/nodeportlocal/portcache/port_table_others_test.go
  pkg/agent/nodeportlocal/portcache/port_table_windows.go
  test/e2e/nodeportlocal_test.go
Labels: kind/cherry-pick

#6298 Automated cherry pick of #6284: Fix single rule deletion for NodePortLocal on Linux (#6284)
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/portcache/port_table_others.go
  pkg/agent/nodeportlocal/portcache/port_table_others_test.go
  pkg/agent/nodeportlocal/portcache/port_table_windows.go
  test/e2e/nodeportlocal_test.go
Labels: kind/cherry-pick

#6247 Add srcPodIP field in Traceflow observations
  build/charts/antrea/crds/traceflow.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/apis/crd/v1beta1/types.go
  pkg/apiserver/openapi/zz_generated.openapi.go
  test/e2e/traceflow_test.go
Labels: area/ops/traceflow

#3242 [Multicast] removal of stale multicast routes
  pkg/agent/multicast/mcast_controller.go
  pkg/agent/multicast/mcast_route.go
  pkg/agent/multicast/mcast_route_linux.go
  pkg/agent/multicast/mcast_route_test.go
  pkg/agent/multicast/mcast_socket_linux.go
  pkg/agent/multicast/mcast_socket_others.go
  pkg/agent/multicast/testing/mock_multicast.go
  pkg/agent/util/syscall/linux/types.go
  pkg/agent/util/syscall/syscall_unix.go
  pkg/agent/util/syscall/ztypes_linux.go
Labels: action/release-note

#6282 Clean up agent net util code
  pkg/agent/secondarynetwork/init_linux.go
  pkg/agent/secondarynetwork/init_linux_test.go
  pkg/agent/secondarynetwork/init_windows.go
  pkg/agent/util/net.go
  pkg/agent/util/net_linux.go
  pkg/agent/util/net_test.go
  pkg/agent/util/net_windows.go
Labels: area/interface

#6299 Automated cherry pick of #6284: Fix single rule deletion for NodePortLocal on Linux (#6284)
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/portcache/port_table_others.go
  pkg/agent/nodeportlocal/portcache/port_table_others_test.go
  pkg/agent/nodeportlocal/portcache/port_table_windows.go
  test/e2e/nodeportlocal_test.go
Labels: kind/cherry-pick

#6287 Fix antctl mc deploy command usage
  pkg/antctl/raw/multicluster/deploy/deploy_helper.go
  pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
Labels: area/multi-cluster

#6300 Automated cherry pick of #6284: Fix single rule deletion for NodePortLocal on Linux (#6284)
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/portcache/port_table.go
  pkg/agent/nodeportlocal/portcache/port_table_others.go
  pkg/agent/nodeportlocal/portcache/port_table_others_test.go
  pkg/agent/nodeportlocal/portcache/port_table_windows.go
  test/e2e/nodeportlocal_test.go
Labels: kind/cherry-pick

#6319 Fix inaccuracy in Traceflow user guide
  docs/traceflow-guide.md
Labels: kind/documentation

#6327 Automated cherry pick of #6319: Fix inaccuracy in Traceflow user guide (#6319)
  docs/traceflow-guide.md
Labels: kind/cherry-pick

#6317 Trim unneeded fields stored in informers to reduce memory footprint
  cmd/antrea-agent/agent.go
  cmd/antrea-controller/controller.go
  pkg/util/k8s/transform.go
  pkg/util/k8s/transform_test.go
Labels: action/release-note

#6332 Fix RestoreHostInterfaceConfiguration for SecondaryNetwork
  pkg/agent/secondarynetwork/init_linux.go
Labels: kind/bug, area/secondary-network

#6331 Remove unneeded member variables
  cmd/antrea-agent/agent.go
  pkg/agent/controller/serviceexternalip/controller.go
  pkg/agent/controller/serviceexternalip/controller_test.go
  pkg/agent/secondarynetwork/init_linux.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
Labels: kind/cleanup

#6329 Update package pkg/third_party/healthcheck
  third_party/proxy/healthcheck/common.go
  third_party/proxy/healthcheck/service_health.go
Labels: area/proxy

#5159 Reorganize the code for configuring Windows networking into dedicated package
  hack/update-codegen-dockerized.sh
  pkg/agent/agent_windows.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/server_windows_test.go
  pkg/agent/externalnode/external_node_controller_windows.go
  pkg/agent/nodeportlocal/rules/netnat_rule.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/route/route_windows.go
  pkg/agent/route/route_windows_test.go
  pkg/agent/util/net_windows.go
  pkg/agent/util/net_windows_test.go
  pkg/agent/util/winnet/interface.go
  pkg/agent/util/winnet/net_windows.go
  pkg/agent/util/winnet/net_windows_test.go
  pkg/agent/util/winnet/testing/mock_net_windows.go
  pkg/agent/util/winnet/types.go
  test/integration/agent/net_windows_test.go
Labels: area/test, area/OS/windows

#5603 Add Jenkins Job for Windows OVS containerization
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test.sh
Labels: area/OS/windows, kind/documentation, area/test/jenkins

#6352 Automated cherry pick of #6334: Update CNI binaries version to v1.4.1 (#6334)
  build/images/deps/cni-binaries-version
Labels: kind/cherry-pick

#6351 Trim images in Node objects to reduce memory footprint
  cmd/antrea-agent/agent.go
  pkg/util/k8s/transform.go
  pkg/util/k8s/transform_test.go
Labels: kind/cleanup

#6312 Add OVS driver installation in initContainer for Antrea Windows agent
  build/yamls/antrea-windows-with-ovs.yml
  build/yamls/antrea-windows.yml
  build/yamls/windows/containerd-with-ovs/conf/Install-OVSDriver.ps1
  build/yamls/windows/containerd-with-ovs/conf/Run-AntreaOVS.ps1
  build/yamls/windows/containerd-with-ovs/conf/VMSwitchExtension-AntreaAgent.ps1
  build/yamls/windows/containerd-with-ovs/containerd-with-ovs.yml
  build/yamls/windows/containerd-with-ovs/kustomization.yml
  build/yamls/windows/containerd/agent-containerd.yml
  build/yamls/windows/containerd/conf/Install-WindowsCNI.ps1
  build/yamls/windows/containerd/conf/Run-AntreaAgent.ps1
  build/yamls/windows/containerd/kustomization.yml
  hack/update-checksum-windows.sh
Labels: area/OS/windows

#6366 Avoid generating defunct process when starting Suricata
  pkg/agent/controller/networkpolicy/l7engine/reconciler.go
Labels: action/backport, action/release-note

#6374 Automated cherry pick of #6366: Avoid generating defunct process when starting Suricata
  pkg/agent/controller/networkpolicy/l7engine/reconciler.go
Labels: kind/cherry-pick

#6325 [Windows] Use hpc base image and buildx to build Agent Windows image
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
  .github/workflows/docker_update_base_windows.yml
  Makefile
  build/images/Dockerfile.build.windows
  build/images/base-windows/Dockerfile
  build/images/base-windows/README.md
  build/images/build-utils.sh
  build/images/build-windows.sh
  build/images/deps/nanoserver-version
  build/images/ovs/Dockerfile.windows
  build/images/ovs/README.md
  build/images/ovs/build.sh
  build/yamls/antrea-windows-with-ovs.yml
  build/yamls/windows/containerd-with-ovs/conf/Install-OVSDriver.ps1
  ci/jenkins/test.sh
  docs/windows.md
  hack/build-antrea-windows-all.sh
Labels: area/OS/windows

#6378 Improve handling of config changes in FlowAggregator
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
Labels: area/flow-visibility/aggregator, action/release-note
