Repository antrea-io/antrea, pull requests merged in 2025-01, with the labels that each got.

#6893 Automated cherry pick of #6889: Support OF port state "down" when installing Pod
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_test.go
Labels: kind/cherry-pick

#6898 Ensure that promote_secondaries is set on IPAssigner interfaces
  pkg/agent/ipassigner/ip_assigner_linux.go
  pkg/agent/util/net_linux.go
  test/integration/agent/ip_assigner_linux_test.go
Labels: kind/bug, area/transit/egress, action/backport, action/release-note

#6881 Support SecondaryNetwork of SR-IOV type for VM Nodes
  build/charts/antrea/README.md
  build/charts/antrea/templates/agent/daemonset.yaml
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_linux_test.go
  pkg/agent/cniserver/interfaces.go
  pkg/agent/cniserver/sriov_linux.go
  pkg/agent/cniserver/testing/mock_cniserver.go
  pkg/agent/secondarynetwork/podwatch/sriov.go
Labels: kind/bug, action/release-note, area/secondary-network

#6900 Ensure correct sysctl values if VLAN iface exists in IPAssigner
  pkg/agent/ipassigner/ip_assigner_linux.go
  test/integration/agent/ip_assigner_linux_test.go
Labels: action/backport, action/release-note

#6769 [FlowAggregator] Add clusterId to aggregated records
  ci/kind/test-e2e-kind.sh
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/exporter/ipfix_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  test/e2e/basic_test.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: action/release-note

#6912 Support version skew between Antrea Agent and Flow Aggregator
  pkg/flowaggregator/clickhouseclient/clickhouseclient.go
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/flowaggregator/preprocessor.go
  pkg/flowaggregator/preprocessor_test.go
Labels: action/release-note

#6914 Remove local ASN range limitation in BGPPolicy
  build/charts/antrea/crds/bgppolicy.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/bgp-policy.md
  pkg/apis/crd/v1alpha1/types.go
Labels: action/release-note, area/transit/bgp

#6906 Fix Windows Conformance failure by updating time synchronization script
  ci/jenkins/test.sh
Labels: area/OS/windows

#6924 Automated cherry pick of #5974: To support running Antrea Flexible IPAM tests on KIND (#5974)
  CONTRIBUTING.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-lab.yaml
  ci/jenkins/test.sh
  ci/kind/kind-setup.sh
  ci/kind/test-e2e-kind.sh
  test/e2e/fixtures.go
  test/e2e/framework.go
Labels: kind/cherry-pick

#6928 Automated cherry pick of #6647: Upgrade Go to 1.23 (#6647)
  .golangci.yml
  Makefile
  build/images/codegen/README.md
  build/images/deps/go-version
  docs/prometheus-integration.md
  go.mod
  hack/.spelling_failures
  hack/update-codegen.sh
  multicluster/controllers/multicluster/leader/resourceexport_controller.go
  multicluster/controllers/multicluster/member/labelidentity_controller.go
  multicluster/controllers/multicluster/member/node_controller.go
  multicluster/controllers/multicluster/member/resourceimport_controller_test.go
  multicluster/controllers/multicluster/member/serviceexport_controller.go
  multicluster/hack/update-codegen.sh
  multicluster/test/e2e/antreapolicy_test.go
  multicluster/test/e2e/framework.go
  pkg/agent/controller/networkpolicy/audit_logging.go
  pkg/agent/controller/networkpolicy/l7engine/reconciler.go
  pkg/agent/controller/networkpolicy/node_reconciler_linux.go
  pkg/agent/controller/networkpolicy/pod_reconciler.go
  pkg/agent/externalnode/external_node_controller.go
  pkg/agent/nodeportlocal/npl_agent_test.go
  pkg/agent/nodeportlocal/testing/annotations.go
  pkg/agent/openflow/network_policy.go
  pkg/agent/route/route_linux.go
  pkg/antctl/command_list.go
  pkg/antctl/raw/check/cluster/command.go
  pkg/antctl/raw/check/installation/command.go
  pkg/antctl/raw/check/installation/test_podtoservice.go
  pkg/antctl/raw/check/logger.go
  pkg/antctl/raw/check/util.go
  pkg/apis/crd/v1beta1/util.go
  pkg/apiserver/certificate/certificate_test.go
  pkg/apiserver/handlers/webhook/convert_crd.go
  pkg/controller/externalippool/controller.go
  pkg/controller/networkpolicy/clustergroup.go
  pkg/controller/networkpolicy/clusternetworkpolicy.go
  pkg/controller/stats/aggregator.go
  pkg/flowaggregator/clickhouseclient/clickhouseclient_test.go
  pkg/flowaggregator/s3uploader/s3uploader.go
  pkg/flowaggregator/s3uploader/s3uploader_test.go
  pkg/ipam/poolallocator/allocator.go
  pkg/ovs/ovsctl/ovsctl_test.go
  pkg/util/ip/ip.go
  pkg/util/sets/int32_test.go
  test/e2e/framework.go
  test/integration/ovs/ofctrl_test.go
Labels: kind/cherry-pick

#6931 Add table of contents to the OVS pipeline doc
  docs/design/ovs-pipeline.md
Labels: kind/documentation

#6942 Automated cherry pick of #6919: Remove stale OVS ports in reconcile if host
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_linux.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/server_linux_test.go
Labels: kind/cherry-pick

#6945 Automated cherry pick of #6742: Update finalizer of ResourceExport to be domain-qualified
  multicluster/apis/multicluster/constants/constants.go
  multicluster/apis/multicluster/v1alpha1/resourceexport_webhook.go
  multicluster/controllers/multicluster/common/helper.go
  multicluster/controllers/multicluster/leader/clusterinfo_export_handler.go
  multicluster/controllers/multicluster/leader/memberclusterannounce_controller.go
  multicluster/controllers/multicluster/leader/resourceexport_controller.go
  multicluster/controllers/multicluster/leader/resourceexport_controller_test.go
  multicluster/controllers/multicluster/leader/stale_controller.go
  multicluster/test/integration/resourceexport_controller_test.go
Labels: kind/cherry-pick

#6947 Automated cherry pick of #6930: Update some golang.org/x dependencies to resolve CVEs (#6930)
  go.mod
  go.sum
Labels: kind/cherry-pick
