Repository antrea-io/antrea, pull requests merged in 2025-08, with the labels that each got.

#7329 fix: protocolFilter struct tag typo
  pkg/config/agent/config.go
Labels: area/flow-visibility/exporter, kind/cherry-pick

#7333 Upgrade CNI plugins from v1.6.2 to v1.7.1
  build/images/deps/cni-binaries-version
Labels: action/release-note

#7349 Automated cherry pick of #7346: Fix kind network cleanup failure on newly provisioned Jenkins
  ci/kind/kind-setup.sh
Labels: kind/cherry-pick

#7359 Automated cherry pick of #7343: Add missing Run calls for nodeStore /
  cmd/antrea-agent/agent.go
  cmd/flow-aggregator/flow-aggregator.go
  pkg/agent/flowexporter/exporter.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/util/objectstore/store.go
Labels: kind/cherry-pick

#7295 Periodically sync ip rules to ensure necessary ip rules
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
Labels: action/release-note

#7364 Automated cherry pick of #7351: Correct ICMPv6 echo request type in ACNPICMPSupport (#7351)
  test/e2e/antreapolicy_test.go
  test/e2e/multicast_test.go
  test/e2e/net_constants.go
  test/e2e/nodenetworkpolicy_test.go
  test/e2e/traceflow_test.go
  test/e2e/vmagent_test.go
Labels: kind/cherry-pick

#7265 Fix ACNP applied to NodePort failing to reject traffic in noEncap/hybrid mode
  .github/workflows/kind.yml
  docs/antrea-network-policy.md
  pkg/agent/controller/networkpolicy/reject.go
  pkg/agent/controller/networkpolicy/reject_test.go
  pkg/agent/openflow/pipeline.go
  pkg/agent/openflow/service_test.go
  test/e2e/antreapolicy_test.go
  test/e2e/proxy_test.go
Labels: action/backport, action/release-note

#7266 Handle Traceflow external destination IP correctly in NoEncap mode
  cmd/antrea-agent/agent.go
  pkg/agent/controller/traceflow/packetin.go
  pkg/agent/controller/traceflow/packetin_test.go
  pkg/agent/controller/traceflow/traceflow_controller.go
  pkg/agent/controller/traceflow/traceflow_controller_test.go
  pkg/apis/crd/v1beta1/types.go
  pkg/controller/traceflow/controller.go
  test/e2e/traceflow_test.go
Labels: kind/bug, area/ops/traceflow

#7282 Use a more robust way to extract the source Node IP from encapsulated IGMP messages
  pkg/agent/multicast/mcast_discovery.go
  pkg/agent/multicast/mcast_discovery_test.go
  test/e2e/multicast_test.go
Labels: action/backport, action/release-note

#7365 Automated cherry pick of #7351: Correct ICMPv6 echo request type in ACNPICMPSupport (#7351)
  test/e2e/antreapolicy_test.go
  test/e2e/multicast_test.go
  test/e2e/net_constants.go
  test/e2e/nodenetworkpolicy_test.go
  test/e2e/traceflow_test.go
  test/e2e/vmagent_test.go
Labels: kind/cherry-pick
