Repository antrea-io/antrea, pull requests merged in 2025-06, with the labels that each got.

#7197 Support custom ClusterIDs attached to exported flow records
  build/charts/flow-aggregator/README.md
  build/charts/flow-aggregator/conf/flow-aggregator.conf
  build/charts/flow-aggregator/values.yaml
  build/yamls/flow-aggregator.yml
  pkg/clusteridentity/clusteridentity.go
  pkg/config/flowaggregator/config.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: action/release-note

#7199 Persist container netns with OVS port external IDs
  pkg/agent/agent_test.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_linux.go
  pkg/agent/cniserver/pod_configuration_linux_test.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/secondary.go
  pkg/agent/cniserver/server_linux_test.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/cniserver/server_windows_test.go
  pkg/agent/interfacestore/interface_cache_test.go
  pkg/agent/interfacestore/types.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
Labels: area/interface, area/secondary-network

#7210 Fix rollback when configureContainerLinkVeth fails
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_linux_test.go
Labels: area/secondary-network

#7208 Fix invalid template ID in FlowAggregator (IPFIX exporter)
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/exporter/ipfix_test.go
  pkg/flowaggregator/preprocessor_test.go
Labels: action/backport, action/release-note

#7164 Add ICMP messages filter support to PacketCapture
  build/charts/antrea/crds/packetcapture.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/antctl.md
  docs/packetcapture-guide.md
  pkg/agent/packetcapture/capture/bpf.go
  pkg/agent/packetcapture/capture/bpf_test.go
  pkg/agent/packetcapture/packetcapture_controller.go
  pkg/antctl/raw/packetcapture/command.go
  pkg/antctl/raw/packetcapture/command_test.go
  pkg/apis/crd/v1alpha1/types.go
  pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
  test/e2e/packetcapture_test.go
Labels: kind/api-change, action/release-note, area/ops/packetcapture

#7218 Automated cherry pick of #7210: Fix rollback when configureContainerLinkVeth fails (#7210) #7213: Fix the interface name used for interface deletion (#7213)
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_linux_test.go
Labels: kind/cherry-pick

#7220 Automated cherry pick of #7210: Fix rollback when configureContainerLinkVeth fails (#7210) #7213: Fix the interface name used for interface deletion (#7213)
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_linux_test.go
Labels: kind/cherry-pick

#7222 Fix incorrect description in pipeline.md
  docs/design/ovs-pipeline.md
Labels: kind/documentation

#7223 FlowAggregator improvements
  docs/antctl.md
  pkg/flowaggregator/apis/types.go
  pkg/flowaggregator/apiserver/handlers/recordmetrics/handler.go
  pkg/flowaggregator/apiserver/handlers/recordmetrics/handler_test.go
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/exporter/ipfix_test.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/flowaggregator/querier/querier.go
  pkg/util/podstore/podstore.go
  pkg/util/podstore/testing/mock_podstore.go
Labels: area/flow-visibility/aggregator

#7230 [FlowAggregator] Fix race condition when getting metrics
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
Labels: kind/bug, area/flow-visibility/aggregator, action/backport, action/release-note

#7219 Automated cherry pick of #7210: Fix rollback when configureContainerLinkVeth fails (#7210) #7213: Fix the interface name used for interface deletion (#7213)
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_linux_test.go
Labels: kind/cherry-pick

#7221 Remove unnecessary logs about NPL cleanup
  pkg/agent/nodeportlocal/k8s/npl_controller.go
  pkg/agent/nodeportlocal/portcache/port_table_others.go
  pkg/agent/nodeportlocal/portcache/port_table_windows.go
  pkg/agent/nodeportlocal/portcache/port_table_windows_test.go
Labels: kind/cleanup, area/proxy/nodeportlocal

#7242 Log error when OVS meter drops packets
  pkg/agent/openflow/client.go
  pkg/agent/openflow/pipeline.go
Labels: action/release-note

#7228 Enhance OVS commands for Antrea Windows
  build/charts/antrea-windows/conf/ovs/Run-AntreaOVS.ps1
  build/yamls/antrea-windows-with-ovs.yml
Labels: action/backport

#7243 Increase the default packet-in rate limit to 5000
  build/charts/antrea/README.md
  build/charts/antrea/values.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/options.go
  docs/antrea-network-policy.md
  pkg/agent/openflow/client_test.go
Labels: area/network-policy, action/release-note

#7246 Automated cherry pick of #7217: Sync groups members for pods that turns into terminated
  pkg/controller/grouping/controller.go
  pkg/controller/grouping/controller_test.go
  pkg/controller/grouping/group_entity_index.go
  pkg/controller/grouping/group_entity_index_test.go
Labels: kind/cherry-pick

#7247 Automated cherry pick of #7217: Sync groups members for pods that turns into terminated
  pkg/controller/grouping/controller.go
  pkg/controller/grouping/controller_test.go
  pkg/controller/grouping/group_entity_index.go
  pkg/controller/grouping/group_entity_index_test.go
Labels: kind/cherry-pick

#7248 Automated cherry pick of #7217: Sync groups members for pods that turns into terminated
  pkg/controller/grouping/controller.go
  pkg/controller/grouping/controller_test.go
  pkg/controller/grouping/group_entity_index.go
  pkg/controller/grouping/group_entity_index_test.go
Labels: kind/cherry-pick

#7252 Automated cherry pick of #7228: Enhance OVS commands for Antrea Windows (#7228)
  build/charts/antrea-windows/conf/ovs/Run-AntreaOVS.ps1
  build/yamls/antrea-windows-with-ovs.yml
Labels: kind/cherry-pick
