Repository antrea-io/antrea, pull requests merged in 2025-04, with the labels that each got.

#7080 Update go-ipfix to v0.14.0
  go.mod
  go.sum
  pkg/flowaggregator/exporter/ipfix.go
Labels: action/backport

#7068 fix: batch probing in e2e test setup (#7067)
  test/e2e/k8s_util.go
Labels: area/test/e2e, lifecycle/active

#7011 ICMP Rule with NodeLatencyMonitor
  cmd/antrea-agent/agent.go
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/route/route_windows.go
  test/integration/agent/route_test.go
Labels: action/release-note

#7095 Automated cherry pick of #7027: Upgrade github.com/spf13/cobra to 1.9.1 (#7027)
  go.mod
  go.sum
  pkg/antctl/raw/featuregates/command_test.go
  pkg/antctl/raw/multicluster/common/common_test.go
  pkg/antctl/raw/multicluster/create/member_token_test.go
  pkg/antctl/raw/multicluster/delete/member_token_test.go
  pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
  pkg/antctl/raw/multicluster/destory_test.go
  pkg/antctl/raw/multicluster/get/clusterset_test.go
  pkg/antctl/raw/multicluster/get/join_config_test.go
  pkg/antctl/raw/multicluster/get/member_token_test.go
  pkg/antctl/raw/multicluster/get/resourceexport_test.go
  pkg/antctl/raw/multicluster/get/resourceimport_test.go
  pkg/antctl/raw/multicluster/init_test.go
  pkg/antctl/raw/multicluster/join_test.go
  pkg/antctl/raw/multicluster/leave_test.go
  pkg/antctl/raw/traceflow/command_test.go
Labels: kind/cherry-pick

#7094 Automated cherry pick of #7080: Update go-ipfix to v0.14.0 (#7080)
  go.mod
  go.sum
  pkg/flowaggregator/exporter/ipfix.go
Labels: kind/cherry-pick

#6884 Support antctl command for packetcapture
  docs/antctl.md
  pkg/antctl/antctl.go
  pkg/antctl/command_list.go
  pkg/antctl/command_list_test.go
  pkg/antctl/raw/check/cluster/test_checkcniexistence.go
  pkg/antctl/raw/check/cluster/test_checkovsloadable.go
  pkg/antctl/raw/check/installation/command.go
  pkg/antctl/raw/check/util.go
  pkg/antctl/raw/helper.go
  pkg/antctl/raw/packetcapture/command.go
  pkg/antctl/raw/packetcapture/command_test.go
  pkg/util/compress/compress.go
Labels: action/release-note

#7122 Add missing labels to namelabelmutator.antrea.io in doc
  docs/antrea-network-policy.md
Labels: kind/documentation

#7125 [FlowAggregator] Clean up RBAC
  build/charts/flow-aggregator/README.md
  build/charts/flow-aggregator/templates/clusterrole.yaml
  build/charts/flow-aggregator/templates/clusterrolebinding.yaml
  build/charts/flow-aggregator/templates/clusterrolebindings.yaml
  build/charts/flow-aggregator/templates/role.yaml
  build/charts/flow-aggregator/templates/rolebinding.yaml
  build/charts/flow-aggregator/templates/rolebindings.yaml
  build/charts/flow-aggregator/templates/roles.yaml
  build/charts/flow-aggregator/values.yaml
  build/yamls/flow-aggregator.yml
  build/yamls/flow-aggregator/base/kustomization.yml
Labels: area/flow-visibility/aggregator, action/release-note
