Repository antrea-io/antrea, pull requests merged in 2025-07, with the labels that each got.

#7253 [FlowAggregator] Use Protobuf message internally
  go.mod
  hack/update-codegen-dockerized.sh
  pkg/apis/flow/v1alpha1/flow.pb.go
  pkg/apis/flow/v1alpha1/flow.proto
  pkg/flowaggregator/clickhouseclient/clickhouseclient.go
  pkg/flowaggregator/clickhouseclient/clickhouseclient_test.go
  pkg/flowaggregator/exporter/clickhouse.go
  pkg/flowaggregator/exporter/interface.go
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/exporter/ipfix_test.go
  pkg/flowaggregator/exporter/log.go
  pkg/flowaggregator/exporter/log_test.go
  pkg/flowaggregator/exporter/s3.go
  pkg/flowaggregator/exporter/testing/mock_exporter.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/flowaggregator/flowrecord/record.go
  pkg/flowaggregator/flowrecord/record_test.go
  pkg/flowaggregator/intermediate/aggregate.go
  pkg/flowaggregator/intermediate/aggregate_test.go
  pkg/flowaggregator/intermediate/interface.go
  pkg/flowaggregator/intermediate/testing/mock_intermediate.go
  pkg/flowaggregator/intermediate/types.go
  pkg/flowaggregator/preprocessor.go
  pkg/flowaggregator/preprocessor_test.go
  pkg/flowaggregator/s3uploader/s3uploader.go
  pkg/flowaggregator/s3uploader/s3uploader_test.go
  pkg/flowaggregator/testing/util.go
Labels: area/flow-visibility/aggregator, action/release-note

#7263 Automated cherry pick of #7183: Fix the flaky failure with Multicast unit test (#7183) #7202: Fix flaky failure in unit test case
  pkg/agent/multicast/mcast_controller_test.go
Labels: kind/cherry-pick

#7262 Automated cherry pick of #7183: Fix the flaky failure with Multicast unit test (#7183) #7202: Fix flaky failure in unit test case
  pkg/agent/multicast/mcast_controller_test.go
Labels: kind/cherry-pick

#7257 Automated cherry pick of #7238: Periodically sync permanent neighbors to ensure route
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
Labels: kind/cherry-pick

#7258 Automated cherry pick of #7238: Periodically sync permanent neighbors to ensure route
  pkg/agent/route/route_linux.go
  pkg/agent/route/route_linux_test.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
Labels: kind/cherry-pick

#7240 Initialize SRIOV interfaces via NetworkStatus when agent restarts
  pkg/agent/cniserver/ipam/antrea_ipam_controller.go
  pkg/agent/cniserver/secondary.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  test/e2e-secondary-network/secondary_network_test.go
Labels: area/secondary-network

#7137 Allow defining static mac adresses for SecondaryInterfaces for VLAN network
  docs/secondary-network.md
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_linux_test.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/interfaces.go
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/pod_configuration_linux.go
  pkg/agent/cniserver/pod_configuration_linux_test.go
  pkg/agent/cniserver/pod_configuration_windows.go
  pkg/agent/cniserver/secondary.go
  pkg/agent/cniserver/server.go
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  pkg/agent/secondarynetwork/podwatch/testing/mock_podwatch.go
  test/e2e-secondary-network/secondary_network_test.go
Labels: kind/documentation, action/release-note, area/secondary-network

#7144 Rename VF name back to the original when Pod deleted
  cmd/antrea-agent/agent.go
  go.mod
  go.sum
  hack/update-codegen-dockerized.sh
  pkg/agent/cniserver/interface_configuration_linux.go
  pkg/agent/cniserver/interface_configuration_linux_test.go
  pkg/agent/cniserver/interface_configuration_windows.go
  pkg/agent/cniserver/interfaces.go
  pkg/agent/cniserver/pod_configuration_linux_test.go
  pkg/agent/cniserver/secondary.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux_test.go
  pkg/agent/cniserver/server_test.go
  pkg/agent/secondarynetwork/init.go
  pkg/agent/secondarynetwork/podwatch/sriov.go
  pkg/agent/types/cnichecker.go
  pkg/agent/types/testing/mock_types.go
  pkg/agent/util/netlink/netlink_linux.go
  pkg/agent/util/netlink/testing/mock_netlink_linux.go
  test/e2e-secondary-network/secondary_network_test.go
  test/integration/agent/cniserver_test.go
Labels: action/release-note

#7254 Add resource requests for Windows container in Antrea deployment
  build/charts/antrea-windows/templates/daemonset.yaml
  build/yamls/antrea-windows-with-ovs.yml
  build/yamls/antrea-windows.yml
Labels: action/release-note

#7311 Remove trailing whitespace from default manifests
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: action/backport

#7312 Automated cherry pick of #7311: Remove trailing whitespace from default manifests (#7311)
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: kind/cherry-pick

#7314 Automated cherry pick of #7286: Improve secondary interface reconciliation (#7286)
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
Labels: kind/cherry-pick

#7308 Add validation to ensure IP range start is not greater than end in IPPool
  pkg/controller/ipam/validate.go
  pkg/controller/ipam/validate_test.go
Labels: action/backport

#7318 Automated cherry pick of #7308: Add validation to ensure IP range start is not greater than
  pkg/controller/ipam/validate.go
  pkg/controller/ipam/validate_test.go
Labels: kind/cherry-pick

#7322 Improve SR-IOV device assignment to ensure it's idempotent
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  pkg/agent/secondarynetwork/podwatch/sriov.go
Labels: action/backport, area/secondary-network
