Repository antrea-io/antrea, pull requests merged in 2025-03, with the labels that each got.

#6991 Remove Builder and Jenkins job for IPAM tests and Skip irrelevant tests from Flexible IPAM tests
  .github/workflows/kind.yml
  CONTRIBUTING.md
  ci/jenkins/README.md
  ci/jenkins/jobs/macros.yaml
  ci/jenkins/jobs/projects-cloud.yaml
  ci/jenkins/jobs/projects-lab.yaml
  test/e2e/antreapolicy_test.go
Labels: action/backport

#7042 Fix crash when deleting the Secret storing BGP passwords
  pkg/agent/controller/bgp/controller.go
  pkg/agent/controller/bgp/controller_test.go
Labels: action/backport, action/release-note

#7036 Push flow-aggregator image to ghcr.io registry
  .github/workflows/build.yml
  .github/workflows/build_tag.yml
Labels: area/build-release, action/release-note

#7047 Automated cherry pick of #7042: Fix crash when deleting the Secret storing BGP passwords
  pkg/agent/controller/bgp/controller.go
  pkg/agent/controller/bgp/controller_test.go
Labels: kind/cherry-pick

#7045 Automated cherry pick of #7042: Fix crash when deleting the Secret storing BGP passwords
  pkg/agent/controller/bgp/controller.go
  pkg/agent/controller/bgp/controller_test.go
Labels: kind/cherry-pick

#6882 Add bidirectional packet capture
  build/charts/antrea/crds/packetcapture.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/packetcapture-guide.md
  pkg/agent/packetcapture/capture/bpf.go
  pkg/agent/packetcapture/capture/bpf_test.go
  pkg/agent/packetcapture/capture/pcap_linux.go
  pkg/agent/packetcapture/capture/pcap_unsupported.go
  pkg/agent/packetcapture/capture_interface.go
  pkg/agent/packetcapture/packetcapture_controller.go
  pkg/agent/packetcapture/packetcapture_controller_test.go
  pkg/apis/crd/v1alpha1/types.go
  test/e2e/packetcapture_test.go
Labels: action/release-note, area/ops/packetcapture

#6868 Add antctl get fqdncache
  pkg/agent/apis/types.go
  pkg/agent/apiserver/apiserver.go
  pkg/agent/apiserver/handlers/fqdncache/handler.go
  pkg/agent/apiserver/handlers/fqdncache/handler_test.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller.go
  pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
  pkg/agent/types/networkpolicy.go
  pkg/antctl/antctl.go
  pkg/antctl/command_list_test.go
  pkg/querier/querier.go
  pkg/querier/testing/mock_querier.go
Labels: action/release-note

#7076 Document SecondaryNetwork support for SR-IOV
  docs/secondary-network.md
  hack/.notableofcontents
Labels: kind/documentation, action/backport

#7082 Automated cherry pick of #7076: Document SecondaryNetwork support for SR-IOV (#7076)
  docs/secondary-network.md
  hack/.notableofcontents
Labels: kind/cherry-pick
