Repository antrea-io/antrea, pull requests merged in 2025-02, with the labels that each got.

#6944 [Windows] Reconcile host-network Pods after agent is restarted
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux.go
  pkg/agent/cniserver/server_windows.go
  pkg/agent/cniserver/server_windows_test.go
  test/e2e/connectivity_test.go
Labels: area/OS/windows

#6973 Remove sleep for TestGroupEntityIndexEventHandlers unit test
  pkg/controller/grouping/group_entity_index_test.go
Labels: area/test, kind/failing-test

#6977 Add more printer columns for PacketCapture CRD
  build/charts/antrea/crds/packetcapture.yaml
  build/yamls/antrea-aks.yml
  build/yamls/antrea-crds.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
Labels: action/release-note, area/ops/packetcapture

#6980 Automated cherry pick of #6796: Upgrade CNI plugins from v1.5.1 to v1.6.2 (#6796)
  build/images/deps/cni-binaries-version
Labels: kind/cherry-pick

#6981 Automated cherry pick of #6796: Upgrade CNI plugins from v1.5.1 to v1.6.2 (#6796)
  build/images/deps/cni-binaries-version
Labels: kind/cherry-pick

#6983 Automated cherry pick of #6821: Fix packetcapture bpf filter issue (#6815) (#6821) #6804: Fix PacketCapture pcapng file issue on macOS (#6804)
  pkg/agent/packetcapture/capture/pcap_linux.go
  pkg/agent/packetcapture/capture/pcap_unsupported.go
  pkg/agent/packetcapture/capture_interface.go
  pkg/agent/packetcapture/packetcapture_controller.go
  pkg/agent/packetcapture/packetcapture_controller_test.go
  test/e2e/packetcapture_test.go
Labels: kind/cherry-pick

#6979 Add flowDirection IE when proxying records in FlowAggregator
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/flowaggregator_test.go
  pkg/flowaggregator/infoelements/elements.go
Labels: area/flow-visibility/aggregator

#6903 Promote ServiceExternalIP to beta
  build/charts/antrea/conf/antrea-agent.conf
  build/charts/antrea/conf/antrea-controller.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  docs/feature-gates.md
  docs/service-loadbalancer.md
  pkg/apiserver/handlers/featuregates/handler_test.go
  pkg/features/antrea_features.go
Labels: action/release-note

#6990 [FlowAggregator] Use correct input channel in flowExportLoopProxy
  pkg/flowaggregator/flowaggregator.go
  test/e2e/fixtures.go
Labels: kind/bug

#6843 Enable disabling TX checksum offload for Antrea host gateway
  build/charts/antrea/conf/antrea-agent.conf
  build/yamls/antrea-aks.yml
  build/yamls/antrea-eks.yml
  build/yamls/antrea-gke.yml
  build/yamls/antrea-ipsec.yml
  build/yamls/antrea.yml
  cmd/antrea-agent/agent.go
  docs/antrea-l7-network-policy.md
  pkg/agent/agent.go
  pkg/agent/agent_linux.go
  pkg/agent/agent_windows.go
  pkg/config/agent/config.go
  test/e2e/l7networkpolicy_test.go
Labels: action/release-note

#6970 Automated cherry pick of #6944: Reconcile host-network Pods after agent is
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux.go
  pkg/agent/cniserver/server_windows.go
  pkg/agent/cniserver/server_windows_test.go
  test/e2e/connectivity_test.go
  test/e2e/framework.go
Labels: kind/cherry-pick

#6969 Automated cherry pick of #6944: Reconcile host-network Pods after agent is
  pkg/agent/cniserver/pod_configuration.go
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux.go
  pkg/agent/cniserver/server_windows.go
  pkg/agent/cniserver/server_windows_test.go
  test/e2e/connectivity_test.go
  test/e2e/framework.go
Labels: kind/cherry-pick

#6985 Add localhost for VMSwitch commands to avoid potential validation issue
  build/charts/antrea-windows/conf/ovs/VMSwitchExtension-AntreaAgent.ps1
  build/yamls/antrea-windows-with-ovs.yml
  hack/externalnode/install-vm.ps1
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Helper.psm1
  hack/windows/Prepare-ServiceInterface.ps1
  pkg/agent/util/winnet/net_windows.go
  pkg/agent/util/winnet/net_windows_test.go
  test/integration/agent/net_windows_test.go
Labels: action/release-note

#6771 Fix context issue during cleanup of kind clusters
  ci/kind/kind-setup.sh
Labels: area/test/infra

#7003 Automated cherry pick of #6985: Add localhost for VMSwitch commands to avoid potential
  build/charts/antrea-windows/conf/ovs/VMSwitchExtension-AntreaAgent.ps1
  build/yamls/antrea-windows-with-ovs.yml
  hack/externalnode/install-vm.ps1
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Helper.psm1
  hack/windows/Prepare-ServiceInterface.ps1
  pkg/agent/util/winnet/net_windows.go
  pkg/agent/util/winnet/net_windows_test.go
  test/integration/agent/net_windows_test.go
Labels: kind/cherry-pick

#7004 Automated cherry pick of #6985: Add localhost for VMSwitch commands to avoid potential
  build/charts/antrea-windows/conf/ovs/VMSwitchExtension-AntreaAgent.ps1
  build/yamls/antrea-windows-with-ovs.yml
  hack/externalnode/install-vm.ps1
  hack/windows/Clean-AntreaNetwork.ps1
  hack/windows/Helper.psm1
  hack/windows/Prepare-ServiceInterface.ps1
  pkg/agent/util/winnet/net_windows.go
  pkg/agent/util/winnet/net_windows_test.go
  test/integration/agent/net_windows_test.go
Labels: kind/cherry-pick

#6999 [SecondaryNetwork] Require resourceName annotations for SRIOV
  pkg/agent/secondarynetwork/podwatch/controller.go
  pkg/agent/secondarynetwork/podwatch/controller_test.go
  pkg/agent/secondarynetwork/podwatch/sriov.go
Labels: area/secondary-network

#7006 [FlowAggregator] Accept configurations with no collector / sink
  pkg/flowaggregator/options/options.go
Labels: area/flow-visibility/aggregator, action/release-note

#6468 Fix the cause of failure of multiple kind job runs on same VM
  Makefile
  ci/jenkins/test.sh
  ci/kind/kind-setup.sh
  test/e2e/providers/kind.go
Labels: area/test/infra

#6998 Upgrade go-ipfix to v0.13.0
  build/charts/flow-aggregator/README.md
  build/charts/flow-aggregator/conf/flow-aggregator.conf
  build/charts/flow-aggregator/values.yaml
  build/yamls/flow-aggregator.yml
  ci/kind/test-e2e-kind.sh
  go.mod
  go.sum
  hack/update-codegen-dockerized.sh
  pkg/config/flowaggregator/config.go
  pkg/config/flowaggregator/default.go
  pkg/flowaggregator/exporter/clickhouse.go
  pkg/flowaggregator/exporter/interface.go
  pkg/flowaggregator/exporter/ipfix.go
  pkg/flowaggregator/exporter/ipfix_test.go
  pkg/flowaggregator/exporter/log.go
  pkg/flowaggregator/exporter/s3.go
  pkg/flowaggregator/exporter/testing/mock_exporter.go
  pkg/flowaggregator/flowaggregator.go
  pkg/flowaggregator/options/options.go
  pkg/ipfix/ipfix_exporter.go
  pkg/ipfix/testing/mock_ipfix.go
  test/e2e/flowaggregator_test.go
  test/e2e/framework.go
Labels: area/flow-visibility

#6925 Automated cherry pick of #6906: Fix Windows Conformance failure by updating time
  ci/jenkins/test.sh
Labels: kind/cherry-pick

#7019 Automated cherry pick of #7012: Filter out the hostNetwork Pods locally on Linux (#7012)
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux.go
  pkg/agent/cniserver/server_windows.go
Labels: kind/cherry-pick

#6922 Add e2e test case for SecondaryNetwork of SR-IOV type
  ci/jenkins/jobs/job-templates.yaml
  ci/jenkins/jobs/projects-cloud.yaml
  ci/test-sriov-secondary-network-aws.sh
  go.mod
  go.sum
  pkg/flowaggregator/s3uploader/s3uploader_test.go
  test/e2e-secondary-network/aws/ec2.go
  test/e2e-secondary-network/infra/sriov-network-attachment-definition.yml
  test/e2e-secondary-network/infra/sriov-secondary-networks.yml
  test/e2e-secondary-network/secondary_network_test.go
  test/e2e/framework.go
  test/e2e/supportbundle_test.go
Labels: area/secondary-network

#7020 Automated cherry pick of #7012: Filter out the hostNetwork Pods locally on Linux (#7012)
  pkg/agent/cniserver/server.go
  pkg/agent/cniserver/server_linux.go
  pkg/agent/cniserver/server_windows.go
Labels: kind/cherry-pick

#7024 Automated cherry pick of #7013: Fix glob pattern in codecov action (Kind tests) (#7013)
  .github/workflows/kind.yml
Labels: kind/cherry-pick

#7028 Update Flow Aggregator documentation with v2.3 changes
  ci/jenkins/README.md
  docs/network-flow-visibility.md
Labels: kind/documentation, area/flow-visibility/aggregator
